### ISSUE TITLE
Your own example doesn't work

### ISSUE THREAD

**Issue by stevenfayers** [MicrosoftDocs/powerapps-docs#1061]
The first example doesn't work just replacing [Organization URI] with the relevant server.
The response "--batchresponse_53e834ce-0f48-492b-be99-f68caedf303a--" doesn't assist at all with debugging.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af14071e-83a5-8dde-6346-d158b4d5d66a
* Version Independent ID: 8fb0f4fb-17ff-7491-d057-a1edf9242bc8
* Content: [Execute batch operations using the Web API (Common Data Service) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/execute-batch-operations-using-web-api)
* Content Source: [powerapps-docs/developer/common-data-service/webapi/execute-batch-operations-using-web-api.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/webapi/execute-batch-operations-using-web-api.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
All the samples here are copied from requests and responses that worked.
The only manual editing was using the `[Organization URI]` placeholder.
It may be that some spacing issues were introduced in the publishing process as indicated in #938 

Composing the $batch body manually is difficult and something that really needs to be automated to be done consistently in your code.

I recommend that you study the body closely and understand exactly what the requirements are instead of just copying and pasting the example in PostMan and expecting it to work.

**Comment by stevenfayers** [comment]
Jim.

Rather than leaving it to the readership to infer the spacing that is required from the examples given, perhaps this page could be explicit in the requirements.

**Comment by JimDaly** [comment]
Please see #938 
We are leaving that issue open until we can determine a fix for the issue. 
If that can't be worked out, we may need to explicitly call out the spacing issue.
