### ISSUE TITLE
Example for LoadData

### ISSUE THREAD

**Issue by jason-russell** [MicrosoftDocs/powerapps-docs#1062]
I'd like to see an example for the LoadData. The description says that the Collection is not initialized with the correct columns and that a Collection needs to be created first. I'd like to see a simple example of this, without having to navigate through multiple pages of documentation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 440e24de-70ad-3af0-f9d5-cbb985a38742
* Version Independent ID: 58808738-2494-02be-bcc5-c904cf2e3d12
* Content: [SaveData and LoadData functions - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-savedata-loaddata#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-savedata-loaddata.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-savedata-loaddata.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by gregli-msft** [comment]
Thanks again Jason.  I have added a "simple" example for using LoadData/SaveData to the documentation.  I quoted simple because although it is about as simple as it gets, it is still 23 steps end-to-end.  It only uses three significant formulas: 

- Collect( MyItems, { Item: TextInput1.Text, Picture: Camera1.Photo } )
- SaveData( MyItems, "LocalSavedItems" )
- LoadData( MyItems, "LocalSavedItems" )
