### ISSUE TITLE
Create Collection (with columns) but no data

### ISSUE THREAD

**Issue by jason-russell** [MicrosoftDocs/powerapps-docs#1063]
The LoadData page says that I need to create a Collection with columns; however I don't have data. Can you include an example on how to start a Collection and set the required columns without data? I don't want to do a ClearCollect() and then Clear()

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9c49101-d089-7743-582f-d44973632751
* Version Independent ID: ec080088-0d3f-f9fe-7090-c140bacfc07b
* Content: [Collect, Clear, and ClearCollect functions - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-clear-collect-clearcollect#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-clear-collect-clearcollect.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-clear-collect-clearcollect.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by gregli-msft** [comment]
Thanks Jason.  The docs have been updated to clarify this point in the sixth paragraph.  Please let me know if you still have questions, this is a little different than other programming languages, and I want to make sure we explain it well.

These functions depend on the collection being implicitly defined with the presence of a **[Collect](function-clear-collect-clearcollect.md)** or **[ClearCollect](function-clear-collect-clearcollect.md)** function call in any formula within your app.  You do not actually need to call **Collect** or **ClearCollect** to load data into the collection in order to define it, which is the common case when using **LoadData** after a previous **SaveData**.  All that is needed is the presence of these functions in a formula to implicitly define the structure of the collection.  For more information see [creating and removing variables](../working-with-variables#create-and-remove-variables).
