### ISSUE TITLE
Value Colum Width 

### ISSUE THREAD

**Issue by MaTeMaTuK** [MicrosoftDocs/powerapps-docs#1066]
Could you please make value column wider?
It looks awful for now.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 427f9ba6-9fd2-8c41-12a8-1dec5966a5c8
* Version Independent ID: eb2d9b07-54f7-72dd-417c-c6376bbf76e9
* Content: [Type | Microsoft Docs - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/manifest-schema-reference/type)
* Content Source: [powerapps-docs/developer/component-framework/manifest-schema-reference/type.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/component-framework/manifest-schema-reference/type.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Power-Maverick** [comment]
This might be happening due to issue with one of the css file.
https://docs.microsoft.com/_themes/docs.theme/master/en-us/_themes/styles/1ec56684.site-ltr.css

```
.table code {
    word-break: break-all;
}

```
You might not need `word-break: break-all` here

Screenshot of the issue added.

![PCF_Types_MicrosoftDocs](https://user-images.githubusercontent.com/36135520/75284485-e9811e00-57e2-11ea-94fd-f3d0fb634d09.png)

**Comment by MaTeMaTuK** [comment]
Yes, Without _word-break: break-all;_ text is better. Who are able to remove this css param?

**Comment by Nkrb** [comment]
@MaTeMaTuK Thanks for the feedback. We have informed the engineering team to look into this issue. Closing the issue.
