### ISSUE TITLE
TextInput.Text cannot be manipulated.

### ISSUE THREAD

**Issue by roniloregino** [MicrosoftDocs/powerapps-docs#1070]
I am having issue with trying to change the TextInput.Text using a value of a Context Variable.

What I was trying to do was either of the following:
**Screen.OnVisible(
     TextInput.Text = ContextVariable;
)
Button.OnSelect(
     TextInput.Text = ContextVariable;
)**

Neither of the two are working. Not sure if it is due to how I manipulated the Text of the Text Input control.
Not sure also if how I coded the Text property manipulation is correct.

Context Variable works on the Default property though.
I will try to set Default property of the Text Input control to Context Variable.
Then in the Button.OnSelect, I will run a "TextInput.Reset" or something.

EDIT:
Using Context Variable in Default property then using "TextInput.Reset" in either Screen.OnVisible or Button.OnSelect works but I would prefer to the line below:

**TextInput.Text = ContextVariable;**

I hope you could make this functional.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ede0c713-e3ec-b9b6-d631-63eb148e73c9
* Version Independent ID: 591b57c7-decf-d71d-957b-4298e436f9b0
* Content: [Text-input control: reference - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-text-input#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-text-input.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/controls/control-text-input.md)
* Service: **powerapps**
* GitHub Login: @chmoncay
* Microsoft Alias: **chmoncay**

**Comment by gregli-msft** [comment]
The Text property of the TextInput control is an output property.  It cannot be set and that is by design.  As you discovered, the Text property is driven from the Default property (an input property) or from what a user types.  

Power Apps is not like other app tools you may have used.  It strives to be like Excel where formulas define dependencies and values that flow through the app as data and user input changes.  Setting state variables, although sometimes required, is discouraged.  If you have not already, I recommend reading through [this introductory article](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/working-with-formulas) and this [more advanced article](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/working-with-variables).
