### ISSUE TITLE
Unable to determine if activityparty is a contact or a user

### ISSUE THREAD

**Issue by peteaxtell** [MicrosoftDocs/powerapps-docs#1103]
Could not find a property named 'partyobjecttypecode' on type 'Microsoft.Dynamics.CRM.activityparty'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a077afea-0218-d8e3-6112-95ea4bb04501
* Version Independent ID: 00ba7831-fe82-4f86-2864-311a7b8375b9
* Content: [Query Data using the Web API (Common Data Service) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/query-data-web-api)
* Content Source: [powerapps-docs/developer/common-data-service/webapi/query-data-web-api.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/webapi/query-data-web-api.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
I sense that there is a product feedback item behind this question. There is no partyobjecttypecode property on the Web API [activityparty entitytype](https://docs.microsoft.com/en-us/dynamics365/customer-engagement/web-api/activityparty?view=dynamics-ce-odata-9). There is one in the ActivityParty Entity. See [PartyObjectTypeCode](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/reference/entities/activityparty#BKMK_PartyObjectTypeCode)

To submit product feedback, please use the [ideas site](https://powerusers.microsoft.com/t5/Power-Apps-Ideas/idb-p/PowerAppsIdeas) so that this can be tracked and the community can vote.

With the way it works today, you need to expand both of the single-navigation properties for systemuser or contact. Depending on which one has data, you know what type it is.

For example: 
```
{{webapiurl}}activityparties?$select=activitypartyid,_partyid_value&$expand=partyid_contact($select=fullname),partyid_systemuser($select=fullname)
```
You can find the list of available single-valued navigation properties for the activityparty entitytype [here](https://docs.microsoft.com/en-us/dynamics365/customer-engagement/web-api/activityparty?view=dynamics-ce-odata-9#single-valued-navigation-properties)

Not really sure why the Web API doesn't include the `partyobjecttypecode`. Perhaps it was considered redundant since you can use the method above to detect the type and get the data about the record in the same query?

But I can see how your query could be more efficient if you could filter on a `partyobjecttypecode` property if it was there.
