### ISSUE TITLE
Removing powerportal default styles

### ISSUE THREAD

**Issue by Digit-89** [MicrosoftDocs/powerapps-docs#1121]
Hello,
Actually there is no information on how to remove the default styles from Microsoft (see below).
```
<link href="https://content.powerapps.com/resource/powerappsportal/dist/preform.bundle-6192e4ae44.css" rel="stylesheet">
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8bc12134-33e6-ef48-6b2a-d832f3c7872f
* Version Independent ID: 7f4534e1-4742-2b7d-c2c2-160f9b8cf846
* Content: [Edit CSS in a portal - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/portals/edit-css)
* Content Source: [powerapps-docs/maker/portals/edit-css.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/portals/edit-css.md)
* Service: **powerapps**
* GitHub Login: @tapanm-MSFT
* Microsoft Alias: **tapanm**

**Comment by Digit-89** [comment]
Actual trick, if it could help someone else. Add this code in the footer (require Javascript).
```
<!-- Removing default PowerPortal styles -->
<script type="text/javascript">	
$(document).ready(function () {
    $('link[href^="https://content.powerapps.com/resource/powerappsportal/dist/preform"]').remove();
});
</script>
<!--END Removing default PowerPortal styles -->
```

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. These are default and minimum styles required for portal to function. You can edit CSS to suite your needs as described in this article using the code editor. <br> The workaround with removing link mentioned on this issue above is not supported.

**Comment by TylerBurnett** [comment]
We need the ability to delete this bundle. As front end developers you are removing our ability to write CSS without interference. 

For our current project I've decided that I would rebuild the Bootstrap less themes myself to allow for the functionality we require to do our work. Unfortunately, because you have put this untouchable css in the portal I will now struggle to make a manageable design since you are forcing styles and overriding my styles to the the selectivity of your css.

For instance, 
![image](https://user-images.githubusercontent.com/11090043/140442533-ceaa107a-ac16-4331-b65b-26f4bd7dc99c.png)

I cannot reset these input outlines without creating a specific rule to patch exactly what you've added in. Why must we write extra css to remove your css?

Please provide this functionality.

**Comment by nickdoelman** [comment]
In the future there may be new features, updates and fixes that may have dependencies or are tested against the default and minimum styles files provided as part of the core portals package.  Please feel free to provide this suggestion on https://powerusers.microsoft.com/t5/Ideas/ct-p/PA_Comm_Ideas for changes to this feature.
