### ISSUE TITLE
Admin Settings - *Notification Method

### ISSUE THREAD

**Issue by smolcykr** [MicrosoftDocs/powerapps-docs#1139]
I see no options displayed in the Notification method field when I select the dropdown. I've tried typing in Email, push, etc. but nothing seems to take.

Have I missed a step earlier in the process? How do I get around this?

Many thanks for the assistance 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6836ad5a-2de5-6223-0514-62c83ac38d17
* Version Independent ID: 8cf9565e-4998-bce4-b319-fedb7e9d835b
* Content: [Crisis communication app - sample template - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/sample-crisis-communication-app#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/sample-crisis-communication-app.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/sample-crisis-communication-app.md)
* Service: **powerapps**
* GitHub Login: @matthewbolanos
* Microsoft Alias: **mabolan**

**Comment by Jeffj124** [comment]
I also have this issue

**Comment by mr-dang-msft** [comment]
@smolcykr @Jeffj124 ,
Have you removed the SharePoint connectors in the admin app and added your own? It comes with the existing SharePoint connectors from the exported package by default.

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. We are reviewing your feedback.

**Comment by a-britten** [comment]
Getting this issue as well. Thought it might have been because I initially setup the SharePoint Site and Group as private, but changed both to public and am still getting the error.

Did remove the existing SharePoint connectors in both apps, both before and after the Site/Group privacy change.

**Comment by mr-dang-msft** [comment]
Hi @smolcykr @Jeffj124 @a-britten,
I'm investigating this issue, but am not able to replicate. We've only made two changes to the admin app since we created it:
- Removed unused fields in the forms
- Made PreferredSentNotification a required field in the form.

And the DeployLists flow has not been modified.

Can you help me check some settings on your end?
1. Confirm the SharePoint column for PreferredSentNotification indeed has the expected options. You can follow these steps:
- Go to your SharePoint site where your lists were deployed using the DeployLists flow. (e.g. https://contoso.sharepoint.com/sites/CrisisComms)
- In the left pane click Site Contents
- Open CI_configAdminSetup
- At the top right, click the settings icon > List settings
- Scroll down to the list of columns. Click PreferredSentNotification. It should look like this with the 3 options (email, Teams notification, Push notification):

![image](https://user-images.githubusercontent.com/39354102/76678946-7543ca00-6599-11ea-8856-5a279d0a8927.png)

Q1: Let me know what you see

2. Check that Items property of the combo box is pointing to the right table. Follow these steps:
- Import the admin app (if it's not already imported). 
- Remove the existing connections to SharePoint. Add your own.
- Run the App's OnStart actions now. Hover over the App object in the tree view, click its ellipsis and Run OnStart:
![image](https://user-images.githubusercontent.com/39354102/76679065-a2dd4300-659a-11ea-971d-84364ed9b30b.png)
- Go to the screen for Admin settings.
- Click the combo box for the PreferredSentNotification.
- In the top left, change the property dropdown menu to the Items property of the combo box. Provided you have not made any changes, it should be pointing to:
`Choices([@CI_configAdminSetup].PreferredSentNotification)`
- Select and hover over the formula to see a preview of its items. It should look like this:
![image](https://user-images.githubusercontent.com/39354102/76679127-18e1aa00-659b-11ea-84c1-e3328dc70419.png)

Q2: Let me know what your combo box shows.

**Comment by smolcykr** [comment]
Thank you Brian 
Yesterday I started fresh - but with one small change - I published both apps before trying to use the drop down. This time it worked. 
In my initial try I had saved both apps but had not published either when I tried to use the drop down. 
Thank you so much for your reply



Sent from Yahoo Mail for iPhone


On Saturday, March 14, 2020, 5:25 AM, Brian Dang <notifications@github.com> wrote:




Hi @smolcykr @Jeffj124 @a-britten,
I'm investigating this issue, but am not able to replicate. We've only made two changes to the admin app since we created it:
   
   - Removed unused fields in the forms
   - Made PreferredSentNotification a required field in the form.

And the DeployLists flow has not been modified.

Can you help me check some settings on your end?
   
   - Confirm the SharePoint column for PreferredSentNotification indeed has the expected options. You can follow these steps:
   
   - Go to your SharePoint site where your lists were deployed using the DeployLists flow. (e.g. https://contoso.sharepoint.com/sites/CrisisComms)
   - In the left pane click Site Contents
   - Open CI_configAdminSetup
   - At the top right, click the settings icon > List settings
   - Scroll down to the list of columns. Click PreferredSentNotification. It should look like this with the 3 options (email, Teams notification, Push notification):



Q1: Let me know what you see
   
   - Check that Items property of the combo box is pointing to the right table. Follow these steps:
   
   - Import the admin app (if it's not already imported).
   - Remove the existing connections to SharePoint. Add your own.
   - Run the App's OnStart actions now. Hover over the App object in the tree view, click its ellipsis and Run OnStart:   

   - Go to the screen for Admin settings.
   - Click the combo box for the PreferredSentNotification.
   - In the top left, change the property dropdown menu to the Items property of the combo box. Provided you have not made any changes, it should be pointing to:   
Choices([@CI_configAdminSetup].PreferredSentNotification)
   - Select and hover over the formula to see a preview of its items. It should look like this:   


Q2: Let me know what your combo box shows.

**Comment by a-britten** [comment]
I came to the same solution @smolcykr did, it was because I hadn't published the apps. Once I did that, things seemed to start working properly.
