### ISSUE TITLE
How to use default News feed from the associated Team Site

### ISSUE THREAD

**Issue by NancySkaggs2020** [MicrosoftDocs/powerapps-docs#1140]
It should be possible to hook into the News feed from the underlying SharePoint site to populate the "Company News" section in the app, rather than manually build Company News items. Please advise how this can be done. We want to offload News entry to others and this would accomplish that. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6836ad5a-2de5-6223-0514-62c83ac38d17
* Version Independent ID: 8cf9565e-4998-bce4-b319-fedb7e9d835b
* Content: [Crisis communication app - sample template - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/sample-crisis-communication-app#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/sample-crisis-communication-app.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/sample-crisis-communication-app.md)
* Service: **powerapps**
* GitHub Login: @matthewbolanos
* Microsoft Alias: **mabolan**

**Comment by NancySkaggs2020** [comment]
What would be the connector method to automatically retrieve News stories from our associated SharePoint site?

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. We are reviewing your feedback.

**Comment by mr-dang-msft** [comment]
Hi @NancySkaggs2020,
If you'd like to use an existing resource in the app, the steps might look like this, but may differ for each organization:
1. Add the desired SharePoint list to the app:
- With the app open, click the data icon in the left hand drawer.
- In the search bar, search for SharePoint. 
- In the right pane that appears, locate your SharePoint site and list which contains the list you want.
![image](https://user-images.githubusercontent.com/39354102/76679263-585cc600-659c-11ea-96b6-cdcbefa2c648.png)

2. Revise the collection for company news.
- Go to the 'Company News Screen' in the tree view
![image](https://user-images.githubusercontent.com/39354102/76679318-cbfed300-659c-11ea-9b54-8e2491f81718.png)
- Use the property drop down menu in the top left to go to the OnVisible property of the screen:
![image](https://user-images.githubusercontent.com/39354102/76679337-e9cc3800-659c-11ea-859f-51fa478febc0.png)
- By default the formula is collecting the existing CI_CompanyNews list that was deployed with the app. Change it to collect your desired list instead. Replace this table with your own:
`Filter(CI_CompanyNews,Or(Deprecated=false,Deprecated=Blank()))`
- Note that the default table is filtered to show news that has not been deprecated. You may need to determine how you want to shape your own table that comes into the app--this is up to you.

At this point you'll receive errors because the columns of your table will likely differ from the one that we have set up. You'll need to configure the NewsGallery component next so that it interacts with the new columns you're using.

3. In the tree view, click 'Components' at the top. The tree view now shows the components in the app. At any time, you can return to the app's screens by clicking Screens again.
- Scroll down to the NewsGallery component.
![image](https://user-images.githubusercontent.com/39354102/76679440-b211c000-659d-11ea-8bf4-ae4dd05f6f77.png)
- Components have custom properties. With the NewsGallery selected, go to its Items property in the right pane. It should already be pointing to the collection for news.
- Next we need to fix the gallery showing the news. It needs to show the columns you desire instead of the columns of the default list.
- In the right pane, select the galNews. Go to its Items property. Revise the columns for Title, Blurb, Details to search the fields in your table. Revise Created to the column in your table that contains a date time to sort by. 
![image](https://user-images.githubusercontent.com/39354102/76679696-a2937680-659f-11ea-9a76-ccccd6f58fb7.png)
- In the right pane, select htmNews and go to its HtmlText property in the top left property dropdown menu.
![image](https://user-images.githubusercontent.com/39354102/76679512-61e72d80-659e-11ea-8d19-069b7f806532.png)
- Expand the formula bar by selecting its bottom edge and drag down.
- Revise the columns: 
First is the elapsed time that is calculated. Change this part to ThisItem.Field1 where Field1 is the name of the column you want to calculate elapsed time from.
`If(Created<>Modified,ThisItem.Modified,ThisItem.Created)`

This one means "If the respective date time when an item in the list was modified differs from its creation date, then use the word "Updated" otherwise use "Posted"." You can use the same logic or replace it with a single string of choice (e.g. "Added ").
`If(Created<>Modified,"Updated ","Posted ")`
- In the same formula, scroll down and update the Title and Blurb columns.
- Change ThisItem.Title and ThisItem.Blurb to the columns for the title and summary of the news item in your table. 
![image](https://user-images.githubusercontent.com/39354102/76679559-cf935980-659e-11ea-837b-77b203deb597.png)
- You might need to update btnNewsLaunch to select your chosen news item. It uses the unique ID column to pick a news item. This part may differ depending on the column in your data source that you use as a unique identifier for each row.

Next we need to update the screen that expands the news that is selected so it is showing the correct columns.

4. At the top of the tree view, click Screens to return to the Screens. 
- Go to the 'Company News Detail Screen'
- Select the DetailViewer. Go to its HtmlText property and expand the formula bar.
![image](https://user-images.githubusercontent.com/39354102/76679748-07e76780-65a0-11ea-8898-78864f39d1cc.png)
- Revise instances of Title, Details and the two locations where the Created and Modified columns are referenced. Note that you do not use "ThisItem." ahead of the column name in this case since you are not in the context of a gallery.

Let me know if these instructions were helpful and which parts need elaboration.

**Comment by NancySkaggs2020** [comment]
Thanks- this looks great.
