### ISSUE TITLE
Crisis communication translation

### ISSUE THREAD

**Issue by Ezeckiel2517** [MicrosoftDocs/powerapps-docs#1153]
Maybe someone can add some steps on HOW to change the translation of the application.

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. It's already using translated text based on the Excel file as part of solution. For example, work status screen has header set as this: 
 
Coalesce(LookUp(colTranslations,Locale=varLanguage).WorkStatusQuestion,"Work status")
 
Which first checks in Excel sheet for WorkStatusQuestion and if found in local language of the user, use it. Otherwise, display in English as 'Work Status'.

**Comment by Ezeckiel2517** [comment]
Yeah I have discovered that there is an excel sheet deploy in the zip package.
Still, it would be usefull to all people if the github page described the step to update the localization with the file. There is an "How to update an app", "How to update a flow", why not adding a "How to update an app translation" ?

**Comment by tapanm-MSFT** [comment]
Thank you for the feedback. This being part of solution and without any manual intervention, is not listed. However, will consider your feedback for review. Thanks again for reaching out.
