### ISSUE TITLE
Errors in Build

### ISSUE THREAD

**Issue by rawalsagar** [MicrosoftDocs/powerapps-docs#1159]
Does not accept "using System.ServiceModel" & shows 135 errors due to this

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ccfeadcb-8074-d9de-125a-7353b1597774
* Version Independent ID: 0d857c7c-b943-7d38-b65c-1cb7b71d2cb2
* Content: [Tutorial: Write and register a plug-in (Common Data Service) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/tutorial-write-plug-in)
* Content Source: [powerapps-docs/developer/common-data-service/tutorial-write-plug-in.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/tutorial-write-plug-in.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
Can you confirm that you completed step 1 in [Create a Visual Studio Project for the Plug-in](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/tutorial-write-plug-in#create-a-visual-studio-project-for-the-plug-in)
...open a new **Class Library (.NET Framework)** project using **.NET Framework 4.6.2**.

**Comment by rawalsagar** [comment]
Dear Jim Daly,

Thanks for the prompt reply.

Yes I confirm that I have completed step 1 as prescribed, but while downloading NuGet Package, “Microsoft.CrmSdk.CoreAssemblies latest version, it offers only v9.0.2.3 (which I have downloaded) instead of v9.0.2.4 as mentioned in procedure.

Can that be the reason?


  *   Sagar Rawal.


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by JimDaly** [comment]
If you go to https://www.nuget.org/packages/Microsoft.CrmSdk.CoreAssemblies/ you should see that 9.0.2.23 (not v9.0.2.3) is the latest version. Yes, 9.0.2.23 is considered newer than v9.0.2.4.

**Comment by JimDaly** [comment]
I tested this. Here is a [video](https://youtu.be/hLiGp72oN-Y), using VS 2019 now, but should be the same.
You may need to go into the project explorer, select **References...** and explicitly add a reference to **System.ServiceModel**.

But I think the default assembly project has this selected by default.

**Comment by rawalsagar** [comment]
Dear Jim,

Thanks for your support. I got the followup tool alright, now I want to add “debugging Tool in it. Can you help me with it?

Dilip

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by JimDaly** [comment]
@rawalsagar 
Documentation feedback issues allow people to raise issues about the documentation. 
In this case, I don't see anything actionable I can do to improve the documentation for this topic. IDK if you missed a step or if the instructions were unclear.

If you have any suggestions to improve this topic so that others won't encounter the 'Does not accept "using System.ServiceModel" & shows 135 errors due to this" issue you raised I will close this issue (or you can close it, I think)

If you need to learn about debugging, I ask that you find the topic related to what you want to do and use it. If there are issues with the documentation so that it can be improved, please report them using the Documentation feedback issues like you did originally.

If you are looking for someone to help you, I recommend using the forums.

https://powerusers.microsoft.com/t5/Common-Data-Service-for-Apps/bd-p/CDS_Apps
https://community.dynamics.com/f

**Comment by rawalsagar** [comment]
Dear Jim,

Thanks for your reply. I understand your job is to address docs. Related issues.

Thanks for guidance.

Have a great day.

Dilip

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by rawalsagar** [comment]
Dear Jim,

As the problem is resolved, you can close the issue.

Appreciate the prompt help extended by you.

Thank you,

Dilip.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
