### ISSUE TITLE
Lacks details

### ISSUE THREAD

**Issue by KittyDreadful** [MicrosoftDocs/powerapps-docs#1166]
This page lacks details on the types of snippets and how to edit them.  For example, what's the difference between a text snippet and an HTML snippet and how do you edit either?   Are there other kinds of snippets?  What's the syntax for using content from Dynamics in the snippet?  How do I insert a field that relates to an entity? or relates to a related entity? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b0b55a3-c138-c07f-c500-4ce5e6277cb7
* Version Independent ID: 171e50f8-946e-16c9-586f-8e457129bc9e
* Content: [Customize content by using content snippets on a portal - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/portals/configure/customize-content-snippets#feedback)
* Content Source: [powerapps-docs/maker/portals/configure/customize-content-snippets.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/portals/configure/customize-content-snippets.md)
* Service: **powerapps**
* GitHub Login: @tapanm-MSFT
* Microsoft Alias: **tapanm**

**Comment by tapanm-MSFT** [comment]
Thank you for the feedback. Content is updated with more details and example. The updates include text, HTML and liquid tag use. Using HTML in snippet instead of text allows use of HTML inside snippet for rendering. Liquid tags can be used to reference Dynamics 365 entity records. Please allow some time for changes to reflect.
