### ISSUE TITLE
The message on the right hand corner of teams

### ISSUE THREAD

**Issue by stpsupp2** [MicrosoftDocs/powerapps-docs#1179]
I found that when I change the status of in the user interface, for example: working from home/out of office. The status of my teams right hand corner will also update. But with the wrong work status. I have checked my email receive the correct message. Please help confirm.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6836ad5a-2de5-6223-0514-62c83ac38d17
* Version Independent ID: 8cf9565e-4998-bce4-b319-fedb7e9d835b
* Content: [Crisis communication app - sample template - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/sample-crisis-communication-app)
* Content Source: [powerapps-docs/maker/canvas-apps/sample-crisis-communication-app.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/sample-crisis-communication-app.md)
* Service: **powerapps**
* GitHub Login: @matthewbolanos
* Microsoft Alias: **mabolan**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. This is expected behavior. For both options (Work From Home or Out of Office), the app enables users to set a Out of Office message - which in effect will always change the Status on Teams (and O365 wide) to "Out of Office". A status for "Work from Home" at tenant level does not exist. 

- For feedback about the Crisis Communication sample template, go to https://aka.ms/crisis-communication-feedback.
- To report an issue with the Crisis Communication app, go to https://aka.ms/crisis-communication-issues.
