### ISSUE TITLE
Text Literal

### ISSUE THREAD

**Issue by YangHongshen** [MicrosoftDocs/powerapps-docs#1207]
What is Text literal in Power App?

I encountered this issue in using RenameColumns(Collection, oldName, NewName) where oldName is a variable

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b42181e-8538-95bb-c2f6-233fb545f3fd
* Version Independent ID: 1f1bb49a-5984-e464-c881-013b79328d30
* Content: [Data types - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/data-types)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/data-types.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/data-types.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by gregli-msft** [comment]
Text literals are explained in the data types article, in the [embedded text](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/data-types#embedded-text) section.   Basically double quotes delimited, with doubled double quotes used to include a double quote in the string, same as Excel.

**Comment by Hjaf** [comment]
@gregli-msft 
The article referred to do not include the phrase "text literal" which is what the error tooltip in power apps studio displays when using variables for arguments in functions that take text literals. e.g.: 
`DataSourceInfo('Dataverse Entity', DataSourceInfo.DisplayName, locColumnLogicalName)`
![image](https://github.com/MicrosoftDocs/powerapps-docs/assets/50009020/858ab887-f27f-4170-b07f-2052e6e4dc7f)

The article referred to implies that simply adding " to the start and end of a string produces a literal string which can be used as arguments for these functions (`$"""{locColumnLogicalName}"""`). This will not work and **it is perhaps by design** to limit use of variables for some arguments, but arriving at this conclusion is not possible at the moment because this is still not clear anywhere in the documentation. This has been raised several times in various forums but seems to be ignored e.g.: 
https://powerusers.microsoft.com/t5/Building-Power-Apps/AddColumns-and-RenameColumns-expect-string-literals/td-p/147378  

I believe that this kind of unclarity in the documentation contributes to a lot of frustration and reduces confidence in power platform for both professional and non-professional low-code developers.
