### ISSUE TITLE
Don't see the option for custom domain name

### ISSUE THREAD

**Issue by dhawal16** [MicrosoftDocs/powerapps-docs#1269]
I am testing this on the tenant as Tenant Admin but i don't see this option. Is this option not available for Trial Enviornment [Not Production]?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce8c6740-12c2-5a24-9c67-55f8485fe957
* Version Independent ID: 1225db21-8bd8-ba23-ccb6-e659d92bf40b
* Content: [Add a custom domain name - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/portals/admin/add-custom-domain#feedback)
* Content Source: [powerapps-docs/maker/portals/admin/add-custom-domain.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/portals/admin/add-custom-domain.md)
* Service: **powerapps**
* GitHub Login: @tapanm-MSFT
* Microsoft Alias: **tapanm**

**Comment by vaibhavantriwale** [comment]
I guess you got it right since I was also unable to find this option even as Tenant Admin. I came across this question on Powerusers forum @ https://powerusers.microsoft.com/t5/Power-Apps-Governance-and/Custom-Domain-on-PowerApps-Portals/td-p/356177
In last comment PowerApps staff  has mentioned that "Important thing is to ensure that your powerapps portal is in production state and is not trial as this is only available for production portals."

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out and updates. The documentation is updated with this information. Please allow some time to reflect the changes.
