### ISSUE TITLE
Does all EntitySetName in lower case? Wrong EntitySetName may returned.

### ISSUE THREAD

**Issue by Flex-Xuan** [MicrosoftDocs/powerapps-docs#1287]
I don't know if it is the right place or not to report this issue.

When I using 

> /api/data/v9.1/EntityDefinitions?$select=MetadataId,LogicalName,EntitySetName 

to retrieve all EntitySetName and then using the EntitySetName to retrieve records. I found there are two entities which EntitySetName returned are wrong!

they are : knowledgearticlescategories  which EntitySetName returned is 'KnowledgeArticleCategories' and   ribbonmetadatatoprocess which returned is 'RibbonMetadataSetToProcess'

if I check from $metadata, I can see they are defined like this:

> &lt;EntitySet Name="ribbonmetadatasettoprocess" EntityType="Microsoft.Dynamics.CRM.ribbonmetadatatoprocess"/>
> &lt;EntitySet Name="knowledgearticlecategories" EntityType="Microsoft.Dynamics.CRM.knowledgearticlescategories"/>

so the EntitySetName should in lower case but returned with Camel Naming Rule. is it bug something? 

Do all EntitySetName should be lower case??? if yes I can convert all to lower case to avoid this issue.
Thanks,
Flex

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8ee6e60-f70c-b0f7-5382-8e3297aad5ff
* Version Independent ID: 963ff1af-bbf0-4297-19cd-65ae265fd187
* Content: [Retrieve metadata by name or MetadataId (Common Data Service) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/retrieve-metadata-name-metadataid?view=dynamics-ce-odata-9)
* Content Source: [powerapps-docs/developer/common-data-service/webapi/retrieve-metadata-name-metadataid.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/webapi/retrieve-metadata-name-metadataid.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by phecke** [comment]
@Flex-Xuan Thanks for the feedback. That is the way the EntitySetName naming was implemented for those two instances.

**Comment by im-rausch** [comment]
@phecke In my opinion, your answer is simply insulting. @Flex-Xuan asked you specific questions and described the situation in details. The answer you gave could have been given by anyone who read the question. This is bullying.

**Comment by JimDaly** [comment]
@im-rausch 

This forum is for feedback about documentation. It isn't the place to report bugs, and we don't guarantee to provide answers to questions.

The case of the entity set name is important and the two instances that @Flex-Xuan mentioned are not correct.  All entity set names should be lower case.

As @Flex-Xuan found, changing the values to lower case for these two tables solves the problem.

For example, sending this:
GET /api/data/v9.2/KnowledgeArticleCategories

returns:

404
{"error":{"code":"0x80060888","message":"Resource not found for the segment 'KnowledgeArticleCategories'."}}

But lower case `knowledgearticlecategories` returns a 200.

I would say that this is a bug. The `EntityMetadata.EntitySetName` values in the definition of these tables are incorrectly set. But the Web API manages to correct this when listing the [EntitySet resources](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/webapi/query-data-web-api?view=dynamics-ce-odata-9#entityset-resources). That service document is the source of truth. You should depend on the OData service documents rather than the EntityMetadata properties.

I think that after reading @Flex-Xuan's question, @phecke was simply acknowledging that these two tables were set incorrectly. I hope I've added enough background to satisfy anyone who might find this thread in the future.
