### ISSUE TITLE
Is blank a word or an empty string or something else?

### ISSUE THREAD

**Issue by ianmckay-pmail** [MicrosoftDocs/powerapps-docs#1342]
Is blank a word or an empty string or something else?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb4730ed-889e-9f35-89c2-26bad76646a9
* Version Independent ID: 09485d1f-9219-0ca7-1122-7c6dbcb8edc0
* Content: [Filter, Search, and LookUp functions - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-filter-lookup#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-filter-lookup.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-filter-lookup.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by gregli-msft** [comment]
Blank is a null value in databases and other languages.  We use the term Blank because that is what Excel uses and we try to align to Excel whenever possible.  There is a [discussion in the Data Types article](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/data-types#blank).   We don't link to this information often and perhaps we should, I'll take that up with the documentation editors.
