### ISSUE TITLE
Assinged to field not working

### ISSUE THREAD

**Issue by abarek** [MicrosoftDocs/powerapps-docs#1361]
I'm unable to type in the Assigned To: field.  I'm able to enter it in the SharePoint list and it displays fine after that.

Any suggestions on something that's missing?

**Comment by phecke** [comment]
@abarek I cannot tell what you are doing by your description above. Are you using PowerApps and creating a model-driven or canvas app? It is best if you provide a documentation link that relates to what you're doing.

**Comment by abarek** [comment]
Sorry about that.   I thought I was posting to the help desk power app channel.  It's a power app canvas.  I have it working in teams.  There is a field for assigned to but it cannot be filled in..  does this help at all.

Ken Abare
IT Director
D&D Building

________________________________

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. It might help if the connections, especially the Office 365 Users, are verified that they exist and work correctly. And you can also try to refresh the browser when replaying the app. You can also try to use a test SharePoint list with a test column of person/group type; and use this list in canvas app to check what the behavior is in this environment. If this still doesn't work, please reach out using a [support service request](https://admin.powerplatform.microsoft.com/support) so that the support teams can help investigate the issue in your environment and help you fix.
