### ISSUE TITLE
Upsert option is not clearly documented

### ISSUE THREAD

**Issue by akill25445** [MicrosoftDocs/powerapps-docs#1423]
Please elaborate on the upsert piece. If possible with an example. Reading through the current content, I really couldn't make out how to use an upsert using Web API

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08356781-8ff5-8696-0072-89fb392acc7a
* Version Independent ID: 80f74dc0-cb69-3ee7-0990-fc656e1c66ed
* Content: [Update and delete entities using the Web API (Common Data Service) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/update-delete-entities-using-web-api?source=docs#feedback)
* Content Source: [powerapps-docs/developer/common-data-service/webapi/update-delete-entities-using-web-api.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/webapi/update-delete-entities-using-web-api.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
Content says:

> An upsert operation is exactly like an update. It uses a PATCH request and uses a URI to reference a specific entity. The difference is that if the entity doesn’t exist it will be created. If it already exists, it will be updated. Normally when creating a new entity you will let the system assign a unique identifier. This is a best practice. But if you need to create a record with a specific id value, an upsert operation provides a way to do this. This can be valuable in situation where you are synchronizing data in different systems.

What part of this is the problem?
The example is identical to update using PATCH, except that the GUID value will be one you make up rather than one that exists.

The thing which may be missing is how this is frequently used with an alternate key.
We have an example showing retrieving with an alternate key:
[Retrieve using an alternate key](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/retrieve-entity-using-web-api#retrieve-using-an-alternate-key)

Would a similar example for Upsert help?

**Comment by akill25445** [comment]
1) For me it'd have made more sense if the "id" is replaced by GUID (or) may be referred in the parenthesis like id (GUID).
2) Specifying about the alternate key with an example would have made my life so easier. (I understand that the alternate key was specified in the "Retrieve an entity" page but honestly I did not refer that page because my focus was to get the _upsert_ working.)
Hope it makes sense ?

**Comment by JimDaly** [comment]
Thanks for your feedback.
We can include an example showing use of the alternate key here.
Keeping this open until this is done.

**Comment by JimDaly** [comment]
Quite a lot of content was added to address this since this issue was opened.
See 

- [Upsert a table row](https://docs.microsoft.com/en-us/power-apps/developer/data-platform/webapi/update-delete-entities-using-web-api?source=docs#upsert-a-table-row)
- [Use Upsert to Create or Update a record](https://docs.microsoft.com/en-us/power-apps/developer/data-platform/use-upsert-insert-update-record?tabs=webapi)
