### ISSUE TITLE
Web Page address missing

### ISSUE THREAD

**Issue by nickbrandl** [MicrosoftDocs/powerapps-docs#1445]
In the "Step 4: Add a webpage", you don't specify what the url for the web page is. Using this step by step guide, I was able to display search results, but It seems I cannot browse to the details page (which I assume is what we create on step 4).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62fc0169-247f-15d5-44ee-be841d655127
* Version Independent ID: a08847b8-e801-987f-1288-2d1acb9f7ef7
* Content: [Global search for additional entities in Power Apps portal - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/portals/configure/search-additional-entities)
* Content Source: [powerapps-docs/maker/portals/configure/search-additional-entities.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/portals/configure/search-additional-entities.md)
* Service: **powerapps**
* GitHub Login: @tapanm-MSFT
* Microsoft Alias: **sandhan**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. The page created in step 4 needs to be used in [step 5 instructions](https://docs.microsoft.com/powerapps/maker/portals/configure/search-additional-entities#step-5-add-a-site-marker-for-the-search-results-details-page) to create site marker. Since this is a walkthrough with sample illustration, you can either keep the page URL default or change as per your requirement. This is the page that shows details of the record when you select in search results. If this still doesn't work. please to support team with a [service request](https://admin.powerplatform.microsoft.com/support) to help you investigate and fix the issue.
