### ISSUE TITLE
Minor edit in text that's conveying possibly opposite meaning vs intent

### ISSUE THREAD

**Issue by samathur** [MicrosoftDocs/powerapps-docs#1464]
I believe in the following sentence, the author wants to imply the lower level entities within the component list such as forms within entities are quite large in number. Hence, the NOT highlighted in bold should be removed. 

There are actually twice as many types of components as shown in the preceding list, but most of them are **not** nested within other components and not visible in the application.

**Comment by phecke** [comment]
@samathur Please provide us a link to the topic that you are referring to and we will take a look. Thanks

**Comment by samathur** [comment]
The second to last paragraph on https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/solutions-overview

**Comment by Mattp123** [comment]
@samathur - Thanks for following up. You're correct with your suggested revision, however that topic has been restructured and the content that listed the components has been removed (similar information about how to view the available solution-aware components can be found here: https://docs.microsoft.com/en-us/power-platform/alm/solution-concepts-alm#solution-components). We removed the static list because it will vary based on your environment version and what solutions are installed. 

Closing issue
