### ISSUE TITLE
Is Xrm.Page still supported for Ribbon?

### ISSUE THREAD

**Issue by FixRM** [MicrosoftDocs/powerapps-docs#1482]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87b97b2f-e00e-a277-e17a-44a8f30956ca
* Version Independent ID: a58d5ec5-169e-3483-2bac-b13b54778035
* Content: [Define ribbon enable rules (model-driven apps) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/define-ribbon-enable-rules#custom-rule)
* Content Source: [powerapps-docs/developer/model-driven-apps/define-ribbon-enable-rules.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/define-ribbon-enable-rules.md)
* Service: **powerapps**
* GitHub Login: @JesseParsons
* Microsoft Alias: **jeparson**

**Comment by JesseParsons** [comment]
@bishalgoswami can you please assign to @hazhoumsft ?  I will send a PR to update the author of that article.

**Comment by bishalgoswami** [comment]
@JesseParsons @KumarVivek I have assigned this Issue to Vivek for now. It couldn't be assigned to @hazhouMSFT because he has not joined the MicrosoftDocs org yet. @hazhouMSFT you need to join the MicrosoftDocs org to be able to contribute to Docs.

Thanks,
Bishal

**Comment by Nkrb** [comment]
@FixRM Use of the Xrm.Page object as a static access to the primary form context is still supported to maintain backward compatibility with the existing scripts, and won’t be removed as soon as some other client API methods listed in the Client API deprecation section. We recommend that you use the new formContext object instead of the Xrm.Page object in your code targeting version 9.0 or later where possible. Also, using the formContext object enables you to create common event handlers that can operate either on a form or in an editable grid depending on where its called. More information: getFormContext (Client API reference).

Getting the formContext object for JavaScript functions for ribbon actions is different from how you get it in form scripting. More information: [Form and grid context in ribbon actions](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/pass-data-page-parameter-ribbon-actions#form-and-grid-context-in-ribbon-actions). Closing the issue.
