### ISSUE TITLE
Outdated documentation

### ISSUE THREAD

**Issue by rpeters-gom** [MicrosoftDocs/powerapps-docs#1519]
I should enable feature **Use display names** like described here in step 1: https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/use-native-cds-connector#relational-data-option-sets-and-other-new-features-for-common-data-service-is-off

But feature is missing in advanced settings.
In step 2 I should enable **Use GUID data types instead of strings**. This is also missing.

Please update the documentation so I can migrate the powerapp to new CDS connector.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aeef79b7-79cc-cdb7-2da0-62b1329a37af
* Version Independent ID: 080ad9b8-4ba8-2a13-6f4d-57d4350de1b3
* Content: [Upgrade to use native Common Data Service connector - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/use-native-cds-connector)
* Content Source: [powerapps-docs/maker/canvas-apps/use-native-cds-connector.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/use-native-cds-connector.md)
* Service: **powerapps**
* GitHub Login: @tapanm-MSFT
* Microsoft Alias: **lanced**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Please read the note [here](https://docs.microsoft.com/powerapps/maker/canvas-apps/use-native-cds-connector#relational-data-option-sets-and-other-new-features-for-common-data-service-is-off): 

*If you don't see Relational data, option sets and other new features for Common Data Service in Advanced settings, or if it’s already On, skip the following steps and continue to the next section.*

Depending on outcome, you may skip to [next section](https://docs.microsoft.com/powerapps/maker/canvas-apps/use-native-cds-connector#improve-data-source-experience-and-common-data-service-views-is-off).

Also, please read if this helps - if [Improve data source experience and Common Data Service views* is On](https://docs.microsoft.com/powerapps/maker/canvas-apps/use-native-cds-connector#improve-data-source-experience-and-common-data-service-views-is-on).

For assistance with migration, migration deadline obstruction due to issues or if you need help, please reach out to support teams with a [support ticket](https://admin.powerplatform.microsoft.com/support) so that they can help you out.
