### ISSUE TITLE
Batch requests and API limits

### ISSUE THREAD

**Issue by ashlega** [MicrosoftDocs/powerapps-docs#1558]
Could you confirm if every batch request will be counted as a single request from the entitlement limits perspective, too? Right now batches are specifically called out for the service protection limits, but, since entitlement limits are tied to licensing(unlike service protection limits), it's not clear if the same logic applies (it seems it does, but, when discussing licensing, it needs to be absolutely clear)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b61960df-dcdc-d4e5-749b-0f55e22a385d
* Version Independent ID: baddf389-6252-fe30-1a60-48c18f256ed8
* Content: [API limits overview (Common Data Service) - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/api-limits-overview)
* Content Source: [powerapps-docs/maker/common-data-service/api-limits-overview.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/api-limits-overview.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
@ashlega 
Content in this topic today relating to Entitlement limits says

> For Common Data Service, API requests include all data operations that interact with entity records where records are created, retrieved, updated, or deleted (CRUD). Special operations such as share and assign are included because they are considered updates. These requests can be from any client or application and using any endpoint. These include, but are not limited to, operations performed by plug-ins, async workflows, custom controls, and $batch (ExecuteMultiple) operations. There are a small set of system internal operations that are excluded, like login, logout, and system metadata operations.

What part of this is not clear?

The intent is to convey that the batch operation itself is not counted for entitlement, but the operations included within the batch are when they "*... interact with entity records where records are created, retrieved, updated, or deleted (CRUD).*"

**Comment by bthompson-365** [comment]
The text is clear I think the issue both Alex and myself have is that that sentence seems to have been changed quietly without it being announced and noted.

I know that last year when I was working for Microsoft on a project batch requests were a means of avoiding the API limits as 1 batch file was counted as a single request (and I suspect that very large European customer will be very annoyed when they discover this change).

**Comment by JimDaly** [comment]
Understood. I wrote this topic in November of last year and applied some changes after review by the entitlement limits owners.. The reason to add this topic was to limit the scope to CDS and separate the _service protection limits_ concept from the _entitlement limits_ concepts.

This concept separation was necessary so that I could provide more details about the _service protection limits_ within this topic:
https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/api-limits

This topic is only intended to be an overview. In the process of reviewing the content, I found the issue about batch was not clear, so in review with the entitlement limit area owners this point about batch was added.

If this was ambiguous earlier, this change is intended to help. Having batch counted as a single request for entitlement limits is a pretty clear gap in the intent for entitlement limits, and would lead people down a path where they would use batch for everything, which is not a good design choice.

I don't see anything actionable here in terms of the documentation, so I'll close this issue.
