### ISSUE TITLE
How we can sync failures?

### ISSUE THREAD

**Issue by anilvem1** [MicrosoftDocs/powerapps-docs#1757]
How to re sync if any failures in Export to Data Lake solution?
One of my Export to Data lake in CDS environment is not pushing any data as part of Initial sync and it stuck for last 2 days. So wanted to know what to do in case of sync failures?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 771a2696-1d5a-88c0-299e-320d03a536c3
* Version Independent ID: 0b729e37-ce56-6d84-f44b-a22666776cec
* Content: [Export to data lake - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/export-to-data-lake)
* Content Source: [powerapps-docs/maker/common-data-service/export-to-data-lake.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/export-to-data-lake.md)
* Service: **powerapps**
* GitHub Login: @sabinn-msft
* Microsoft Alias: **matp**

**Comment by sabinn-msft** [comment]
Best option now would be to drop and re-add entity (disable and then enable entity)

**Comment by subashsivaji** [comment]
@sabinn-msft Is there better way to deal with sync failures? Currently we cannot just disable and enable single entity. We get an error that says `Please wait for the initial sync of data to complete before updating the table list.`

How do we address failures? What happens when there is a failure during incremental sync - we cannot unlink and link entire data lake again?

![image](https://user-images.githubusercontent.com/10966624/100610354-74112380-3307-11eb-8f2f-1157e1953bd3.png)

**Comment by sabinn-msft** [comment]
Lets close this one and continue discussion on the email thread we started.

**Comment by Mattp123** [comment]
Closing issue.
