### ISSUE TITLE
Is it possible to invoke AAD auth/Oauth secured Azure function from Dynamics CRM plugin using webhook?

### ISSUE THREAD

**Issue by arunvinoth** [MicrosoftDocs/powerapps-docs#1796]
Looking for inputs or confirmation about the possibility on this topic.

No problem with public Azure function (open HTTP trigger) or accessing using function key. Whereas AAD secured is throwing 401-forbidden response. https://community.dynamics.com/crm/f/microsoft-dynamics-crm-forum/357955/how-to-connect-to-azure-function-which-is-configured-for-azure-active-directory-authentication-from-dynamics-crm/940630

It is becoming repeat ask in community. https://stackoverflow.com/q/64179051/7920473

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42dbdb06-f634-7af2-8054-eef3c9ae49db
* Version Independent ID: dea28d93-ba3b-1020-77ca-f03b2a4773ef
* Content: [Register a webhook (Common Data Service) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/register-web-hook)
* Content Source: [powerapps-docs/developer/common-data-service/register-web-hook.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/register-web-hook.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
This is a known challenge which Web Hooks doesn't even attempt to address. Your options are limited.
So this is a feature request rather than a documentation issue.

If you attempt to call such an authenticated service using an HttpClient in a plug-in, you have more options. But none of them today represent best practices that we would recommend specifically at this time, although I see people making them work in community posts. Setting a certificate or secret value within the secure configuration of the plug-in seems to be the best solution I've seen. But we are looking to provide something better.
