### ISSUE TITLE
The query has problems. please correct it.

### ISSUE THREAD

**Issue by luoyong0201** [MicrosoftDocs/powerapps-docs#1868]
The query has problems. please correct it.
We can register Update message plugin for Usersettings entity.
But the query only returns retrievemultiple message for plugin

{{webapiurl}}sdkmessages?$select=name
&$filter=isprivate eq false 
and (name ne 'SetStateDynamicEntity' 
and name ne 'RemoveRelated' 
and name ne 'SetRelated' and 
name ne 'Execute') 
and sdkmessageid_sdkmessagefilter/any(s:s/iscustomprocessingstepallowed eq true 
and s/isvisible eq true)
&$expand=sdkmessageid_sdkmessagefilter($select=primaryobjecttypecode;
$filter=iscustomprocessingstepallowed eq true and isvisible eq true)
&$orderby=name

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afbf0dbd-40c9-b1a0-3f21-b98c20bc49d7
* Version Independent ID: 9232684b-31ab-a4ba-f48e-3170e38b5beb
* Content: [Event Framework (Common Data Service) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/event-framework#available-events)
* Content Source: [powerapps-docs/developer/common-data-service/event-framework.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/event-framework.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
I don't think there is anything wrong with this query.

Run this query in Postman

{{webapiurl}}sdkmessages?$select=name
&$filter=isprivate eq false 
and (name ne 'SetStateDynamicEntity' 
and name ne 'RemoveRelated' 
and name ne 'SetRelated' and 
name ne 'Execute') 
and sdkmessageid_sdkmessagefilter/any(s:s/iscustomprocessingstepallowed eq true 
and s/isvisible eq true and **s/primaryobjecttypecode eq 'usersettings'**)
&$expand=sdkmessageid_sdkmessagefilter($select=primaryobjecttypecode;
$filter=iscustomprocessingstepallowed eq true and isvisible eq true **and primaryobjecttypecode eq 'usersettings**')
&$orderby=name

I’ve added **just a couple of filters** to reduce the amount of data that is returned so that only those results for ‘usersettings’ entity are returned. This makes it easy to see that both messages are included.
I get these results:

{
    "@odata.context": "https://yourorg.crm.dynamics.com/api/data/v9.1/$metadata#sdkmessages(name,sdkmessageid_sdkmessagefilter(primaryobjecttypecode))",
    "value": [
        {
            "@odata.etag": "W/\"31457440\"",
            "name": "**RetrieveMultiple**",
            "sdkmessageid": "03bebb1b-ea3e-db11-86a7-000a3a5473e8",
            "sdkmessageid_sdkmessagefilter": [
                {
                    "@odata.etag": "W/\"31432156\"",
                    "primaryobjecttypecode": "usersettings",
                    "_sdkmessageid_value": "03bebb1b-ea3e-db11-86a7-000a3a5473e8",
                    "sdkmessagefilterid": "83ee100e-9f22-406a-b147-22f3b776f67d"
                }
            ]
        },
        {
            "@odata.etag": "W/\"35426775\"",
            "name": "**Update**",
            "sdkmessageid": "20bebb1b-ea3e-db11-86a7-000a3a5473e8",
            "sdkmessageid_sdkmessagefilter": [
                {
                    "@odata.etag": "W/\"31438421\"",
                    "primaryobjecttypecode": "usersettings",
                    "_sdkmessageid_value": "20bebb1b-ea3e-db11-86a7-000a3a5473e8",
                    "sdkmessagefilterid": "da32c642-41f0-4f9b-a5e8-33783f1bee00"
                }
            ]
        }
    ]
}

This demonstrates that both of the messages valid for **usersettings** are returned.
If you are getting different results, then let me know.

You can also run the equivalent FetchXml query. Note how all the same conditions are part of the filter.

If you aren't running this in PostMan to see the raw results, consider how you are viewing the results.
If you are viewing the results through some other way, such as described in this blog post [Find Messages and entities eligible for plug-ins using the Common Data Service](https://powerapps.microsoft.com/en-us/blog/find-messages-and-entities-eligible-for-plug-ins-using-the-common-data-service/), take a close look at that data to verify that there are not additional filters applied.
