### ISSUE TITLE
Typo on page

### ISSUE THREAD

**Issue by jennifer-caviness** [MicrosoftDocs/powerapps-docs#1950]
[Document1.pdf](https://github.com/MicrosoftDocs/powerapps-docs/files/5574570/Document1.pdf)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b64f6ab7-293a-325f-01e7-a7cb556b6037
* Version Independent ID: fe876141-ec73-bdea-48ea-af8d2d5dc81b
* Content: [Overview of the Power Apps app in Microsoft Teams - Power Apps](https://docs.microsoft.com/en-us/powerapps/teams/overview-of-the-power-apps-app)
* Content Source: [powerapps-docs/teams/overview-of-the-power-apps-app.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/teams/overview-of-the-power-apps-app.md)
* Service: **powerapps**
* GitHub Login: @chmoncay
* Microsoft Alias: **chmoncay**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Updated:
*When you select an environment from the list, you'll see the recent resources built by the selected environment's team, or the apps installed in the selected environment on the right side of the screen.*
If there's any additional feedback, please feel free to submit new issue. Please add relevant text in GitHub issue when raised, instead of file upload.
