### ISSUE TITLE
Query Functions Support of Column from Parent Table

### ISSUE THREAD

**Issue by LinnZawWin** [MicrosoftDocs/powerapps-docs#1952]
Does query functions support the column from the parent table?

`GET [Organization URI]/api/data/v9.1/accounts?$filter=primarycontactid/createdon ne null`
The normal filter with the column from the parent table works well as in the query above.
But the column from the parent table cannot be passed as a parameter into the query function and as a result, the following query does not work.
`GET [Organization URI]/api/data/v9.1/accounts?$filter=Microsoft.Dynamics.CRM.Last7Days(PropertyName='primarycontactid/createdon')`

If it is not supported, can you please add the Note to mention the limitation of query functions which only support the column from the main table and not from the related tables?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0db17aa6-b445-ec98-f3ed-1d019a0eddd2
* Version Independent ID: 7ec7d3a4-bdb6-565f-e070-16711ef06679
* Content: [Use Web API functions (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/use-web-api-functions#bkmk_composeQueryWithFunctions)
* Content Source: [powerapps-docs/developer/common-data-service/webapi/use-web-api-functions.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/webapi/use-web-api-functions.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
**Note**: Since this is not a UI operation, I will use the OData terminology rather than 'table' or 'column'.

I think it is a bit of a leap to expect that the query function parameter refers to anything other than the simple properties of the entitytype.
The name of the parameter is `PropertyName`, it is not `PathToProperty`.

The error returned, while a bit verbose, makes this clear as well:

`'Account' entity doesn't contain attribute with Name = 'primarycontactid/createdon' and NameMapping = 'Platform'. MetadataCacheDetails: ProviderType=Dynamic, StandardCache=True, IsLoadedInStagedContext = False, Timestamp=39620500, MinActiveRowVersion=39620500, MetadataInstanceId=44806734`
