### ISSUE TITLE
Where is the powerapp saved/published

### ISSUE THREAD

**Issue by smartner** [MicrosoftDocs/powerapps-docs#197]
When you begin designing a new powerapp, where is it saved? when you "publish" a powerapp, what does it mean to "publish"? Is the powerapp moved from the local device to Microsoft cloud - where is it stored? Does publishing change attributes of the powerapp or copies/moves the powerapp to another location?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c73b33f-c31c-429a-6adb-2613991a6469
* Version Independent ID: 31c8663c-72ba-b474-67fa-d5ca56e985ba
* Content: [Save and publish a canvas app - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/save-publish-app)
* Content Source: [powerapps-docs/maker/canvas-apps/save-publish-app.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/save-publish-app.md)
* Service: **powerapps**
* GitHub Login: @AFTOwen
* Microsoft Alias: **anneta**

**Comment by AFTOwen** [comment]
@smartner Thanks for your question. Here's what I know so far:
- Apps are always saved to the cloud unless you specify that you want to save them locally.
- Apps are published starting with the very first auto-save or intentional save.
- If you haven't shared an app, only you can run it or open it for editing.
- If you've shared an app, publishing changes makes them available to everyone with whom you've shared the app.

Does that help?

cc: @emcoope-msft
