### ISSUE TITLE
Web service URLs and geographic location

### ISSUE THREAD

**Issue by MichaelWeberMSFT** [MicrosoftDocs/powerapps-docs#1985]
can you please add the information related to the physical location of the service of each Web service URLs, similar to this article:
https://docs.microsoft.com/en-us/previous-versions/dynamicscrm-2016/developers-guide/gg328127(v=crm.8)?redirectedfrom=MSDN

example: crm6.dynamics.com = Oceania, crm17.dynamics.com = Switzerland etc.

thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50c7eba9-4a15-6e98-a5d0-26fcb3677021
* Version Independent ID: db92dd4f-7db7-3fce-de75-4935192e7e55
* Content: [Discover the URL for your organization (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/discover-url-organization-web-api)
* Content Source: [powerapps-docs/developer/common-data-service/webapi/discover-url-organization-web-api.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/webapi/discover-url-organization-web-api.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
That old topic a list of the regional discovery service endpoints. Which have been deprecated.

This topic is about how to discover the URL using the global discovery service.
If we have to list all the regional deployments, we have to touch this page everytime something changes. Since it isn't directly related to the task of this topic, it isn't relevant.
You don't need to know these details to use the global discovery service.

But I think you are looking for a list of regional URL representing data centers, I think it ought to be in the administrators guide.

I create this issue: https://github.com/MicrosoftDocs/power-platform/issues/500
