### ISSUE TITLE
msdyn_imageblob  ?size=null parameter problem

### ISSUE THREAD

**Issue by Zerglrisk** [MicrosoftDocs/powerapps-docs#1993]
[Enter feedback here]
i trying to retrieve msdyn_imageblob from crm sdk. 

can retrieve it but size is soo small, so i trying to enter size=null parameter,  but it can't 
can you write more guide in here for get msdyn_imageblob origin size?

![1111](https://user-images.githubusercontent.com/8271831/101883427-96921f00-3bda-11eb-94d0-a6bb3c26dc0a.png)
trying to enter parameter ,

![2222](https://user-images.githubusercontent.com/8271831/101883436-98f47900-3bda-11eb-8c83-94931d9e22e0.png)
can retrieve small size (i think this is default)

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7fe995cf-0261-7f67-70d5-4b2c969ebfd8
* Version Independent ID: 636b86b5-98d9-ebc8-103c-98080a68492f
* Content: [msdyn_richtextfile entity reference (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-gb/powerapps/developer/common-data-service/reference/entities/msdyn_richtextfile)
* Content Source: [powerapps-docs/developer/common-data-service/reference/entities/msdyn_richtextfile.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/reference/entities/msdyn_richtextfile.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by Zerglrisk** [comment]
9 days, i just call web-api for that

**Comment by riaandelange** [comment]
The Microsoft documentation is very vague on the subject of storing files on the msdyn_richtext entity solution.
By default the images being uploaded will be resized to 144x144px. If it is smaller then those dimensions will be used.
In order to download the original file you have to fetch it from another URL stored on the entity as its been stored in blob storage by the solution. 

i.e. /api/data/v9.0/msdyn_richtextfiles(d6b2fd42-a0aa-ec11-9840-002248936a59)/msdyn_imageblob/$value?size=full

or  /api/data/v9.0/msdyn_richtextfiles(d6b2fd42-a0aa-ec11-9840-002248936a59)
- then fetch the **msdyn_imageblob_url** value, i.e. "/Image/download.aspx?Entity=msdyn_richtextfile&Attribute=msdyn_imageblob&Id=d6b2fd42-a0aa-ec11-9840-002248936a59&Timestamp=637836333878712357"

References
https://docs.microsoft.com/en-us/powerapps/maker/data-platform/types-of-fields#image-columns
https://docs.microsoft.com/en-us/dynamics365/customer-engagement/web-api/msdyn_richtexteditor?view=dynamics-ce-odata-9

**Comment by phecke** [comment]
@Zerglrisk Closing this issue as it has been answered. If you are still having trouble finding an answer in our documentation, file a new issue.
