### ISSUE TITLE
Missing Data Source File

### ISSUE THREAD

**Issue by JasonM72** [MicrosoftDocs/powerapps-docs#2003]
[Hello,
The document states: 

The examples in this section use the IceCreamSales data source, which contains the data in this table:

However you do not provide a link to the excel table to download it so it can actually be used for testing.  ]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f0c1a10-93b3-16e7-bd63-013b9a0397e6
* Version Independent ID: 99628a7f-60ef-808a-1330-584d6a16b30b
* Content: [AddColumns, DropColumns, RenameColumns, and ShowColumns functions - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-table-shaping)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-table-shaping.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-table-shaping.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by Nkrb** [comment]
@JasonM72 Thanks for contacting us. We don't have any link to the data source. The table shown in the example is the actual data source we are talking about. We are only trying to explain if we had a data source like IceCreamSales, that is how the data source is modified if we use the functions as described. We will update the wordings in the doc so that it will not confuse the users. Closing the issue. If you need further help, please reopen or create a new issue.
