### ISSUE TITLE
PowerApps Option Sets - Need a definition on the page

### ISSUE THREAD

**Issue by rrgrimm** [MicrosoftDocs/powerapps-docs#2016]
I am unable to find a basic definition of an option set for PowerApps. The one page that talks of creating them never defines what an option set is, but rather starts talking about global and local option sets. Generally, when writing about creating something please assume the reader knows zero because that is likely. A basic definition along with an example or two is a nice way to start, and easily skipped by those more experienced.

I am trying to learn Power Apps, and I find this is common. Those writing assume more knowledge in the reader than is likely there. 

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d62465d1-8de8-8f8c-147c-eddfde5b677c
* Version Independent ID: ae20f053-6dee-3c39-6da0-686c0168587b
* Content: [Sample: Work with option sets (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/org-service/samples/work-with-option-sets)
* Content Source: [powerapps-docs/developer/data-platform/org-service/samples/work-with-option-sets.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/data-platform/org-service/samples/work-with-option-sets.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
This is a topic about a specific sample for developers. We expect that developers are already familiar with using the app and how to configure customizations using the UI.

Recently, the terminology changed and what developers call 'optionsets' are called 'choices' in the UI.

This topic does need to be updated to reflect that change and it should also include links to relevant non-developer topics such as [Create a choice](https://docs.microsoft.com/en-us/powerapps/maker/data-platform/custom-picklists)

While we have APIs to work with 'metadata', because there is a UI in the make.powerapps.com portal, Create, Update, and Delete operations are a bit of an advanced subject. But reading metadata is a much more common task.

**Comment by JimDaly** [comment]
Actually, since this is a topic specifically describing a sample, I don't think it needs a link the make.powerapps.com topics.
