### ISSUE TITLE
'Don't do this' page without example of how to do it

### ISSUE THREAD

**Issue by blahDL** [MicrosoftDocs/powerapps-docs#2035]
This page says not to use batch request types in plug-ins and workflow activities but does not say how you should perform these sorts of actions, How about providing a code example of how you should do it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8a6f6d7-f1bb-9767-c76f-c1cd8912941c
* Version Independent ID: d24fcbbb-ce0a-ecd5-6e16-2ff8b03d90bd
* Content: [Avoid usage of batch request types in plug-ins and workflow activities - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/best-practices/business-logic/avoid-batch-requests-plugin)
* Content Source: [powerapps-docs/developer/data-platform/best-practices/business-logic/avoid-batch-requests-plugin.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/data-platform/best-practices/business-logic/avoid-batch-requests-plugin.md)
* Service: **powerapps**
* GitHub Login: @jowells
* Microsoft Alias: **jowells**

**Comment by phecke** [comment]
@blahDL 

Guidance would be simply to submit each request directly instead of batching them and submitting as a single request.  

There is no inherent benefit when executed inside a plugin and actually adds both computational and maintainability overhead.  Also, transactional support (at DB level) is inherently provided when executing within the scope of a plugin.  

Your code should look something like:
`
foreach (request in requests)
   service.Execute(request)
`

I will review the topic and update as needed.
