### ISSUE TITLE
Dataverse references

### ISSUE THREAD

**Issue by josshaw** [MicrosoftDocs/powerapps-docs#2048]
Hi - it reads like someone has incorrectly done a search a replace on this page, with the "Dataverse" appearing in contexts I wouldn't expect  - e.g. "Dataverse environment". Worth checking maybe.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffddfc22-4030-baeb-7e0e-dd83d982a90b
* Version Independent ID: 8da908d8-04f0-db2f-c4d9-1f9487476303
* Content: [Introduction to solutions - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/introduction-solutions#feedback)
* Content Source: [powerapps-docs/developer/data-platform/introduction-solutions.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/data-platform/introduction-solutions.md)
* Service: **powerapps**
* GitHub Login: @shmcarth
* Microsoft Alias: **jdaly**

**Comment by Mattp123** [comment]
@josshaw - I see two references to "Dataverse environment" in the article that are both correct since they're specific to reference a Power Platform environment that includes Dataverse (i.e. a Dataverse environment). Removing "environment" from either or both sentences would make them inaccurate and confusing. 
Closing issue.
