### ISSUE TITLE
Aggregate query issue with Virtual Entities

### ISSUE THREAD

**Issue by piyush-bhatnagar** [MicrosoftDocs/powerapps-docs#2187]
Unable to execute aggregate queries with virtual entities (tables), tested with custom and the OData provider. Runtime throws an exception even before it hits the plugin. Is this an issue or restriction? If this is a restriction, please explain the reasoning behind this.

**Comment by Prospero100** [comment]
To add detail: The following exception is thrown by the platform **before** calling the data provider to handle the query...

[Microsoft.Crm.ObjectModel: Microsoft.Crm.ObjectModel.QueryExpressionConverterPlugin]
[f0e9800e-e081-eb11-a812-000d3a87428a: External plug-in implementation]
{
Exception details: 
ErrorCode: 0x80040315
Message: FetchExpression cannot be converted because aggregates aren't supported by QueryExpression
TimeStamp: 2021-03-10T21:12:38.8989807Z
}

**Comment by phecke** [comment]
@piyush-bhatnagar 

Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, visit [https://powerapps.microsoft.com/support/](https://powerapps.microsoft.com/support/).

You can also try posting your issue to one of the developer forums.

We accept incorrect or missing documentation and sample code issues.
 
Closing this issue.

**Comment by oiluis** [comment]
> Unable to execute aggregate queries with virtual entities (tables), tested with custom and the OData provider. Runtime throws an exception even before it hits the plugin. Is this an issue or restriction? If this is a restriction, please explain the reasoning behind this.

Were you able to solve this? If so, can you explain how? I am using OData to query a virtual entity and I am facing the same blocker
