### ISSUE TITLE
Conflicting information on delegation - 2228905

### ISSUE THREAD

**Issue by BerndKroon** [MicrosoftDocs/powerapps-docs#2196]
[Enter feedback here]
At one point it us stated that the aggregate function 'Average' is delegable: 

> Aggregate functions
> Sum, Average, Min, and Max can be delegated.

Then some lines later, referring to an example with 1 million records, it is stated that Average is " not yet" a delegable function:

> Aggregate functions can also cause confusion. Take Average over a column of that same million-record data source. Average can't yet be delegated, so only the first 500 records are averaged. If you're not careful, a partial answer could be misconstrued as a complete answer by a user of your app.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad97e638-1f17-ffb2-452f-8073a2bffa63
* Version Independent ID: 7ade66f5-aab6-0627-6d3b-914006718930
* Content: [Understand delegation in a canvas app - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/delegation-overview)
* Content Source: [powerapps-docs/maker/canvas-apps/delegation-overview.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/delegation-overview.md)
* Service: **powerapps**
* GitHub Login: @lancedMicrosoft
* Microsoft Alias: **lanced**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Both are correct. The 2nd example with possibility of delegation for average function with a million record data source is because the aggregate delegation is limited to only 50,000 records in Dataverse. [More information - Yes #5 for Sum, Min, Max, Avg](https://docs.microsoft.com/connectors/commondataservice/#power-apps-delegable-functions-and-operations-for-the-cds-for-apps)
