### ISSUE TITLE
Help page should show which screen or crumb trail points to the screen shot. 

### ISSUE THREAD

**Issue by ToddShelton** [MicrosoftDocs/powerapps-docs#2207]
I can't match the screen shot to any screens I use--PP Admin, PA Admin.  I don't use canvas apps so if you can only see it there, I'll never see it. 

The best solution is a crumb trail, but a sentence describing the path will work fine too.  

Please fix this--I'm trying to get that damn CDS connector to run (it stopped two days ago) and I'm looking at any idea to get it going again.  

Thanks, Todd

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6ef9b3a-5d99-1ca0-0e7f-80c2de740313
* Version Independent ID: 80900e35-c8da-10a1-9902-343e84d823d0
* Content: [Connect to Microsoft Dataverse - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/connections/connection-common-data-service)
* Content Source: [powerapps-docs/maker/canvas-apps/connections/connection-common-data-service.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/connections/connection-common-data-service.md)
* Service: **powerapps**
* GitHub Login: @tapanm-MSFT
* Microsoft Alias: **lanced**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. When a canvas app is created in a Microsoft Dataverse environment, a connection is already present. Since you're not aware of how to create apps, please refer to the following documentation first before understanding reading about connecting to a Dataverse environment or use the connector.

- [Create a canvas app from a sample in Power Apps](https://docs.microsoft.com/powerapps/maker/canvas-apps/open-and-run-a-sample-app)
- [Create a canvas app from Microsoft Dataverse in Power Apps](https://docs.microsoft.com/powerapps/maker/canvas-apps/data-platform-create-app)
