### ISSUE TITLE
Xrm.WebApi.online.execute Prototype Recommendation

### ISSUE THREAD

**Issue by clurdish** [MicrosoftDocs/powerapps-docs#2248]
There should be some explanation as to why the `getMetadata` function needs to be on the function prototype. 

I've worked in multiple production instances where this function was not on the prototype level and it works as expected (pared down example below).

```typescript
Xrm.WebApi.online.execute({
    getMetadata: function () {
        return {
            parameterTypes: {},
            operationType: 1,
            operationName: "cc_MyCustomAction"
        };
    }
});
```

This leads me to believe that the documentation is inaccurate or should explain when this potentially breaking change was/will be introduced. If this is purely code preference or a recommendation, it should be removed from the docs or at the very least be moved to a separate "Recommendations" section.

This was previously not included in the documentation and was added as of commit 6e95c65ae616bd907aae6f1bfca68ad71824f988. Maybe @ankarm can comment as the commit author.

A compelling reason that this matters is that TypeScript does not have a way to define that a property must exist on the object prototype. This has led the community project [@types/xrm](https://www.npmjs.com/package/@types/xrm) to type the `execute` method parameter as `any` ([reference](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/1da5f8b3b13a6cbe0f6677329e93acea233da0a3/types/xrm/index.d.ts#L5119)).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: badde453-a02f-72e1-22dd-3be9ed53a4c0
* Version Independent ID: 1904f78b-93c7-86f8-d6f2-96c4e6041f11
* Content: [Xrm.WebApi.online.execute (Client API reference) in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/xrm-webapi/online/execute)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-WebApi/online/execute.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-WebApi/online/execute.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by ankarm** [comment]
@clurdish 
We want all the "data" related to the actual request to CDS to be defined on the object instance as object properties. The `getMetadata()` is merely a name (that we decided as standard) for a function that provides some metadata about the request for the internal code to be able to serialize the request properly for CDS. 
Depending on the type of request, the serialization logic behind the scenes iterates through the properties of the input object considering those properties as necessary "data" for the request and serializes the request accordingly. We do not want `getMetadata()` to show up as an object property at that time. This is especially true for Function type of requests. (e.g. `WhoAmI`)

For the community project @types/xrm - The `execute` method parameter could be typed as required provided the consumer of the type creates a `class` that `implements` the interface.

For example, if the type of the `execute` method parameter was, let's say, `ODataContract`, like so:

``` TypeScript
interface ODataContractMetadata {
    boundParameter: any,
    parameterTypes: any,
    operationType: any,
    operationName: string

}
interface ODataContract {
    getMetadata(): ODataContractMetadata 
}
```

Then the consumer of the `Xrm.WebApi.online.execute()` method would need to create the request object like:
```TypeScript
class WhoAmIRequest implements ODataContract {
    public getMetadata(): ODataContractMetadata {
        return {
            boundParameter: ...,
            parameterTypes: ...,
            operationType: ...,
            operationName: ...
        }
    }
}
```

Meanwhile, I will discuss this with my team and see if there's something we can do to address this problem and make it so that the getMetadata() need not be defined on the prototype.

**Comment by clurdish** [comment]
@ankarm Thank you for the detailed response!

We're thinking along similar lines for the TypeScript interface, but the problem is that the TypeScript compiler doesn't enforce that those properties must be on the object prototype. There would be no type safety for the following.

```typescript
const whoAmIRequest: Xrm.WebApi.ODataContract = {
    getMetadata() {
        return {
            boundParameter: ...,
            parameterTypes: ...,
            operationType: ...,
            operationName: ...
        };
    }
}
```

I would imagine that the `execute` implementation could ignore the that function since it's a special function, roughly something like below.

```javascript
const data = {};
for(let key of Object.keys(request)) {
    if (key !== "getMetadata" || typeof request[key] !== "function") {
        data[key] = request[key];
    }
}
```

I'm looking forward to hearing what your team decides.

**Comment by Nkrb** [comment]
@ankarm To confirm whether we can close this issue.

**Comment by ankarm** [comment]
Hi @clurdish,

We are currently working on a fix for this that should be rolled out globally over the next few weeks. This issue can be closed after the fix has been checked in to master.

**Comment by Nkrb** [comment]
@clurdish  Closing the issue. This issue is fixed and rolled out. If you need further help, please reopen or create a new issue.
