### ISSUE TITLE
Web access from a plug-in

### ISSUE THREAD

**Issue by MoeJw** [MicrosoftDocs/powerapps-docs#2267]
as mentioned in the documentation below, you can use HttpClient or WebClient in sandboxed plugin to access external web resource  without any problem 
[https://docs.microsoft.com/en-us/powerapps/developer/data-platform/access-web-services](url)

but I'm facing an issue when I try to call an extrnal web api from plugin
![image](https://user-images.githubusercontent.com/42002662/114300337-7f9c0480-9ac8-11eb-9f3b-4f98c7e7bb6e.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e40287f8-6fe2-70ef-1143-2d0c039b049d
* Version Independent ID: 3d8970b6-d835-19af-c0f4-232323b552eb
* Content: [Sample: Web access from a plug-in (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/org-service/samples/web-access-plugin)
* Content Source: [powerapps-docs/developer/data-platform/org-service/samples/web-access-plugin.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/org-service/samples/web-access-plugin.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **pehecke**

**Comment by JimDaly** [comment]
@MoeJw 
Doc feedback issues are for areas of the documentation that can be improved.
Seems you have verified that the example provided in the documentation works, but not when calling the specific resources you need.

Perhaps there is some missing bit of information in the docs which could help you succeed, but I'm afraid I don't know what it is either.

A few thoughts:
1. Do you see this error when you use the Plug-in profiler? My guess is yes. Have you verified that the same error occurs at run-time using tracing?
 Plug-in profiler attempts to re-create the sandbox runtime locally, but it has been known to throw some false positives since it isn't perfectly in sync with the actual sandbox runtime. I know there was an issue with the plug-in profiler applying code access security policies where the sandbox runtime does not. The results I find from internet search for this error looks similar.
2. I won't be able to troubleshoot this with you. Recommend you contact support.
