### ISSUE TITLE
Exporting as managed solution is unavailable and importing the solution in another environment fails

### ISSUE THREAD

**Issue by timothybohte** [MicrosoftDocs/powerapps-docs#2315]
On this site page it's implied that you can export the solution as managed. This is not available at the moment. Please notity the readers when this will become available. 

It's also stated on this page that solutions can be moved between environments via exporting and importing. This fails with the reason that the environments have different publishers even though the both are Dataverse for Teams environments. Please check this out and reconcider the information stated about this on the page.

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 998b6a1a-a578-f7ce-52e6-1d504e55bbd1
* Version Independent ID: 0189e16d-f8af-e510-3b01-939dd6afd84a
* Content: [Move customizations between environments - Power Apps](https://docs.microsoft.com/en-us/powerapps/teams/import-solution-in-teams)
* Content Source: [powerapps-docs/teams/import-solution-in-teams.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/teams/import-solution-in-teams.md)
* Service: **powerapps**
* GitHub Login: @wimcoor
* Microsoft Alias: **wimcoor**

**Comment by wimcoor** [comment]
Thanks for reaching out @timothybohte. 

The goal of the Power Apps app in Teams and Dataverse for Teams is to simplify some of the more advanced concepts that come with Power Apps and Dataverse. We consider solution management as one of those more advanced concepts. 

You probably noticed that the Power Apps client embedded in Teams does not even expose solutions explicitly. Therefore, we also provided a simplified export mechanism which allows you to simply select customizations and export. Behind the scenes we compose an unmanaged solution for you that gets exported into the zip file that is then downloaded. I believe the current documentation specific to Dataverse for Teams does not mention you can export a managed solution. However, I can certainly make a change to explicitly mention that this type of export always creates an unmanaged solution. 
Note that it does mention you can import managed solutions into Dataverse for Teams, which you can, and they land under the "Installed Apps" tab in the Build hub. 
 
Additionally, I can share that "solution-aware" makers can still leverage all their favorite solution concepts, like creating solutions and exporting them as managed, using the full Power Apps or Power Automate maker portals. In the coming weeks we'll provide an easy way for makers to navigate from the Teams client to the Power Apps web portal (https://make.powerapps.com) for the selected environment.

Finally, I am sorry to hear that your export/import failed from one Dataverse for Teams environment to another. This should not be an issue and you should not be getting errors for a publisher mismatch. Can you share the detailed error message and maybe your session details so that we can further investigate and resolve this? Alternatively, please create a support case.

**Comment by wimcoor** [comment]
Thanks for reaching out @timothybohte. 

The goal of the Power Apps app in Teams and Dataverse for Teams is to simplify some of the more advanced concepts that come with Power Apps and Dataverse. We consider solution management as one of those more advanced concepts. 

You probably noticed that the Power Apps client embedded in Teams does not even expose solutions explicitly. Therefore, we also provided a simplified export mechanism which allows you to simply select customizations and export. Behind the scenes we compose an unmanaged solution for you that gets exported into the zip file that is then downloaded. I believe the current documentation specific to Dataverse for Teams does not mention you can export a managed solution. However, I can certainly make a change to explicitly mention that this type of export always creates an unmanaged solution. 
Note that it does mention you can import managed solutions into Dataverse for Teams, which you can, and they land under the "Installed Apps" tab in the Build hub. 
 
Additionally, I can share that "solution-aware" makers can still leverage all their favorite solution concepts, like creating solutions and exporting them as managed, using the full Power Apps or Power Automate maker portals. In the coming weeks we'll provide an easy way for makers to navigate from the Teams client to the  Power Apps web portal (https://make.powerapps.com) for the selected environment.

Finally, I am sorry to hear that your export/import failed from one Dataverse for Teams environment to another. This should not be an issue and you should not be getting errors for a publisher mismatch. Can you share the detailed error message and maybe your session details so that we can further investigate and resolve this ? Alternatively, please create a support case.

**Comment by Mattp123** [comment]
@timothybohte - the article has been updated to specifically state the the solution packages you export or unmanaged. 

Closing issue.
