### ISSUE TITLE
Common Data Service still used

### ISSUE THREAD

**Issue by manuelap-msft** [MicrosoftDocs/powerapps-docs#2449]
Hello,

throughout this page (I mostly noticed it under Limitations), Common Data Service is still used when it should now be Microsoft Dataverse.

Thank you
Manuela 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba670cf8-5810-79c4-7a2a-101099ffe1d7
* Version Independent ID: 69b7e1fb-9f56-8c07-b1d5-8480fe6d8e1a
* Content: [Use environment variables in solutions - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/data-platform/EnvironmentVariables)
* Content Source: [powerapps-docs/maker/data-platform/EnvironmentVariables.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/EnvironmentVariables.md)
* Service: **powerapps**
* GitHub Login: @caburk
* Microsoft Alias: **caburk**

**Comment by Mattp123** [comment]
@manuelap-msft - thanks for your feedback. The references to Common Data Service weren't updated because the name change for the Common Data Service **_connector_** took awhile to update (after the official name change). That rollout has completed and the article has been updated to reflect the current connector name. 
Closing issue.
