### ISSUE TITLE
asynchronous or synchronous?

### ISSUE THREAD

**Issue by ramontebar** [MicrosoftDocs/powerapps-docs#2456]
Hi @JimDaly, did you mean "**synchronous**" in this paragraph?:

"
- The custom api Allowed Custom Processing Step Type property should be set to Async Only. This will prevent any **asynchronous** steps from being applied for this API.
"

![image](https://user-images.githubusercontent.com/7858467/122082432-e8209e00-cdf7-11eb-853f-99b130ff204d.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c7c89b5-6d70-0f43-954f-070daaa5f6f3
* Version Independent ID: 12235e60-0f0a-37e2-40bb-e9f5330b9031
* Content: [Microsoft Dataverse business events (preview) - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/data-platform/business-events)
* Content Source: [powerapps-docs/maker/data-platform/business-events.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/business-events.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
Thanks Ramon - You are right.
BTW - I'm in the process of moving this page.

**Comment by ramontebar** [comment]
You're welcome @JimDaly. I really like this new business events feature and the documentation you have put together so far! 😀 May I know where this page will be moved to?

**Comment by JimDaly** [comment]
Just moved it to a different folder.
There is a re-direct in place so the old URL works, but now you will find it in the **developer** folder rather than the **maker** folder.

This link:
   https://docs.microsoft.com/en-us/powerapps/maker/data-platform/business-events

Will take you to where the topic is now:
   https://docs.microsoft.com/en-us/powerapps/developer/data-platform/business-events

**Comment by ramontebar** [comment]
Thanks @JimDaly!
