### ISSUE TITLE
MacOS PowerApps CLI Auth Steps

### ISSUE THREAD

**Issue by JTRemington** [MicrosoftDocs/powerapps-docs#2462]
On MacOS, where Multi Factor Authentication is enabled for a tenant, the flags `--name` and `--kind` were needed to authenticate. MSAL did not launch the native browser without those flags. Without them, the following error was given:

`"Error: Only loopback redirect uri is supported, but app://[APPID REDACTED]/ was found. Configure http://localhost or http://localhost:port both during app registration and when you create the PublicClientApplication object. See https://aka.ms/msal-net-os-browser for details"`

Attempting to authenticate with `--username`  & `--password` failed with:

`"Error: AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access '00000007-0000-0000-c000-000000000000'. "`

Until MSAL launches the authentication web view without those flags, the documentation ought to call out the necessity of using them.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf4e3c9e-af16-604e-43d7-179252741bdb
* Version Independent ID: ce493d89-9f8c-ac80-6e77-00e5a6f84077
* Content: [Tutorial - Use Microsoft Power Platform CLI with portals - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/portals/power-apps-cli-tutorial#step-3-download-portals-content)
* Content Source: [powerapps-docs/maker/portals/power-apps-cli-tutorial.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/portals/power-apps-cli-tutorial.md)
* Service: **powerapps**
* GitHub Login: @neerajnandwana-msft
* Microsoft Alias: **nenandw**

**Comment by davidjenni** [comment]
Hi @JTRemington,

yes, this is a known limitation on macOS: the pac CLI does not yet support interactive OAuth authentication flows. We are working on addressing this in a future release of the pac CLI (which will ship with a future release of the PowerPlatform VS Code extension).
This limitation is also mentioned in the release notes in https://aka.ms/ppcvscode

Since your AAD instance requires ConditionalAccess/MFA for your user credentials, your otherwise correct workaround to use --username/--password authN failed.

To work around the AAD ConditionalAccess requirement, the best practice is to use appID/SPN authentication, by supplying a --tenant, --applicationId, --clientSecret triple. To create one, please refer to the documentation and a PowerShell script as documented in: https://aka.ms/buildtools-spn
Note that the reference PS script needs to run on Windows Desktop Powershell

CC: @kkanakas @neerajnandwana-msft
