### ISSUE TITLE
Missing instructions for Model driven app session IDs

### ISSUE THREAD

**Issue by denisem-msft** [MicrosoftDocs/powerapps-docs#2535]
There is no instruction on how to get session IDs for model driven apps here. It needs instructions for both the player (in the mobile app and web player), as well as in the designer studios. It would also be good to show how to get it in the maker portal in general (with the gear icon).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf7b75ec-2194-9cbb-d321-71ba81990643
* Version Independent ID: 5ed344a8-55e7-385a-9298-7f587e213b86
* Content: [Get a session ID or a canvas-app ID - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/get-sessionid)
* Content Source: [powerapps-docs/maker/canvas-apps/get-sessionid.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/get-sessionid.md)
* Service: **powerapps**
* GitHub Login: @tapanm-MSFT
* Microsoft Alias: **tapanm**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Since this is a troubleshooting topic to get session ID, the expectation is that the user is already aware of how to get to the maker portal. If not, you can browse using https://make.powerapps.com. 

Though this topic is for canvas app session ID, will pass on the feedback for model-driven app ID. While running the model-driven app ID, I've seen the session ID accessible from the gear icon on the top-right > **About** > and the session ID is listed on the dialog box.
