### ISSUE TITLE
Page doesn't define whether and where to use schema name vs logical name

### ISSUE THREAD

**Issue by stevenfayers** [MicrosoftDocs/powerapps-docs#2726]
Page doesn't define when and where to use schema name vs logical name, given that the APIs are, unfortunately case sensitive, and creating fields in Dynamics, unfortunately defaults one to lower case and the other to Pascal case.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c5424f5-e734-423d-2baf-d7f82d500c96
* Version Independent ID: 4c1116df-37f5-0be4-6c94-3e3939e4cdb2
* Content: [Query data using the Web API (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/webapi/query-data-web-api)
* Content Source: [powerapps-docs/developer/data-platform/webapi/query-data-web-api.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/webapi/query-data-web-api.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by fowl2** [comment]
There's also the pluralization automatically applied :( 

The metadata document at `/api/data/v9.0/$metadata` contains the Web API names for the most (all?) things.

For entities/tables, it's a little easier to browse the [EntityDefinitions](https://docs.microsoft.com/en-us/dynamics365/customer-engagement/web-api/entitymetadata?view=dataverse-latest) `LogicalCollectionName` property either directly or using the [Metadata Browser](https://docs.microsoft.com/en-us/dynamics365/customerengagement/on-premises/developer/browse-your-metadata).

**Comment by JimDaly** [comment]
This is good feedback.
It is pretty common for people to assume that the `LogicalCollectionName` is the property, but it is actually the `EntitySetName` property. They can be different. See https://docs.microsoft.com/en-us/powerapps/developer/data-platform/webapi/web-api-types-operations#change-the-name-of-an-entity-set

**Comment by JimDaly** [comment]
@stevenfayers 
Thank you for your feedback and sorry for the delay in responding.
Since you have added this feedback we have added more content related to understanding the service documents which are the actual source of truth regarding the names used by the Web API.  

These topics should be considered 'required reading' before moving on to actually performing the operation with Web API. See [Web API types and operations](https://docs.microsoft.com/en-us/power-apps/developer/data-platform/webapi/web-api-types-operations) and the other topics in that section to understand what names to use.
