### ISSUE TITLE
Issue with Configuring the Tools path in Power Platform Tools

### ISSUE THREAD

**Issue by awadbensaleh** [MicrosoftDocs/powerapps-docs#2729]
I dont see the tools path after i installed the power platform tools. Also there is no way to configure the tools path either in the screen shot below neither in your screenshot that you posted. 

![image](https://user-images.githubusercontent.com/31972160/133359155-7813101b-a305-4bb8-86f4-de9f6763f960.png)

 Getting an error when trying to deploy, as we did not configured the tool path ?

![image](https://user-images.githubusercontent.com/31972160/133359303-1c070b42-dec2-46f0-a7fe-13854020807b.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d709296-ee38-4b31-a3b3-2a532ed06908
* Version Independent ID: ef0cedf7-60d7-b0ca-770f-a69759bb59e5
* Content: [Install Power Platform Tools - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/tools/devtools-install)
* Content Source: [powerapps-docs/developer/data-platform/tools/devtools-install.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/tools/devtools-install.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @phecke
* Microsoft Alias: **pehecke**

**Comment by phecke** [comment]
@awadbensaleh There is no tool path to set otherwise we would describe how to set it in the docs. Are you still having this trouble? What version of the extension are you installing?

Make sure that you follow these instructions. The extension is not available in VS until you load a solution containing one or more Power Platform Tool templates.

_After installing Power Platform Tools, you will not find any Power Platform Tools related menu items or views in the Visual Studio user interface until you create or load a Visual Studio solution that contains at least one project created from a Power Platform Tools template._

**Comment by phecke** [comment]
@awadbensaleh  FYI, you will get a quicker response by submitting your tool feedback as described here: [Providing tool feedback](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/tools/devtools-create-plugin#providing-tool-feedback)

Of course this assumes that the extension is installed and working correctly.

**Comment by Pankaj-Thakur** [comment]
@awadbensaleh If you still run into issues please reach out to powerplatformvs@microsoft.com with the activity log if possible - https://docs.microsoft.com/en-us/visualstudio/ide/reference/log-devenv-exe?view=vs-2019
