### ISSUE TITLE
Provide example on splitting with linefeed

### ISSUE THREAD

**Issue by lordneeko** [MicrosoftDocs/powerapps-docs#2768]
Please add examples to show using the split() function on a string with linefeeds. The resulting array should result in one item per line in the input string

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2dc17706-b063-fd81-634a-2db0a9d8988e
* Version Independent ID: 1ec42eef-5290-2a9c-d207-6e1dcf239472
* Content: [Split function in Power Apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-split)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-split.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/functions/function-split.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Not clear about the linefeeds, but since this is a consulting scenario, please try reaching out to the [Power Apps community forum](https://powerusers.microsoft.com/t5/Forums/ct-p/PA_Comm_Forums) for help. If you're experiencing any issue, create a [support ticket](https://docs.microsoft.com/power-platform/admin/get-help-support).
