### ISSUE TITLE
No response after record create. Hangs as token does not delete

### ISSUE THREAD

**Issue by tacklers** [MicrosoftDocs/powerapps-docs#2792]
We have built an API with CDSWebApiService and followed the instructions to the letter.

Accessing a vanilla tenancy with hardcoded credentials the API gets a token, creates a record but no response.

It cannot delete the token so hangs. Lines 69 - 469.

We have had 4 programmers look at this but no joy.

An MVP reported the same issue in September/2020 and abandoned trying, reverting to the Organizational approach.  

https://powerusers.microsoft.com/t5/Power-Apps-Pro-Dev-ISV/Azure-Web-API-and-CDSWebApiService-Class/m-p/691218#M3339

We decided to start from scratch with an Organizational API but will come back to this as soon as fixed. if we still have jobs after letting the business down! Cheers, Richard 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d571fd40-cd40-e93c-0dce-82a4c3bc2694
* Version Independent ID: c0f13c24-8e61-e197-8392-c1028a906e58
* Content: [CDSWebApiService class library (C#) (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/webapi/samples/cdswebapiservice)
* Content Source: [powerapps-docs/developer/data-platform/webapi/samples/cdswebapiservice.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/webapi/samples/cdswebapiservice.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **pehecke
![CDIWebApiService-line-469](https://user-images.githubusercontent.com/19391937/136601576-64466307-8fc4-4fe5-a635-e5c340b91014.png)
*
![OauthMessageHandler-line-69](https://user-images.githubusercontent.com/19391937/136601591-6b904b08-00d8-48a7-a58a-3887e46588b4.png)
*

**Comment by JimDaly** [comment]
@tacklers 
I'm sorry to hear you had trouble with the sample. This CDSWebAPIService class is a Class library project which other samples depend on: AsyncParallelOperations, BasicOperations, ConditionalOperations, ParallelOperations, and QueryData.
Were you successful in running any of those samples?

**Comment by tacklers** [comment]
Hi Jim, thanks for the follow up. It's taken me a while to get the samples running.
1. Query data. Eventually got it to work but it kept hanging on an operation and following advice I fettled the profiling then it ran okay.
![query-data-exception](https://user-images.githubusercontent.com/19391937/137642560-6dce9fa2-6c01-4749-9d86-fb7a6514e355.png).
Slightly disappointed as the clear up operation deletes everything. It does a managed export but I don't know where this file lives. 
2. Metadata. This kept stopping out of the box. I followed the code as it was erroring on the solution which was unique and did exist. I took out the not! and it then ran successfully
![solution-is-unique](https://user-images.githubusercontent.com/19391937/137642646-8554be06-2505-4d49-9f1c-32a5edb7e629.png)
3. Basic Operations. I'm not sure how to fix this yet. The first error was on the dates setup as mm/dd/yy it broke on that as I'm dd/mm/yy so I changed the dates. It now faults on competitors but I don't know why. 
![basic-operations-breaks-on-competitors](https://user-images.githubusercontent.com/19391937/137642821-08afb434-6bc5-46cb-b4c8-13f392b82537.png).
I will try AsyncParallelOperations, Conditional operations and Parallel operations.
Given that three work/nearly work I'm puzzled how my original error is connected.
It gets a token, writes data but always halts on deleting the token and we can't skip that step else it breaks the framework. 
Thanks for your help. Cheers, Richard

**Comment by JimDaly** [comment]
Richard -
Thanks for your feedback.

I added this CDSWebAPIService class several years back to improve the previous sample code we had. That original code simply created a new HttpClient with each call and had no-reusability.

The purpose of this class is to demonstrate a pattern for re-usable code that would:

- Make your code 'DRY'er by wrapping common operations by Http methods.
- Manage an HttpClient in a thread-safe manner.
- Manage Service Protection Limit API 429 Too Many Requests errors that a client application should expect.

Many of our sample scenarios require creating certain records so that actions can be performed on them, this became very tedious without some re-usable code.

Let me comment on the items you mentioned:

1. Query Data: The error in the screenshot refers to an exception in the Plug-in Profiler.  Plug-in Profiler is a solution used to debug plug-ins. See [Use Plug-in profiler](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/debug-plug-in#use-plug-in-profiler). Do you happen to be debugging a plug-in on one of these operations while you run the sample?
You also mentioned:  

> It does a managed export but I don't know where this file lives.

  The metadata sample does a managed export, but the Query Data sample doesn't. Maybe you are thinking of that sample?

2. Metadata: This sample is checked in to the repo but not documented. There are some known issues with it. This sample attempts to compose some of the common SDK metadata operations into equivalent functions and provides class definitions for the complex objects used for these operations.

3. Basic Operations: This sample was written using the full version of Dynamics 365 Customer Engagement, which includes the Sales functionality. If you are working with a new environment without the Sales solution, the `competitor `table probably doesn't exist, so the error `Resource not found for the segment 'competitors'`. suggests that is the case.

For the error you originally reported about hanging as it deletes the token: I'm also not clear about what is causing that. 
This sample is build using .NET Framework and the ADAL libraries. My expectation is that the libraries will cache the token and refresh it as needed. There should be no need to delete it.

Finally, the key point I take from your feedback is that this sample class is presented in a way that suggests it is ready for use with any project. It is a sample helper class which I used to write other samples. I hope it demonstrates some re-usable patterns that developers can adopt to use Web API, but it isn't an SDK or the only way to use Web API.  I will update the documentation to call this out.

**Comment by JimDaly** [comment]
@tacklers 
The CDSWebAPIService samples were retired and replaced with a new helper library. See [WebAPIService class library](https://docs.microsoft.com/en-us/power-apps/developer/data-platform/webapi/samples/webapiservice). This now uses .NET 6, MSAL and more current methods to manage an HttpClient.

This is a helper library designed to demonstrate best practices and support Web API sample development using .NET. But they are still sample code for educational purposes rather than for production.
