### ISSUE TITLE
Form OnLoad event vs Form data OnLoad

### ISSUE THREAD

**Issue by fowl2** [MicrosoftDocs/powerapps-docs#2827]
The [Form OnLoad event](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/events/form-onload) is described as: 
> The form OnLoad event occurs after the form has loaded.
> It also occurs after a record is saved on create or update, and on refresh. For example by selecting the Save or the Refresh button on the main form.

Whereas [Form data OnLoad](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/events/form-data-onload) says:
> On initial page load.
> When the page data is explicitly refreshed using formContext.data.refresh method.
> When the data is refreshed on a page on saving a record, if there are any changes.

I'm having trouble understanding what the difference between these is, and under what circumstances Form data OnLoad would be used. Perhaps (guessing) there was some difference pre UCI?

Could this article be updated with some guidance around this?

Thanks! 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58114325-7776-d90e-9aa5-9257b51bfa66
* Version Independent ID: 933b1a50-460c-21a3-b608-b56180c30338
* Content: [Form data OnLoad event (Client API reference) in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/events/form-data-onload)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/events/form-data-onload.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/model-driven-apps/clientapi/reference/events/form-data-onload.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by JimDaly** [comment]
@fowl2 
Sorry for the long delay in responding to this.
Thank you for your feedback.

The descriptions for the Form Onload event seem to have changed since you created this.
The current descriptions is:

[Form OnLoad event](https://docs.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/reference/events/form-onload)

> This event occurs whenever the form is loaded, specifically:
> 
> - On initial page load.
> - After a new record is first saved (created).

It appears that the description now describes that Form Onload occurs less frequently than previously described. Since it is attached to the ui area, it appears to only change when the form itself is initially loaded or reloaded to change from create to update form.

The Data onload description seems to only occur for data changes.

I hope these changes help differentiate these two events. Since this was opened so long ago, I'm going to close this with this comment. If you feel more is needed, please add a comment and I can re-open.
