### ISSUE TITLE
Change Tile for Model Driven App?

### ISSUE THREAD

**Issue by bpremji** [MicrosoftDocs/powerapps-docs#2840]
Is it possible to change the tile for a Model Driven App?  Changing the icon for a Model Driven App does not seem to reflect when using the App on a mobile device.  The icon remains blue with a jigsaw piece icon

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d076b13-d76b-6562-9af3-bfd1054a8754
* Version Independent ID: 1e078ef8-10eb-e202-5485-4da988f5905f
* Content: [Change app name and icon for canvas apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/set-name-tile)
* Content Source: [powerapps-docs/maker/canvas-apps/set-name-tile.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/set-name-tile.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @emcoope-msft
* Microsoft Alias: **emcoope**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Is this question with regards to any specific documentation topic? If so, please reference it here. The one referenced with the issue is only applicable to canvas apps. For general discussions and questions, please visit [Power Apps Community Forum](https://powerusers.microsoft.com/t5/Power-Apps-Community/ct-p/PowerApps1), or reach out using [support ticket](https://docs.microsoft.com/power-platform/admin/get-help-support).
