### ISSUE TITLE
Very incomplete content [combo box]

### ISSUE THREAD

**Issue by raphievila** [MicrosoftDocs/powerapps-docs#285]
I was looking information in how and what to set on the Default value and is not even mentioned here. neither the what value type the DefaultSelectItems value has to be, no matter what I set it gives me an error, string, text, array. Don't give any clue how to set. If I set to Parent.Default throws another error. Very frustrating, when you even have example of usage.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb8bf3d3-12e3-5b55-8713-221cf5f5a30c
* Version Independent ID: 5a050d01-6ef6-97d6-07de-d5cac82dea06
* Content: [Combo box control: reference - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-combo-box#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-combo-box.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/controls/control-combo-box.md)
* Service: **powerapps**
* GitHub Login: @fikaradz
* Microsoft Alias: **fikaradz**

**Comment by fikaradz** [comment]
You are right, documentation here isn't adequate, we'll look to improve it.

Default isn't mentioned because it shouldn't be used. DefaultSelectedItems should be used.  This expects a record that is part of the Items table.  So if your Items is set to:
Table(
  {firstName:"John", lastName:"Doe"}, 
  {firstName:"Anna", lastName:"Smith"},
  {firstName:"Peter", lastName:"Jones"}
)

Then you can set DefaultSelectedItems to one of those records, like:
{firstName:"John", lastName:"Doe"}

For more details about working with tables and records, see [this doc topic](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/working-with-tables#table).

If your Combo box is inside a form (and hence inside a data card), you can then set DefaultSelectedItems to Parent.Default as that refers to the record of the current selected value for that data field.

**Comment by AFTOwen** [comment]
Thanks, @raphievila, for the feedback. Please let us know whether @fikaradz addressed the problem. Cheers!

**Comment by raphievila** [comment]
Yes, does answer the question. basically the defaultItemsSelected is an object. But it turns more complicated when using an external source as a SharePoint list or Excel file.

Where the DefaultSelectedItem should include a Filter() method, for example:

`Filter(Table, firstName = Parent.Default)`

And that's where the documentation should be layout, to include code samples with different sources. But yes, that's a perfect answer.

Now, everytime I use a ComboBox I'm having issues sending the updated value. When the form is submitted, it resets the value to the Parent.Default filtered values. And obviously, that's not covered in the documentation.

So far, the only way I can manage to use a ComboBox is outside the form, when an item is selected, then the value is set to a Variable using UpdateContext(). The updating a Text field with that value, if the value is not equal to the Variable value.

Proper documentation is essential for proper development, doing hacks as the one that I did, can have undesired consequences in the future.

I love the PowerApps, and I'm sure with proper documentation would be a perfect solutions for businesses with Office 365.

**Comment by fikaradz** [comment]
@raphievila there shouldn't be any issues using combo box in forms.

When the form is saved, the latest value of SelectedItems is written to the data source which is then refreshed.  So when the value of SlectedItems shows Parent.Default, it is referencing the selected values from the parent Data card (which in turn references the field from the current item being viewed in the form).  Anyhow because the form is refreshed, the selected value should show the latest value that was saved.

I realize this may be a little confusing, we are trying to make working with forms simple so what happens behind the scenes is not really requirement to have it working, all can be done with our GUI studio interface.

**Comment by raphievila** [comment]
> there shouldn't be any issues using combo box in forms.

@fikaradz  You are correct, there shouldn't be any issue, but it is, and I had to spend 3 hours to work a work-around to fix the issue, that happened, even though it shouldn't, making the app unusable.

Any way, that's not the point of the conversation, I mentioned the issue to demonstrate how extremely lacking is the documentation, which is done with the purpose to educate how to properly implement tools to avoid this issue.

Since this tool is supposed to be for anyone without any knowledge of coding, the documentation is not in a level to say PowerApps is for anyone, only for people verse in YouTube, Google and Bing, that knows how to search and find solutions, and lucky enough to find them.

Sad to say to YouTubers have better content than the documentation. Is my suggestion just to embed those videos into the documentation that way we can call it complete.

**Comment by tapanm-MSFT** [comment]
Thank you for your feedback on overall documentation. As the discussion addresses primary concern, closing this issue and considering the documentation improvement feedback for overall enhancement.

**Comment by Hjaf** [comment]
@fikaradz 
> Default isn't mentioned because it shouldn't be used.

A year later and the attribute Default is visible in the studio, the fact that there are attributes not supposed to be used still available in studio should perhaps be an issue for more than just the documentation. Where can I report this issue?
