### ISSUE TITLE
Are Business Process Flows Only Available in Dynamics 365?

### ISSUE THREAD

**Issue by michaelbunney** [MicrosoftDocs/powerapps-docs#2948]
The Power Automate procedure "Create a business process flow" says to open Solution Explorer and links to this page.  But this page shows a screen shot of Dynamics 365.  What if I don't have Dynamics 365?  This information is about Power Automate generally, but as documented is implying a dependency on Dynamics 365.

Is it the case that Power Automate business-process flows are only available in Dynamics 365, as this page implies?  Or are they a general feature of Power Automate, as the Power Automate [business process flow](https://docs.microsoft.com/en-us/power-automate/create-business-process-flow) page implies?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aca92584-1ebb-b41a-471c-5be652c4fed1
* Version Independent ID: d10d62e3-4274-aa7a-fc8f-226a92292001
* Content: [Navigating to my apps, solution explorer, and settings in Power Apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/advanced-navigation#solution-explorer)
* Content Source: [powerapps-docs/maker/model-driven-apps/advanced-navigation.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/model-driven-apps/advanced-navigation.md)
* Service: **powerapps**
* Sub-service: **mda-maker**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@michaelbunney - Business process flows are available with licenses Power Apps plans and you can create and edit them using the business process flow designer. You don't need Dynamics 365. Since business process flows are type of automation (although specific to model-driven apps) you create them in Power Automate. 

Note that, some tables that use out-of-the-box business process flows specific to that table, such as the Opportunity table, do require a Dynamics 365 app license.

Closing issue.
