### ISSUE TITLE
Revise Code Examples to meet new ES-Lint requirements

### ISSUE THREAD

**Issue by ADPerkin** [MicrosoftDocs/powerapps-docs#3166]
If you are now employing ES-Lint to check code in the Solution Cheker It would be helpful if you could update the code examples in line with the new Power Platform es-lint strict requirements. In this specific example you use console statements, which are no longer valid. However, removing those and having no action, also breaches es-lint requirements. 

There are very few examples of workarounds to situations where a success/failure code has to be provided.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d991c0b4-ff31-84e2-4084-f2ef82d77588
* Version Independent ID: ad7a366f-8d17-82f5-ea6e-c5feee2545cf
* Content: [openAlertDialog (Client API reference) in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/xrm-navigation/openalertdialog)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Navigation/openAlertDialog.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Navigation/openAlertDialog.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by JimDaly** [comment]
@ADPerkin 

Sorry for the delay in responding to this. 
I looked through the linting rules included in the solution checker.

In this case, you are saying that we shouldn't use console.log in our sample code because it doesn't meet the standards for production code.

I think our sample code, particularly sample code that is included in-line with the content should, focus on helping people understand what the code does. Just because it isn't considered a best practice for production code to include console statements doesn't mean people don't use them. They are intended for use while debugging.

So, I don't think we will invest effort in revising samples to meet that standard.
Thanks,
