### ISSUE TITLE
 Please define CreateXml if you're going to use it in the sample here.

### ISSUE THREAD

**Issue by dmattsonucm** [MicrosoftDocs/powerapps-docs#3201]
Please define CreateXml if you're going to use it in the sample here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d867a76b-03c7-c4a3-313f-ee642b5f0bde
* Version Independent ID: 371fff7e-205d-4a9f-b790-5537d3113770
* Content: [Page large result sets with FetchXML (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/org-service/page-large-result-sets-with-fetchxml)
* Content Source: [powerapps-docs/developer/data-platform/org-service/page-large-result-sets-with-fetchxml.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/org-service/page-large-result-sets-with-fetchxml.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by darshSWL** [comment]
There is a link to the sample code above the code snippet. CreateXml is defined there.

"CrmServiceClient service" can be removed from the method signature, I think.

**Comment by dmattsonucm** [comment]
Well, that explains why I didn't find it because it links to a page that links to the top level of the GitHub repo. Then I need to go through the Github Repo to try to find where that's at.

It was easier to search google for this than to find it.  Not to mention you're showing passing in a string into the function and it asks for an XmlDocument doc.

CreateXml(CrmServiceClient service , XmlDocument doc, string cookie, int page, int count)

**Comment by JimDaly** [comment]
Agree that there are several issues here:
1. The code in this section is incomplete [FetchXML and the Paging Cookie Example](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/org-service/page-large-result-sets-with-fetchxml#fetchxml-and-the-paging-cookie-example). The important part that parses and works with the paging cookie data is missing.  Someone should be able to figure out the logic without having to go to the Github repo.
2. The CreateXml static method in SampleMethods.cs file should be shown in the doc.
3. The link in this Sample topic: [Sample: Use FetchXML with a paging cookie](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/org-service/samples/use-fetchxml-paging-cookie) should have a link directly to the sample rather than just to the Samples Repo.  Link to https://github.com/microsoft/PowerApps-Samples/tree/master/cds/orgsvc/C%23/UseFetchXMLWithPaging would be useful

**Comment by darshSWL** [comment]
@JimDaly 
Regarding SampleMethod.cs:

There are two very similar methods:
1. public static string CreateXml(CrmServiceClient service, string xml, string cookie, int page, int count)
2. public static string CreateXml(CrmServiceClient service , XmlDocument doc, string cookie, int page, int count)

Both methods don't make use of the CrmServiceClient parameter.
Only the first method is used in the example code. Maybe the second method could be private?

**Comment by JimDaly** [comment]
Changes checked in. s/b updated tonight or tomorrow.
