### ISSUE TITLE
Setting up postman environment is outdated

### ISSUE THREAD

**Issue by tifa64** [MicrosoftDocs/powerapps-docs#3225]
Hello,

[This](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/webapi/setup-postman-environment) wiki is outdated.

1. When trying to get token from postman it mentions

1. When trying to get token using browser it returns:

```
Request Id: 0a59d0ce-ccd3-4ea7-a3e6-aad575570900
Correlation Id: 5980d973-47fa-4dc9-a613-944a96dfd183
Timestamp: 2022-03-28T09:20:19Z
Message: AADSTS50011: The redirect URI 'https://oauth.pstmn.io/v1/callback' specified in the request does not match the redirect URIs configured for the application '51f81489-12ee-4a9e-aaae-a2591f45987d'. Make sure the redirect URI sent in the request matches one added to your application in the Azure portal. Navigate to https://aka.ms/redirectUriMismatchError to learn more about how to fix this.
```

And even when specifying the redirect URL in the Azure application to `https://oauth.pstmn.io/v1/callback` it still persists on the error.

1. This [video](https://www.youtube.com/watch?v=AmTcp-kGgpY&t=474s&ab_channel=CRMChap) shows that the api needs to grant admin permission

**Comment by JimDaly** [comment]
Thanks for your feedback.
The topic does need to be updated, since Postman changes their UI occasionally, but the core part about configuring environment variables still works.
The `{{callback}}` global variable can have the value of either `https://callbackurl` or `http://localhost`. Either should work.
From your error, it appears that you are depending on the postman value b/c it begins with `https://oauth.pstmn.io`, which shouldn't occur with the given instructions.

Please review the settings and try again.
We will update the topic to address the UI changes that occurred since it was written.

**Comment by tifa64** [comment]
Hello Jim, thank you for replying, the reason why i'm depending on postman's value is because I authorize using the browser, and the reason why i'm doing that is because when I use postman, i get 

`This application contains sensitive information and can only be accessed from:
Devices or client applications that meet Microsoft management compliance policy.
The current browser is not supported, please use Microsoft Edge, Internet Explorer, Chrome or Firefox 91+ to access this application.`

`Error Code: 53000
Request Id: e97b5360-61e7-4779-b7af-e247954b0e00
Correlation Id: 1e2c7c89-db9e-4ed7-aa14-af5d39045acd
Timestamp: 2022-04-21T08:35:36.966Z
App name: Dynamics 365 Example Client Application
App id: 51f81489-12ee-4a9e-aaae-a2591f45987d
IP address: 89.23.224.56
Device identifier: Not available
Device platform: Windows 10
Device state: Unregistered`
