### ISSUE TITLE
Missing guide how to fetch such polymorphic lookup via WebAPI (OData) query

### ISSUE THREAD

**Issue by rafek1241** [MicrosoftDocs/powerapps-docs#3293]
It would be great to have there details how to query polymorphic links via WebAPI query.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52939b82-7a1e-7320-c0a4-be2ea7f59724
* Version Independent ID: c67af10a-57f8-b450-5e0f-6c3f7d22079a
* Content: [Use multi-table lookup columns (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/power-apps/developer/data-platform/webapi/multitable-lookup?branch=pr-en-us-4448)
* Content Source: [powerapps-docs/developer/data-platform/webapi/multitable-lookup.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/webapi/multitable-lookup.md)
* Service: **powerapps**
* GitHub Login: @NHelgren
* Microsoft Alias: **nhelgren**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @rafek1241. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@rafek1241

Thanks for opening this issue.

The key to using Web API effectively is to understand how the service is defined via the CSDL $metadata service document. It is the ultimate source of truth for Web API.  I strongly recommend reviewing this topic [Web API types and operations](https://docs.microsoft.com/en-us/power-apps/developer/data-platform/webapi/web-api-types-operations) and all the topics in the group that describe how to understand the $metadata service document.

Polymorphic lookups can have multiple single-valued navigation properties. Understanding how they are expressed with [Lookup Properties](https://docs.microsoft.com/en-us/power-apps/developer/data-platform/webapi/web-api-properties#lookup-properties) is also important. Key to using them depends on identifying the name of the single-valued navigation property.  See this section: [Multi-table lookups](https://docs.microsoft.com/en-us/power-apps/developer/data-platform/webapi/web-api-navigation-properties#multi-table-lookups).

See this section of the **Query Data** topic: [Retrieve data about lookup properties](https://docs.microsoft.com/en-us/power-apps/developer/data-platform/webapi/query-data-web-api#retrieve-data-about-lookup-properties)

If this information isn't clear, please open a doc feedback issue for those topics.

Key take aways:

 - All the topics in this area should deal _only_ with CRUD of schema data (metadata) as defined by the scope of this topic: [Use the Web API with table definitions](https://docs.microsoft.com/en-us/power-apps/developer/data-platform/webapi/use-web-api-metadata). If the types are part of this group: [Web API Metadata EntityType Reference](https://docs.microsoft.com/en-us/power-apps/developer/data-platform/webapi/reference/metadataentitytypes?view=dataverse-latest), they inherit from [MetadataBase](https://docs.microsoft.com/en-us/power-apps/developer/data-platform/webapi/reference/metadatabase?view=dataverse-latest) and should be described here.
 - All information about working with table data for types that inherit from [crmbaseentity](https://docs.microsoft.com/en-us/power-apps/developer/data-platform/webapi/reference/crmbaseentity?view=dataverse-latest) should be available within the content here: [Perform operations using the Web API](https://docs.microsoft.com/en-us/power-apps/developer/data-platform/webapi/perform-operations-web-api). This includes all the system entities [Web API EntityType Reference](https://docs.microsoft.com/en-us/power-apps/developer/data-platform/webapi/reference/entitytypes?view=dataverse-latest) or custom entities.
 
This topic and others have blurred this line somewhat and we need to remove some content that talks about using table data and replace it with links to where this information is presented within [Perform operations using the Web API](https://docs.microsoft.com/en-us/power-apps/developer/data-platform/webapi/perform-operations-web-api). Otherwise, we will end up with duplicate content and confusion when people look to the metadata topics for information about how to work with data.

I already have a workitem for this and will follow up with @NHelgren. So, so closing this.

**Comment by rafek1241** [comment]
@JimDaly 
Hi Jim, Thanks for a response. I understand the whole lookup concept. The problem is that I want to use polymorphic lookup in operations like `retrieving, filtering, inserting` to the navigation property hidden under shared name and how can I achieve that? It would be great to have a guide in the docs for that.

**Comment by JimDaly** [comment]
@rafek1241 
Robert -

Thanks for providing more information.  Key challenges I've seen is that people try to guess the names of the single-valued navigation properties, so the links I included above focus on that issue. If you understand that, what specific challenges are you having?

If you are having issues with these areas, please open a _specific_ doc feedback request on these topics:

|operation|topic|
|---|---|
|`retrieving`|[Retrieve a table row using the Web API](https://docs.microsoft.com/en-us/power-apps/developer/data-platform/webapi/retrieve-entity-using-web-api)|
|`filtering`|[Query data using the Web API > Filter Results](https://docs.microsoft.com/en-us/power-apps/developer/data-platform/webapi/query-data-web-api#filter-results)|
|`inserting`|[Create a table row using the Web API](https://docs.microsoft.com/en-us/power-apps/developer/data-platform/webapi/create-entity-web-api)|

This will help us identify what specific kinds of content need to be added or revised.

Custom polymorphic lookups are a relatively new thing, but the system Customer lookup on some Dynamics 365 Customer Engagement tables is a kind of polymorphic lookup that has been around for a long time.

I don't know if this is your experience, but for people who have used our .NET SDK, polymorphic lookups are expressed as a single Attribute that allows for an EntityReference that can point to more than one Target. I find people who carry this understanding over to OData sometimes struggle because conceptually OData is very different. 

In OData, I think it is best not to focus too much on the referential constraint. Each single-valued navigation property represents a different relationship, so using them is not different than having multiple 'ordinary' lookups that each have a single-valued navigation property. The only difference is that for that group, because of the referential constraint, only one of them can have a value at a time.

Some of the implications of this that I imagine might be unexpected:

- If you try to create or update a record while setting a value to more than one of the single-valued navigation properties in a polymorphic lookup, I expect Dataverse to throw an exception.
- When constructing queries, you may have to group a combination of filters together using the logical operator `or`. This makes writing queries more complex, but doesn't introduce any new concepts.
- Sometimes there just isn't an elegant solution to get the results you want in a single query and you may have to send more than one request to get the complete set of data you need.

But IDK of these are the kinds of things people are struggling with. We don't have any more specific guidance to add at this time. But perhaps by listening to your _specific_ scenarios we may find some things to add. Can you share the specific challenges you are facing by opening up doc feedback issues for the appropriate topic above?

Thanks
