### ISSUE TITLE
There is no information on "Form field height" or "Use all available vertical space" formatting for column properties configuration.

### ISSUE THREAD

**Issue by dewilliams704** [MicrosoftDocs/powerapps-docs#3323]
There is no information on "Form field height" or "Use all available vertical space" formatting for column properties configuration.  Details of what the "User all available vertical space" checkbox actually does would be nice, as we are running into issues where the text box is not expanding as expected.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63ad3991-5f3a-4349-6974-9306225a4090
* Version Independent ID: 61ef62e7-9623-e0d4-cb8d-9733549a8744
* Content: [Add, configure, move, or delete columns on a form - Power Apps](https://docs.microsoft.com/en-us/power-apps/maker/model-driven-apps/add-move-or-delete-fields-on-form)
* Content Source: [powerapps-docs/maker/model-driven-apps/add-move-or-delete-fields-on-form.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/model-driven-apps/add-move-or-delete-fields-on-form.md)
* Service: **powerapps**
* Sub-service: **mda-maker**
* GitHub Login: @aneesmsft
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@dewilliams704 - Thank you for your feedback. The form field properties have been added to the referenced article in this issue as follows: 

Formatting | Form field height | Some columns, such as the multiline text column, let you control the height of the column by specifying the number of rows the column occupies.

Formatting | Use all available vertical space | Instead of setting the height by a number of rows, some columns, such as the multiline text column, let you set the column height to expand to all the available space on the form
