### ISSUE TITLE
Page has gone missing

### ISSUE THREAD

**Issue by rezanid** [MicrosoftDocs/powerapps-docs#3358]
I was not quite sure where to report this, so here we go. I have noticed that an important page with the following URL has gone missing for couple weeks now!
https://docs.microsoft.com/en-us/power-apps/developer/data-platform/webapi/reference/incident?view=dataverse-latest

I had this page open on a browser tab, but unfortunately I hit refresh accidentally. Usually, I would be able to find it though Google cache, but that' gone too.

I don't know what is the mechanism behind it, but I know you can access any other table/entity definition in web-api by replacing the last segment of the URL with the logical name of the table/entity you are looking for for example https://docs.microsoft.com/en-us/power-apps/developer/data-platform/webapi/reference/contact?view=dataverse-latest works fine, but `incident` has gone for good :)

**Comment by JimDaly** [comment]
@rezanid 
Thanks for your feedback. 
The reason incident isn't included anymore is because we had to cut the scope back to just the tables that are part of Dataverse. The reference documentation is generated using a program that reads the Web API $metadata and complements it with some additional metadata. With so many different solutions, we could no longer maintain such a large list and include all entitytypes, functions, and actions for all solutions.

Incident is part of the Dynamics 365 for Customer Service solution. 
The reference documentation for that table is no longer in the [Dataverse table reference](https://docs.microsoft.com/en-us/power-apps/developer/data-platform/reference/about-entity-reference) either.

Incident table reference is now here: https://docs.microsoft.com/en-us/dynamics365/customer-service/developer/reference/entities/incident 

I'm glad you found the Web API reference helpful. You might leave some feedback with the team that does the customer service product documentation and as that they include Web API reference for the components of their solution.

Your feedback is noted. If we get more feedback about this we may reconsider.
