### ISSUE TITLE
More details on Upsert process

### ISSUE THREAD

**Issue by devlinl** [MicrosoftDocs/powerapps-docs#3441]
In the section "Understanding the Upsert process" step 2 reads, "Dataverse will look up the record targeted by the target entity."

Please provide additional detail regarding how this look up occurs. What data does Dataverse use to look up the record? Is it just based on the Primary Name field? Does this process take Alternate Keys into account?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ed55813-1248-7edf-c33c-ce7a4783f9e6
* Version Independent ID: 32bc8340-84c9-8114-673f-481b3b09470f
* Content: [Use Upsert to insert or update a record (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/power-apps/developer/data-platform/use-upsert-insert-update-record)
* Content Source: [powerapps-docs/developer/data-platform/use-upsert-insert-update-record.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/use-upsert-insert-update-record.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @divka78
* Microsoft Alias: **jdaly**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @devlinl. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@devlinl 

Thanks for your feedback.

The Upsert operation expects that the table has alternate keys defined to uniquely identify a record without a primary key value. It doesn't use the primary name field (unless it is part of the alternate key)

The entity passed with the Target parameter should have values for the alternate key so that it can be uniquely identified.

This is described as part of the [Data Synchronization](https://docs.microsoft.com/en-us/power-apps/developer/data-platform/data-synchronization) topic that introduces the combination of features that support this scenario.

But I understand that someone can find this topic without reading all the topics in this group. The topic can be made more clear that this is expected.

**Comment by JimDaly** [comment]
@devlinl 

I have made significant changes to this topic to provide more details on the upsert operation [Use Upsert to Create or Update a record](https://docs.microsoft.com/en-us/power-apps/developer/data-platform/use-upsert-insert-update-record?tabs=webapi) as well as changes to other topics, such as [Use an alternate key to reference a record](https://docs.microsoft.com/en-us/power-apps/developer/data-platform/use-alternate-key-reference-record?tabs=webapi)

I hope that the additional detail provided will address the questions you and others may have on this.
