### ISSUE TITLE
ModelDriven

### ISSUE THREAD

**Issue by filsmaiga** [MicrosoftDocs/powerapps-docs#3443]
Pourquoi le nom application pilotè processus 

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 2119255f-281e-11b0-54e1-921115e21a24
* Version Independent ID: 24314dee-2250-33b0-0e4d-66a4ca17f270
* Content: [Présentation de la création d’une application pilotée par modèle avec Power Apps - Power Apps](https://docs.microsoft.com/fr-fr/power-apps/maker/model-driven-apps/model-driven-app-overview)
* Content Source: [powerapps-docs/maker/model-driven-apps/model-driven-app-overview.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/model-driven-apps/model-driven-app-overview.md)
* Service: **powerapps**
* Sub-service: **mda-maker**
* GitHub Login: @Mattp123
* Microsoft Alias: **v-roryneary**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @filsmaiga. This issue has been assigned to the doc author for review.

**Comment by Mattp123** [comment]
@filsmaiga - Model-driven apps "process driven" because, as the article states "if you are building an app to manage a complex process, such as onboarding new employees, managing a sales process, or member relationships in an organization such as a bank, a model-driven app is a great choice." Reading further into the article you'll find that you don't have to spend much time designing the UI since most is determined for you based on what process you're defining in the app. Hence the app is considered "process driven" or in other words, the app layout and design is determined by the process in which the app is built for.

Closing issue.
