### ISSUE TITLE
There is no export button in dataverse for Teams anymore

### ISSUE THREAD

**Issue by mfahsold** [MicrosoftDocs/powerapps-docs#3447]
Hello MSFT Team,

I tried to backup my solution in a Dataverse for Teams environment and was a little bit shocked, that the export button is completly missing. About last week I was able to export the solution but now I can not do an update?

This docs document says, the button and the functionality should be still there?

best Matthias
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 998b6a1a-a578-f7ce-52e6-1d504e55bbd1
* Version Independent ID: 0189e16d-f8af-e510-3b01-939dd6afd84a
* Content: [Move customizations between environments - Power Apps](https://docs.microsoft.com/en-us/power-apps/teams/import-solution-in-teams)
* Content Source: [powerapps-docs/teams/import-solution-in-teams.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/teams/import-solution-in-teams.md)
* Service: **powerapps**
* Sub-service: **teams**
* GitHub Login: @wimcoor
* Microsoft Alias: **wimcoor**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @mfahsold. This issue has been assigned to the doc author for review.

**Comment by ToddOmya** [comment]
@Mattp123 @wimcoor Any update on this? I need this urgently as I have customized the Inspections app and need to roll it out to multiple teams

**Comment by jukkan** [comment]
I'm still seeing the Export button in my Dataverse for Teams environment (runnign Teams browser client). However, if in your environment the button is missing, have you tried accessing the Maker portal and doing a solution export from there? You can access it via the Apps view and clicking on "Open in Power Apps". 

You'll need to create the solution explicitly since the UX is different from the Export experience in DV4T. For more gotchas related to solution management, check out my blog post: [Working with solutions in Dataverse for Teams](https://jukkaniiranen.com/2022/03/working-with-solutions-in-dataverse-for-teams/)

**Comment by Mattp123** [comment]
@mfahsold - This works in my basic testing from the Power Apps teams app. Make sure you have one or more components selected to trigger the commands otherwise they don't appear. 
![image](https://user-images.githubusercontent.com/21203819/200692105-649f04a0-a9df-4673-afe8-635e42f06f46.png)
