### ISSUE TITLE
A connector may provide tables of data or actions.

### ISSUE THREAD

**Issue by ravikiran-srini** [MicrosoftDocs/powerapps-docs#3479]
Hi, in the documentation, the second para states:

"A connector may provide tables of data or actions. Some connectors provide only tables, some provide only actions, and some provide both. Also your connector may be either a standard or custom connector."

**Question:**
What are the connectors that provide only tables? I checked many connectors, but each of them provides actions as well.
Looks like all the connectors provide a mix of both, so that given statement in the documentation is very confusing.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7c89a8f-b16f-2896-faae-efbb438c7a89
* Version Independent ID: 8ce453b3-7e57-c80a-7ca0-9b122ad4796b
* Content: [Overview of connectors for canvas apps - Power Apps](https://docs.microsoft.com/en-us/power-apps/maker/canvas-apps/connections-list)
* Content Source: [powerapps-docs/maker/canvas-apps/connections-list.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/connections-list.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @lancedMicrosoft
* Microsoft Alias: **lanced**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @ravikiran-srini. This issue has been assigned to the doc author for review.

**Comment by lancedMicrosoft** [comment]
From: ravikiran-srini ***@***.***>
Sent: Wednesday, June 29, 2022 11:11 PM
To: MicrosoftDocs/powerapps-docs ***@***.***>
Cc: Lance Delano ***@***.***>; Mention ***@***.***>
Subject: [MicrosoftDocs/powerapps-docs] A connector may provide tables of data or actions. (Issue #3479)


Hi, in the documentation, the second para states:

"A connector may provide tables of data or actions. Some connectors provide only tables, some provide only actions, and some provide both. Also your connector may be either a standard or custom connector."

Question:
What are the connectors that provide only tables? I checked many connectors, but each of them provides actions as well.
Looks like all the connectors provide a mix of both, so that given statement in the documentation is very confusing.

[Yes, a connector may provide both tables and actions.  However, in the context of Power Apps a connector is classified as ‘Tabular’ or ‘Action’ based.  Tabular connectors do not make actions available in the Power Apps context.  We will update the docs to make this more clear.  There is work going on to change this, but for now this is a limitation.]

________________________________
Document Details

⚠ Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.

  *   ID: e7c89a8f-b16f-2896-faae-efbb438c7a89
  *   Version Independent ID: 8ce453b3-7e57-c80a-7ca0-9b122ad4796b
  *   Content: Overview of connectors for canvas apps - Power Apps<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fpower-apps%2Fmaker%2Fcanvas-apps%2Fconnections-list&data=05%7C01%7Clanced%40microsoft.com%7Cd97d2af08ac74cedc8fb08da5a5f433c%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637921662443687962%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=fNE%2B5leJfpxWWmmbMBNaJUOOPN%2FONAZDjQ%2FNaimt77w%3D&reserved=0>
  *   Content Source: powerapps-docs/maker/canvas-apps/connections-list.md<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fpowerapps-docs%2Fblob%2Fmain%2Fpowerapps-docs%2Fmaker%2Fcanvas-apps%2Fconnections-list.md&data=05%7C01%7Clanced%40microsoft.com%7Cd97d2af08ac74cedc8fb08da5a5f433c%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637921662443687962%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=VV4uWpvh5S%2FPvOu3JWMpJnN6SR%2B9MFf%2BTf8Nxbdd3cM%3D&reserved=0>
  *   Service: powerapps
  *   Sub-service: canvas-maker
  *   GitHub Login: @lancedMicrosoft<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FlancedMicrosoft&data=05%7C01%7Clanced%40microsoft.com%7Cd97d2af08ac74cedc8fb08da5a5f433c%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637921662443687962%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=2M5CpKf0T6jTE5cDmkOIHbL5lbbBM%2BPUomYCm55EIrI%3D&reserved=0>
  *   Microsoft Alias: lanced
