### ISSUE TITLE
Suggestion to Document the Use of Xrm.WebApi without Xrm.WebApi.online or Xrm.WebApi.offline

### ISSUE THREAD

**Issue by LinnZawWin** [MicrosoftDocs/powerapps-docs#3509]
A lot of the developers that I know are getting confused with the use of Xrm.WebApi in an offline scenario and they are having a misconception that
1. Xrm.WebApi.retrieveMultipleRecords only works on online
2. they needed to use Xrm.Utility.getGlobalContext().client.isOffline() to call the online or offline API (e.g. Xrm.WebApi.online.retrieveMultipleRecords() or Xrm.WebApi.offline.retrieveMultipleRecords()).

Would it be possible to update the document that Xrm.WebApi (e.g. Xrm.WebApi.retrieveMultipleRecords) handles the both online and offline scenarios by the platform without having to determine with the client.isOffline() in the script?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8601a9f-ca1e-49e0-bdf8-383431829997
* Version Independent ID: 488d4db7-a2de-b47e-5c1c-a28a5f8e046f
* Content: [Xrm.WebApi (Client API reference) in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/reference/xrm-webapi)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/xrm-webapi.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/model-driven-apps/clientapi/reference/xrm-webapi.md)
* Service: **powerapps**
* Sub-service: **mda-developer**
* GitHub Login: @adrianorth
* Microsoft Alias: **jdaly**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @LinnZawWin. This issue has been assigned to the doc author for review.

**Comment by adrianorth** [comment]
@lancedMicrosoft can you review this request?

**Comment by JimDaly** [comment]
@LinnZawWin 
Thanks for your feedback.
According to the doc, `Xrm.WebApi` has two properties: `online` and `offline`.
Each of these properties expose a common set of methods: `createRecord`, `updateRecord`, etc.

The expectation I have from reading the docs is that the developer should detect whether their code is running online or offline and then access the methods via the appropriate property.

Your feedback suggests that the common methods are available directly using `Xrm.WebApi`, without accessing them directly via the `online` or `offline` properties. Your feedback suggests that this is managed automatically somehow. If I'm understanding you correctly, this calls into question whether the `online` and `offline` properties serve any purpose at all.

Am I understanding you correctly?

If these properties serve no purpose, it will certainly make the API easier to use. But we need to get dev team to confirm the expected behavior here.

@lancedMicrosoft Please comment on the expected behavior.

**Comment by LinnZawWin** [comment]
@JimDaly 
Your understanding is correct.
- The common methods are available directly using `Xrm.WebApi`, without accessing them directly via the `online` or `offline` properties and the platform manages automatically somehow.

I have been using the `Xrm.WebApi.retrieveMultipleRecords` and `Xrm.WebApi.retrieveRecord` API for several months in production which is used by both online and offline users. There is no issue reported so far other than having to handle the single-valued navigation property in the query as specified in the documentation.

https://docs.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/reference/xrm-webapi/retrievemultiplerecords#retrieve-or-filter-by-lookup-properties

**Comment by JimDaly** [comment]
@LinnZawWin 
Thanks for confirming. 
There has been an internal email thread about this including @lancedMicrosoft and members of the dev team.

My understanding is that the `offline` and `online` objects are not irrelevant. It seems like they were put in place to support some capabilities that have yet to be implemented.

I'm leaving this assigned to @lancedMicrosoft who will be updated the docs to fill in the gaps.

**Comment by LinnZawWin** [comment]
Thanks for the confirmation, @JimDaly. And thanks @lancedMicrosoft for updating the docs.

**Comment by JimDaly** [comment]
@LinnZawWin 

I see that this [article was updated last August](https://github.com/MicrosoftDocs/powerapps-docs/commit/7a785bd8ff80f6c276ecbacf2ace439e2c772dd0) and the following was added by @ian-legler 

> With mobile offline configured, the source for these records will depend on the current client state. In offline mode, the source is the offline data store. In online mode, the source is the server. If the client is offline-first (in preview), the methods in [online](https://learn.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/reference/xrm-webapi/online) can be used to access tables and records that are not part of the offline profile, as long as the client has network connectivity.

I trust this addresses this issue. Sorry for the delay in closing this.
