### ISSUE TITLE
Where do you change the default? [environment]

### ISSUE THREAD

**Issue by HairyDrumroll** [MicrosoftDocs/powerapps-docs#353]
Where do you change the default?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4fa02db7-a31a-cdbe-2fd4-84ec805b44b1
* Version Independent ID: 8b6de090-c3f0-0df2-86b0-50aca46bfde7
* Content: [Working with environments - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/working-with-environments)
* Content Source: [powerapps-docs/maker/canvas-apps/working-with-environments.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/working-with-environments.md)
* Service: **powerapps**
* GitHub Login: @linhtranms
* Microsoft Alias: **litran**

**Comment by AFTOwen** [comment]
Thanks, @HairyDrumroll. When you sign in to PowerApps, it automatically opens in whatever environment you were in when you signed out most recently. Does that help?

**Comment by HarryDriscollTWE** [comment]
Hi, I've now leaned that someone in our IT team created a new 'environment' and then set that new environment as the default.
Because data gateways to on-premises data sets for PowerApps and Flow are only visible to the default environment, all of my PowerApps and Flows relying on these gateways fell over.
That led me to the page referenced above and although it talks about the default environment, it doesn't say anywhere how to set what the default is.
I believe the documentation should say where the default environment is set.
