### ISSUE TITLE
Schema changes

### ISSUE THREAD

**Issue by indikaa** [MicrosoftDocs/powerapps-docs#3578]
Hi There, 
Could you please help me to understand how this temple can handle the schema/metadata changes?
i.e: adding or removing a field from an entity ?

**Comment by indikaa** [comment]
Hi this is related to this article: https://docs.microsoft.com/en-us/power-apps/maker/data-platform/azure-synapse-link-copy-sql

**Comment by JasonHQX** [comment]
@indikaa This ADF template reads Model.json file which capture all data schema change. (Not applied to datatype change since it is required to recreate the synapse link if there is a data type change). For more information: You can check this overview blog: https://community.dynamics.com/365/dynamics-365-fasttrack/b/dynamics-365-fasttrack-blog/posts/adf-template-to-copy-dataverse-data-to-azure-sql-part-1

**Comment by Mattp123** [comment]
Closing issue.
