### ISSUE TITLE
Many-to-Many (N:N) relationships for an activity

### ISSUE THREAD

**Issue by LinnZawWin** [MicrosoftDocs/powerapps-docs#3612]
Would it be possible to add a note in this article or this one [this one](https://docs.microsoft.com/en-us/power-apps/maker/data-platform/create-edit-nn-relationships) that Many-to-Many (N:N) relationship cannot be created for an activity?

I cannot seem to find that limitation in any of the articles under docs.microsoft.com.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57ef09bb-f324-47cb-1625-914db5bbc8fa
* Version Independent ID: 0328bcbb-93ac-717e-50cd-7a7fd5fcfdd5
* Content: [Activity table (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/power-apps/developer/data-platform/activity-entities)
* Content Source: [powerapps-docs/developer/data-platform/activity-entities.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/activity-entities.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @mayadumesh
* Microsoft Alias: **jdaly**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @LinnZawWin. This issue has been assigned to the doc author for review.

**Comment by phecke** [comment]
@LinnZawWin For the developer documentation, the relationships that a table/entity supports is called out in the Table/Entity reference documentation. For example, the [Task ](https://learn.microsoft.com/power-apps/developer/data-platform/reference/entities/task) reference page only documents 1:N and N:1 relationships, therefor N:N is not supported.

In the maker UI, you cannot create an N:N relationship for a task.

If we called out which entities don't support N:N in the docs, that list can change over time and the docs would become out of date without us knowing about it. Since the Table/Entity reference is generated from the web service metadata, that reference can be kept up to date easily.

**Comment by LinnZawWin** [comment]
@phecke Table/Entity reference is generated from the web service metadata which documents existing relationships but it does not specify whether N:N is supported or not. E.g. the [Account ](https://learn.microsoft.com/en-nz/power-apps/developer/data-platform/reference/entities/account) reference page documents 1:N and N:1 relationships but there is no N:N relationship either (even though N:N is supported for Account).

Is there anywhere a developer/maker can look into the documentation to find out if the table supports N:N relationship without checking in the maker UI?
