### ISSUE TITLE
More information regarding the certificate

### ISSUE THREAD

**Issue by MattyBearBytes** [MicrosoftDocs/powerapps-docs#3698]
Lots of folks are coming here now for the OAuth Implicit Grant.

Whilst the specifics of the certificate are great - what type of certificate does it need to be?
If its pre-production, and there is no custom URL, and we are still using Microsoft's URL:  how do we create that certificate?

For example, can it be the same certificate uploaded in the SSL section of the Portal Admin?
There is an error that appears when you try to upload the same certificate as SSL.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c569345a-740f-f09b-efdc-01bc0a2d99e4
* Version Independent ID: c569345a-740f-f09b-efdc-01bc0a2d99e4
* Content: [Add custom certificates - Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/portals/admin/manage-custom-certificates)
* Content Source: [powerapps-docs/maker/portals/admin/manage-custom-certificates.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/portals/admin/manage-custom-certificates.md)
* Service: **powerapps**
* Sub-service: **portals**
* GitHub Login: @neerajnandwana-msft
* Microsoft Alias: **nenandw**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @MattyBearBytes. This issue has been assigned to the doc author for review.

**Comment by Kunter-Bunt** [comment]
Just to support the claim: We have experienced the same behavior that the admin portal denies the certificate not matching the requirements although uploading it to a development instance worked fine in investigation.
It also has worked previously with that certificate when uploading it as SSL Certificate which has the same requirements. Investigation showed that you need 2 different certificates for SSL and Custom for it to work. That might even be a bug of portals, likely because the certificate store cannot handle both certificates having the same Thumbprint, but it should at least be pointed out in the docs.
![image](https://user-images.githubusercontent.com/9168648/200319076-558639df-4f3e-4cdc-87be-ada6279ad19d.png)
Cert A -> SSL Cert Portal A
Cert B -> Custom Cert Portal A
Cert B -> Custom Cert Portal B
Cert B -X SSL Cert Portal B

**Comment by nickdoelman** [comment]
Thank you for your feedback and the details. We are aware of the issue and have updated the documentation advising that the same certificate cannot be used for both custom domain names and implicit grant flow.
