### ISSUE TITLE
Cosmos DB Paritioning explanation in Dataverse

### ISSUE THREAD

**Issue by arajawat** [MicrosoftDocs/powerapps-docs#3736]
The Document tree & all related pages talk about Dataverse Web APIs but suddenly this page talks about Cosmos partitioning. This is not a right place and creates confusion if we can create partition key in dataverse or not.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 06a71082-a3db-214d-d66d-9e32f95ed992
* Version Independent ID: 596ccce9-3bf6-f6e9-14c1-3bc79db1c960
* Content: [Access entity data faster using storage partitions (Microsoft Dataverse) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/webapi/azure-storage-partitioning)
* Content Source: [powerapps-docs/developer/data-platform/webapi/azure-storage-partitioning.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/webapi/azure-storage-partitioning.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @Peakerbl
* Microsoft Alias: **peakerbl**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @arajawat. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@arajawat 
Thanks for your feedback.

Web API is my area of expertise. Not so much about Cosmos partitioning. Perhaps @Peakerbl can speak to this.

From a Web API perspective, this topic describes a dynamic process in which partitions are created while performing a POST (Create) operation on a record. Afterwards, you can use this `partitionId` when performing GET, PATCH, or DELETE operations.

I also note that there is a companion topic for this that describes using the SDK: [Improve performance using storage partitions when accessing entity data](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/org-service/azure-storage-partitioning-sdk)

So, I would say that this content is included in these places because the process of working with these keys depends on performing data operations, which is what these sections are about. 

- If this isn't the right place, where are you expecting to find it?

From an information architecture perspective, we are trying to unify content areas which are described separately for Web API and SDK. This seems like a good candidate for this. Having a single topic describing behaviors for both is a goal. 

- Is this what you are looking for?

Also, as someone with little experience or knowledge of Cosmos partitioning, the other potential gaps I see are:

> - Is it possible to create a partition without creating a record?
> - How do I get a list of the current partitions being used?
> - Will I get an error if I use a partition key value that doesn't exist?
> - How do I know which tables support use of partitions?


- Are these also questions that you have?

**Comment by JimDaly** [comment]
I've created a workitem to unify the two topics for SDK and Web API into one.
