### ISSUE TITLE
Does this work for .NET Core? If not, why?

### ISSUE THREAD

**Issue by JandosHk** [MicrosoftDocs/powerapps-docs#3791]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 61e6ca03-5e73-39aa-c2f0-2df8aa19cad9
* Version Independent ID: 4e6eb61b-e550-a1cb-6862-2ba4e9e07702
* Content: [Quick Start: Web API sample (C#) (Microsoft Dataverse) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/webapi/quick-start-console-app-csharp?tabs=msal)
* Content Source: [powerapps-docs/developer/data-platform/webapi/quick-start-console-app-csharp.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/webapi/quick-start-console-app-csharp.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @divka78
* Microsoft Alias: **dikamath**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @JandosHk. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@JandosHk 
Thanks for your feedback.

This sample is written for .NET Framework. 

As mentioned in this topic, we have a version of this sample written for .NET 6.0 here: [https://github.com/microsoft/PowerApps-Samples/tree/master/dataverse/webapi/C%23-NETx/QuickStart](https://github.com/microsoft/PowerApps-Samples/tree/master/dataverse/webapi/C%23-NETx/QuickStart).

We have more complex samples for .NET 6.0 here [https://github.com/microsoft/PowerApps-Samples/tree/master/dataverse/webapi/C%23-NETx](https://github.com/microsoft/PowerApps-Samples/tree/master/dataverse/webapi/C%23-NETx)

Is your question because you have difficulty converting the steps to .NET Core or just surprise these quick start instructions still use .NET Framework in 2022?

Updating the instructions of this Quick Start to .NET 6.0 is on our TODO list.

**Comment by JandosHk** [comment]
Thank you for the reply. I mainly use .NET Core nowadays. Browser search landed me to classic .NET sample, so I was wondering whether .NET Core support was there or not. Having both samples on the same page (or having cross links) would have helped, which will be the case, I guess, once you update the instructions.

**Comment by JimDaly** [comment]
Closing since workitem 3013846 exists to update this topic.
