### ISSUE TITLE
Patch request v. 9.2

### ISSUE THREAD

**Issue by kkaarel** [MicrosoftDocs/powerapps-docs#3792]
[Enter feedback here]

Trying to use patch with http and update data in dataverse, but get an error that Patch is not allowed 

{"error":{"code":"","message":"The requested resource does not support http method 'PATCH'."}}

The documentation is for version 9.0, but we have 9.2

With post the request works but not with PATCH

script

`import http.client
import json

conn = http.client.HTTPSConnection("<env>.crm4.dynamics.com")
payload = json.dumps({
  "name": "myname"
})
headers = {
  'Authorization': 'Bearer' +token 
}
conn.request("PATCH", "/api/data/v9.2/<tabel>?If-None-Match=null&OData-MaxVersion=4.0&OData-Version=4.0&Content-Type=application/json&If-Match=*&MSCRM.SuppressDuplicateDetection=false&Accept=application/json", payload, headers)
res = conn.getresponse()
data = res.read()
print(data.decode("utf-8"))`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c2ec5c1c-86a3-95bc-57bd-56ce7cc5378e
* Version Independent ID: 75f47983-64d4-4646-7d4e-5a46944cfbe7
* Content: [Perform conditional operations using the Web API (Microsoft Dataverse) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/webapi/perform-conditional-operations-using-web-api)
* Content Source: [powerapps-docs/developer/data-platform/webapi/perform-conditional-operations-using-web-api.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/webapi/perform-conditional-operations-using-web-api.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @divka78
* Microsoft Alias: **dikamath**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @kkaarel. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@kkaarel 
The code you have posted isn't in any library I know of. It isn't .NET using HttpClient or JavaScript XmlHttpRequest or Fetch.
What is this?

`conn.request("PATCH", "/api/data/v9.2/?If-None-Match=null&OData-MaxVersion=4.0&OData-Version=4.0&Content-Type=application/json&If-Match=*&MSCRM.SuppressDuplicateDetection=false&Accept=application/json", payload, headers)`

My guess is that it is a custom wrapper around one of the above.

Just looking at this code, there are issues.
1. No resource identified
2. Requests headers being passed as query strings.

These represent significant misunderstanding of basic concepts. I recommend starting with this topic: [Compose HTTP requests and handle errors](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/webapi/compose-http-requests-handle-errors). Also recommend you try things out using Postman. See [Set up a Postman environment](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/webapi/setup-postman-environment) rather than use a wrapper unless you wrote the wrapper and understand what it does.

Action item for documentation: Update the version in the URL. 
v9.0 or v9.2 doesn't really make any difference at this point, but it should be updated.
