### ISSUE TITLE
In app notification with other features

### ISSUE THREAD

**Issue by BillyCottrell** [MicrosoftDocs/powerapps-docs#3802]
Hi,

So I am currently building a power automate flow and was wondering if it is possible to create model driven in-app notification that holds approvals or adaptive cards. Just to make things clear, I don't mean making an approval/adaptive card and add a reference to it in the in-app notification, but rather have an approval/adaptive card inside the notification itself. Also, when an in-app notification is created is it possible for flow to wait until an action was used in the notification, just like with approvals and adaptive cards.

I am asking this because I want this to appear only in the model driven app itself and not as an email or teams message, but also because I want power automate to continue the flow when an action like approval or rejection occurred or to send reminders when receiving no response.

Thanks in advance!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f495f03e-28c9-0ebb-ef03-72e16b267b3a
* Version Independent ID: a9dcec59-8b72-966e-fa53-f4b2e42d325e
* Content: [Send in-app notifications within model-driven apps - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/send-in-app-notifications?tabs=clientapi)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/send-in-app-notifications.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/model-driven-apps/clientapi/send-in-app-notifications.md)
* Service: **powerapps**
* Sub-service: **mda-developer**
* GitHub Login: @adrianorth
* Microsoft Alias: **aorth**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @BillyCottrell. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@BillyCottrell 
The scope of issues for this Github repository is feedback on the documentation.

The topic [Send in-app notifications within model-driven apps](https://learn.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/send-in-app-notifications?tabs=sdk) describes how to programmatically send in-app notifications. The scope of this topic is pretty specific.

You say:

> I don't mean making an approval/adaptive card and add a reference to it in the in-app notification, but rather have an approval/adaptive card inside the notification itself.

In app notifications allow you to provide content in the body. But it seems like you are asking for a different capability have an experience that includes the actual card in the body. So, I have to call this a feature request rather than documentation feedback.

If you have a feature request, you can post it here: [Power Apps Ideas](https://powerusers.microsoft.com/t5/Power-Apps-Ideas/idb-p/PowerAppsIdeas)

If you are looking for other solutions, your question might be better directed to [Power Apps Community](https://powerusers.microsoft.com/t5/Power-Apps-Community/ct-p/PowerApps1)


Unless @adrianorth  or @caburk  have some thoughts do add, I'm going to close this.

**Comment by BillyCottrell** [comment]
@JimDaly well I didn't intend as a feature request, but instead I was just inquiring what the limits are of in-app notifications and whether it is possible to simulate something similar to adaptive cards or approvals to the point that it's possible to be used in flow the same way approvals are used.

**Comment by JimDaly** [comment]
@BillyCottrell 
Thanks, but please advise how the documentation could be changed to address your question.

The feature involves creating records where you can set an icon or use markdown in the body to customize the appearance and content. Several examples are provided.

I think this is pretty subjective:

> ...it is possible to simulate something similar to adaptive cards or approvals to the point that it's possible to be used in flow the same way approvals are used.

What are the properties of adaptive cards or approvals that you want to simulate?
Can you create them using Markdown?

I expect an approval must include an action. Can that action be composed as a link?

It sounds like an interesting thing to investigate, but out of scope for this topic.

**Comment by BillyCottrell** [comment]
@JimDaly well, mainly whether it is possible to simulate the same response behaviour that approvals have in flows.
Since you have actions in the in-app notification, I thought it would be possible to listen to which action was used on that notification the same way flow listens to the response of the approval request.

I guess to give an example, it would be something like:

You are trying to do something which triggers a flow, but the flow notices that something went wrong or whatever, and it sends a notification to the triggering user with info about the issue. So the user has a few options, either you "cancel" the flow, or you "cancel and undo" the changes that triggered the flow in the first place, so you can go and check it yourself, or you can do "sent to support" to escalate the issue. Based on the selected action the flow continues so that when it's "cancel" it just terminates the flow with the status cancelled, when it's "cancel and undo" it updates the record to a previous state, in case you want to send it to support it will gather all the information and sent it to the support team for further investigation (so it can add like the workflow info of the run itself).

So I'm not really requesting for like forms to be added to the notification, I mean after all it remains a notification that's supposed to inform people and nothing else. I just think that being able to take action on it directly can make it easier to follow up and notify other users when issues arise.

**Comment by JimDaly** [comment]
@BillyCottrell 
App notifications allow you to compose a notification experience with links. When the user clicks the link, it sends a GET request to the URL of the link. There appears to be no capability to send requests using POST, PATCH or any other Http method.

You say:

>  I thought it would be possible to listen to which action was used on that notification the same way flow listens to the response of the approval request.

It may be possible, but it isn't part of this feature. Imagine that you have a web service that processes GET requests and in-turn performs some action. You should be able to have that web service treat that as an event to initiate some process, but the in-app notification is just a method to deliver that link to the user.

The author of this topic made no mention of adaptive cards, and I think that means that there is no connection intended between them. The scope of this feature appears to be limited to sending in-app notifications.

You have flexibility in what kind of link you add. What happens when users click that link is up to you, and not part of the capability that this feature provides. 

Does this make sense?

**Comment by BillyCottrell** [comment]
@JimDaly
In that case, I understand that adaptive cards or approval like capabilities are not meant to be part of the in-app notification experience and that the notifications are only about delivering a message and not allowing users to directly update or interact with other features but rather sending a reference to that feature or process.

Thank you for clarifying this!
