### ISSUE TITLE
performance penalty in using Upsert versus using Create. 

### ISSUE THREAD

**Issue by xtofs** [MicrosoftDocs/powerapps-docs#3810]
the phrase "There is a performance penalty in using Upsert versus using Create. If you are sure the record doesn't exist, use Create." is misleading because for client code to know that a resource exist, it need to send a GET request first. Therefore the fair comparison should be between a GET+POST for insert vs a POST for update. That comparison will most likely show that the single POST is cheaper in the total.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8ed55813-1248-7edf-c33c-ce7a4783f9e6
* Version Independent ID: 32bc8340-84c9-8114-673f-481b3b09470f
* Content: [Use Upsert to Create or Update a record (Microsoft Dataverse) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/use-upsert-insert-update-record?tabs=webapi)
* Content Source: [powerapps-docs/developer/data-platform/use-upsert-insert-update-record.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/use-upsert-insert-update-record.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @divka78
* Microsoft Alias: **dikamath**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @xtofs. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@xtofs 
Thanks for your feedback.
The fact remains that there is a performance penalty in using Upsert versus using Create.
You say that it is misleading and that the perf impact is the same suggests that the only way to test that the record exists is to test each one individually with a GET.  The results could be achieved with a single query that returns multiple records.

I think the statement stands: _If you are sure that the record doesn't exist, use Create._

We want people to think about this and not simply use Upsert behaviors always.

**Comment by xtofs** [comment]
The sentiment to encourage users of the API to think about it is great. Fully support that .

But I stand by the statement that the way is depicted is not fair comparison. You are not considering the cost (both on client and service side) how the client can know that  _the record doesn't exist_  if you leave that out in the comparison you are not considering half the work that an Upsert has to do.

**Comment by JimDaly** [comment]
OK. 

The whole point of providing Upsert is exactly as you say. This is highlighted here [Data Synchronization > Upsert](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/data-synchronization#upsert). It isn't like we don't want people to use it. But if they **know** they are creating a new record (_without getting into how they know_) then they should use Create rather than Upsert. This is still true.

You say it is misleading, but what direction does it lead people towards? It leads them to think about it rather than simply using  PATCH for everything and incurring that additional processing when not needed. This is what we want to avoid.

What change to the docs do you think we should make to achieve this?
