### ISSUE TITLE
Have a way to get Schema Name of a field

### ISSUE THREAD

**Issue by DiogoAlex** [MicrosoftDocs/powerapps-docs#3814]
To use the Odata.bind we need to use the schema name of the field. I'm trying to clone a record and create it with some children records and I can't get this to work because of the schema name of some lookups.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 75f70840-ac77-de34-b797-233a4ff56d37
* Version Independent ID: e6b3d742-fe79-7442-0cae-d5dcba71f55f
* Content: [createRecord (Client API reference) in model-driven apps - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/reference/xrm-webapi/createrecord)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-WebApi/createRecord.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-WebApi/createRecord.md)
* Service: **powerapps**
* Sub-service: **mda-developer**
* GitHub Login: @adrianorth
* Microsoft Alias: **aorth**

**Comment by JimDaly** [comment]
@DiogoAlex 
Thank you for your feedback.

The first thing to address is that you don't want the `SchemaName` of the field. You want the name of the _single-valued navigation property_, not the schema name of anything. This isn't stored anywhere in the metadata for the field/property/attribute, this is in the metadata of the relationship that supports the lookup. 

Keep in mind that some lookup fields can support multiple entity types. Like customer lookup might point to either account or contact, or a polymorphic lookup can point to any number of other entity types.

For example, if you are working with the `incident` entity and want to find the name of the single-valued navigation property to  use @odata.bind to set an `account` record using the `customerid` lookup, you can retrieve that using this query:

```
GET /RelationshipDefinitions/Microsoft.Dynamics.CRM.OneToManyRelationshipMetadata?$filter=ReferencingEntity eq 'incident' and ReferencedEntity eq 'account' and ReferencingAttribute eq 'customerid'&$select=ReferencingEntityNavigationPropertyName
```

It will return this JSON, and the value `customerid_account` is the value you should use.
```
{
    "@odata.context": "[Organization URI]/api/data/v9.2/$metadata#RelationshipDefinitions(ReferencingEntityNavigationPropertyName)",
    "value": [
        {
            "ReferencingEntityNavigationPropertyName": "customerid_account",
            "MetadataId": "4b5945b8-a4a6-4613-afc1-ae1d5e6828c7"
        }
    ]
}
```

This corresponds to the CSDL of the navigation property as described here [Single-valued navigation properties](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/webapi/web-api-navigation-properties#single-valued-navigation-properties)
```
                <NavigationProperty Name="customerid_account" Type="mscrm.account" Nullable="false" Partner="incident_customer_accounts">
                    <ReferentialConstraint Property="_customerid_value" ReferencedProperty="accountid" />
                </NavigationProperty>
```
But I think the question remains: How to perform the query to RelationshipDefinition AND include the cast to `/Microsoft.Dynamics.CRM.OneToManyRelationshipMetadata` so that you can get the properties you need.

The [Xrm.WebApi.retrieveRecord](https://learn.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/reference/xrm-webapi/retrieverecord) and [Xrm.WebApi.retrieveMultipleRecords](https://learn.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/reference/xrm-webapi/retrievemultiplerecords) seem optimized for business data records and not metadata. But I think you can still compose your own [XmlHttpRequest](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest) or [fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch) to retrieve this data. We have Web API Sample code for client-side JavaScript [here ](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/webapi/web-api-samples-client-side-javascript)

@DiogoAlex Does this unblock you in getting the information you need?

@adrianorth It may be valuable to offer some helper methods to retrieve metadata, or provide an example in this topic about how people should get the name of the single-valued navigation property they need.

**Comment by JimDaly** [comment]
@DiogoAlex 
I haven't heard back from you so I don't know if the information I provided would help others, or if there is a different issue.
This topic is about using the Xrm.WebApi functions and they depend on some knowledge of Web API. Not sure that we need to invest in adding to this page to address questions about Web API that are available elsewhere. Closing this.
