### ISSUE TITLE
What happens during paging of RetrieveEntityChangesResponse results?

### ISSUE THREAD

**Issue by DigitalFlow** [MicrosoftDocs/powerapps-docs#3862]
Hi everyone,

the documentation points out:

> If the new or updated item collection is greater than 5000, the user can page through the collection

This is true.
However we were wondering whether you could precise how paging affects dataToken handling.

As we found out, the RetrieveEntityChangesResponse will not contain a `EntityChanges.DataToken` on the initial load (i.e. the DataToken in the initial request is null or empty), if `EntityChanges.MoreRecords` is `false`.
It will only return the DataToken on the last page of the initial load.

Now for big tables the initial load can take several hours to complete.
And on the last page we will receive a dataToken with a timestamp of the last page.

But what happens now to the records that were created or updated during the initial load?
To us it seems these records are lost to us, since the next time after initial load that we query data, our data token will be set to the timestamp from the last page, so we don't receive the changes in between.

Can you specify how to handle this condition?

Kind regards,
Florian

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ae183946-fb2a-1b2f-e199-273eb9a68d54
* Version Independent ID: 0cf78a90-f63b-af43-8075-c1cd4e934e7d
* Content: [Use change tracking to synchronize data with external systems (Microsoft Dataverse) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/use-change-tracking-synchronize-data-external-systems)
* Content Source: [powerapps-docs/developer/data-platform/use-change-tracking-synchronize-data-external-systems.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/use-change-tracking-synchronize-data-external-systems.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @Peakerbl
* Microsoft Alias: **peakerbl**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @DigitalFlow. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@DigitalFlow 
I'm not totally clear about your question. I'll try to paraphrase.

This is what I understand, please correct me if I'm wrong.

You use RetrieveEntityChanges to extract data from Dataverse to load into another system. There are many records and this requires significant time (hours) and multiple pages.  After the last page, when there are no more records, you get a DataToken value that you can then use for subsequent use of RetrieveEntityChanges to keep the data in the two system synchronized.

But, during the hours that the initial extraction of data was taking place, additional data was added to Dataverse. So you are asking: 

> But what happens now to the records that were created or updated during the initial load?

I think the fastest way to answer this would be to query Dataverse for records created or modified during that period and then see if they exist in the external system. 

Also, once you get the token after the initial data load, immediately use RetrieveEntityChanges and see if the results include the changes that occurred during those hours since the initial RetrieveEntityChanges request are returned.

From a documentation side, I think you are saying it would be good to document what people should expect rather than have to perform these tests to find out.

Let me know if I've correctly paraphrased the situation and how documentation on this would help.

**Comment by DigitalFlow** [comment]
Hi @JimDaly,

you understood everything correctly, thanks for that :)

Yeah, some words on what to expect would be really helpful.
Everything is stated roughly in the documentation, but in these use cases you need to know everything in detail to make sure all the data is transferred correctly.

I had a thorough look on the logic involved and things cleared up a little.
I had a workaround in place in our code, where I saved the dataVersion retrieved from the first page and set this as next dataVersion for the next run instead of the last page of the paging calls.

As it turns out, this lead to the dataVersion never updating really.
I did not have an idea what the `DataVersion` really means, I guess it's not stated anywhere.

The `DataVersion` looks something like `265161759!12/01/2022 14:00:00`.

As we found out, it's really the data version number and the datetime from when the results where gathered separated by an exclamation mark, like `{VersionNumber}!{DataTimeStamp}`.
With our workaround where we saved the first page's DataVersion instead of the last page's one, we noticed that only the DataTimeStamp part of the DataVersion was increased, the version number part got stuck at the same value.

This would point me to think that the issue with long delta loads might not even be a problem, because the rowversion stays the same until the last page.
I guess a clarification on this behavior would be really helpful for others wondering about this.

In addition to that, now I wonder what the timestamp is used for. Right now when we page me make sure to always send the intital dataVersion, just with a different PagingInfo.
As the dataVersion seems to stay the same across all pages until the last, we questioned whether we should always send the same initial dataVersion while paging, or always send the last one we received, which contains the same versionNumber, but a later timestamp.

If you could clear things a little up, that would be awesome :)

Kind regards,
Florian

**Comment by JimDaly** [comment]
@Florian -

I see you looked at the value of the [RetrieveEntityChangesRequest.DataVersion Property](https://learn.microsoft.com/en-us/dotnet/api/microsoft.xrm.sdk.messages.retrieveentitychangesrequest.dataversion?view=dataverse-sdk-latest). We don't discuss the contents of this string value in the topic because it is supposed to be irrelevant. People shouldn't be concerned about the contents of this string because it is an implementation detail. As you found, it does contain the version and timestamp information. But we don't expect people to examine it or try to construct their own version of it. They should just use it as described and everything should 'just work'.

Introducing additional words that explain implementation details generally confuses more people because it suggests that it is important to understand, and that people should manipulate this data. But the design is intended to keep things simple.

Seems like things are working for you now. Is this correct?
If so, is there a way to update the documentation to capture what you have learned?

You say:

> This would point me to think that the issue with long delta loads might not even be a problem, because the rowversion stays the same until the last page.
> I guess a clarification on this behavior would be really helpful for others wondering about this.

I'm not convinced that we should introduce a discussion of a hypothetical problem. We don't know how many other people are wondering about this. But if we add a discussion about it to the documentation, then we can expect more people to wonder about it. If we had some evidence that this is a common concern, such as questions posted to community forums, then we could consider this.

Does this make sense?

**Comment by JimDaly** [comment]
@DigitalFlow 
Florian -
I haven't heard back from you on this, so closing for now.
