### ISSUE TITLE
Missing or incomplete information

### ISSUE THREAD

**Issue by kev1961** [MicrosoftDocs/powerapps-docs#3969]
[Enter feedback here]
Thanks for the information. However, a lot of not all these pages lack some critical information in order to it. First, you use window.sdk however, there is no mention where to get and install this library or framework. At a minimum, there should be a link to the page that describes where and how to install. Second, there is no mention that you need to authenticate before using the API in question. There should a link or a section describing how to authenticate using user/password, and by SPN (in other words by using a security token) which I assume is required.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c3ae32fb-348c-fe39-fc4a-6a4b0680a199
* Version Independent ID: 9c1c528a-ff1e-d02c-5603-3071176ee85b
* Content: [Web API Query Data Sample (Client-side JavaScript) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/webapi/samples/query-data-client-side-javascript)
* Content Source: [powerapps-docs/developer/data-platform/webapi/samples/query-data-client-side-javascript.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/webapi/samples/query-data-client-side-javascript.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @divkamath
* Microsoft Alias: **dikamath**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @kev1961. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@kev1961 
Thanks for your feedback.

From your feedback it seems you are looking for JavaScript samples for a client application. 

These samples are actually for client-side scripts using model driven apps. In that scenario, the libraries are loaded using Web Resources and authentication is handled by the application. Window.Sdk is just a namespace for the sample library included in the code.

But I can see how, without the context we have assumed, someone could expect a different use case.
We should update the docs to make this clear.

I'd love to hear what kind of JavaScript app you want to build using Dataverse.

**Comment by JimDaly** [comment]
@kev1961 

Sounds like you are seeking a work-around due to issues you have experienced with tooling.
Generally, the tools use the same public APIs we document, so unless there is an issue with the tool itself (the newtonsoft error seems like that) then I don't think building a new app from scratch is going to necessarily move you forward.

The Model-driven app you exported should be in the form of a solution, so you should just need to import the solution.

Exporting the contents of one Dataverse DB to another including all the parts of a Model-driven app doesn't sound like a good idea to me. There is a reason why the solution export/import infrastructure exists. I don't think it is realistic for one person to replicate it. It is very complex.

Have you contacted MS support? I think that is your best path forward.

Since there isn't any actionable items for the documentation for this article, I'm going to close this issue.

**Comment by kev1961** [comment]
Thanks Jim. I will reach out to Msft through my agency
