### ISSUE TITLE
CLI command to be executed doesn't behave as the steps in the docs say 

### ISSUE THREAD

**Issue by bambooch** [MicrosoftDocs/powerapps-docs#3977]
On step 4. it says _The above command will also run `npm install`..._ but the command doesn't have the `--run-npm-install` flag passed into it. Either the command should be modified accordingly or the reader should be instructed to run `npm install` in step 4.

Screenshot below:
![image](https://user-images.githubusercontent.com/22875244/214439607-9e073038-dad6-4828-b125-63b492749343.png)
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5e4b9e58-d9d3-c387-fe6a-258ebe78516d
* Version Independent ID: 22d89b45-e427-1ab9-b456-7d7750585b52
* Content: [Create and build a code component in Microsoft Dataverse - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/component-framework/create-custom-controls-using-pcf)
* Content Source: [powerapps-docs/developer/component-framework/create-custom-controls-using-pcf.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/component-framework/create-custom-controls-using-pcf.md)
* Service: **powerapps**
* Sub-service: **pcf**
* GitHub Login: @noazarur-microsoft
* Microsoft Alias: **noazarur**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @bambooch. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@bambooch 
Thank you for your feedback.

I also noticed that the guidance provided related to using the developer command prompt for Visual Studio was out of date.

We recommend using PAC CLI with Visual Studio Code and the command prompt rather than downloading and installing the .MSI which will only work for Windows.

So I have updated the instructions for that. And the PAC CLI example now includes the `--run-npm-install` parameter so that npm will run automatically.
