### ISSUE TITLE
upload file into file column is not working using power portal web api

### ISSUE THREAD

**Issue by jonathanhotono** [MicrosoftDocs/powerapps-docs#4080]
It seems that this docs sample is not working for power portal web api.
Upload a file in a single request using Web API is not working on power portal web api and keep returning errors.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 823f06cb-d5e9-6dbb-1bda-460e1e0e84fa
* Version Independent ID: 823f06cb-d5e9-6dbb-1bda-460e1e0e84fa
* Content: [Use file column data (Microsoft Dataverse) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/file-column-data?tabs=webapi#upload-a-file-in-a-single-request-using-web-api)
* Content Source: [powerapps-docs/developer/data-platform/file-column-data.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/file-column-data.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @NHelgren
* Microsoft Alias: **nhelgren**

**Comment by JimDaly** [comment]
@jonathanhotono 

According to the Power Pages Web API documentation

[Portals Web API overview : Web API operations](https://learn.microsoft.com/en-us/power-apps/maker/portals/web-api-overview#web-api-operations)

> The portals Web API offers a subset of capabilities for Dataverse operations that you can do by using the Dataverse API. We've kept the API format as similar as possible to reduce the learning curve.

Noted that you are looking to use the style that doesn't use actions, which are not supported by Power Pages Web API. You are seeking to upload with a single request as described in [Upload a file in a single request using Web API](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/file-column-data?tabs=webapi#upload-a-file-in-a-single-request-using-web-api)

There is nothing actionable about this topic since it isn't about the Power Pages Web API.  You may want to leave feedback in the topics about Portals Web API.

I will alert the Power Pages team of this feedback item.
