### ISSUE TITLE
Missing/Wrong Information

### ISSUE THREAD

**Issue by LauWagFelix** [MicrosoftDocs/powerapps-docs#4154]
I can't find the mentioned API Right "Mobile Application Management"
And there is no Command shown how to add (like the other 2 shown; as example "Azure API Connections")

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 66f1562e-3a0f-1be1-3e3a-98b6dd24e768
* Version Independent ID: 66f1562e-3a0f-1be1-3e3a-98b6dd24e768
* Content: [Customize and build your mobile app - Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/common/wrap/how-to)
* Content Source: [powerapps-docs/maker/common/wrap/how-to.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/common/wrap/how-to.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @makolomi
* Microsoft Alias: **mkaur**

**Comment by makolomi** [comment]
Updated API to its full name" "Microsoft Mobile Application Management" instead it's partial name how it was in the doc to address issue #4154. 
- this API only comes up in search under its full name and won't show up under the partial name, so the customer could not find it (reproduced)
fixed in this pr: https://github.com/MicrosoftDocs/powerapps-docs-pr/pull/7840

**Comment by mduelae** [comment]
@LauWagFelix The topic has been updated.

Thank you.
