### ISSUE TITLE
Power Apps Grid Control: SetFilterXml not working

### ISSUE THREAD

**Issue by VictorSijtsma** [MicrosoftDocs/powerapps-docs#4396]
On the new Power Apps Grid Control, the javascript function SetFilterXml is not being applied.
It does work on the "old" editable subgrid control, which offers almost the same functionality

**Comment by prikrylm** [comment]
Have similar problem on subgrid. setFilterXml works (approx 2 months ago), but now after filter is applied subgrid list correct rows and immediately reloads with no filter and list all table rows.

**Comment by prikrylm** [comment]
Supported methods seems do not allow me to set custom filter on subgrid. Is there some  way to do it? For example records related to lookup on the record not on the record itself?

**Comment by VictorSijtsma** [comment]
@darshSWL Then there is no supported way to filter a subgrid based on a field on the form of the parent record. Or am i missing something?

**Comment by prikrylm** [comment]
Yes, there is supported way. 
- add lookup to the form on the place where you want subgrid
- set Form Component control on the lookup Components settings
- select form with related subgrid on Form Component Control

**Comment by VictorSijtsma** [comment]
Yeah, kind of a detour but it works, but only for a lookup. Any other kind of field won't, saddly :(

**Comment by darshSWL** [comment]
That's what we are also doing. 
Maybe a custom PCF control like https://pcf.gallery/fetchxml-detailslist/ would also work.

There is also a link in the already mentioned issue to the ideas page to vote for this feature: https://experience.dynamics.com/ideas/idea/?ideaid=85716c9d-fe01-ea11-b862-0003ff68ba22

**Comment by JimDaly** [comment]
@VictorSijtsma, @darshSWL , and @prikrylm 

Apologies for being late to respond. // Build had everyone very busy for the past few weeks.
Also, these documentation feedback items will send us a notification only if they are created using the button of each article.

We can't provide technical support here, and this isn't the forum for submitting ideas.
But I would love to hear what we can do to improve the documentation to address this issue.

**Comment by darshSWL** [comment]
@JimDaly

I'm not sure how to actually improve the documentation. Perhaps a note regarding setFetchXml that explicitly marks this method as unsupported would be helpful. Since there is getFetchXml, it stands to reason that there is also setFetchXml. Also, there are posts all over forums and blogs about how to supposedly use setFetchXml. Maybe it could also be possible to include prikrylm's tip about the Form Component control in that note?

Of course, there is the principle that undocumented functions are unsupported. However, this principle is not obvious. There are many other software or API documentations that are outdated or incomplete and therefore you have to rely on forums and blogs.
An example would be that the documentation for Elastic Tables (which marked as in preview) was not yet available, even though the feature was already released. By the way, I didn't know that there is a section for "maker" and one for "developer" in the documentation. This tore apart the documentation for Elastic Tables (at least for me) and as a result, information that should have been available was missing. This also contributes to people wanting to believe the forums and blogs without looking further into the documentation. "I'm sure it's in the documentation somewhere".

Hope this helps.

**Comment by JimDaly** [comment]
@darshSWL 
Thanks for taking the time to share your thoughts on this.

I've looped in @jasongre and the dev team to ask them to take another look at the gridContext.SetFilterXml method.

While our supported APIs exist alongside unsupported APIs, we are going to have challenges guiding customers to differentiate between them.  This is especially true for client-side APIs because there isn't a way to flag them as private.

The documentation for elastic tables is a different matter, I think. The timing of publishing the documentation was tied mostly to the announcement at the //build conference than the appearance of the option in the UI.

We separate content for developers because:
- People who are not developers ('makers') don't want or need to see this content. It is more complex.
- The experience for developers isn't driven by the UI experiences as the maker content is.

Elastic tables are a good example of this. These are the articles for elastic tables:

For all: https://learn.microsoft.com/power-apps/maker/data-platform/create-edit-elastic-tables

For developers:
https://learn.microsoft.com/power-apps/developer/data-platform/elastic-tables
https://learn.microsoft.com/power-apps/developer/data-platform/create-elastic-tables
https://learn.microsoft.com/power-apps/developer/data-platform/use-elastic-tables
https://learn.microsoft.com/power-apps/developer/data-platform/query-json-columns-elastic-tables
https://learn.microsoft.com/power-apps/developer/data-platform/bulk-operations-elastic-tables
https://learn.microsoft.com/power-apps/developer/data-platform/elastic-table-samples

For the elastic tables content, we were a little late (by a couple of days) in adding the links between the maker and 'Developer Guide' topics. They are there now. Is this the part you found was missing?

**Comment by JimDaly** [comment]
I haven't gotten any response from the dev team to clarify this. Closing for now.
