### ISSUE TITLE
Confusing documentation flow

### ISSUE THREAD

**Issue by ken-afh** [MicrosoftDocs/powerapps-docs#4425]
The organizational structure of this entire document set is highly confusing. The navigation in the left panel does not follow the flow of the content in the right panel. When reading the documentation, should I navigate from topic to topic using the left navigation menu or follow the contextual "See Also" links? No "Next" navigation hint leads me to the next natural content section.

The topic is complex enough without struggling to understand the documentation flow. **Do better, Microsoft.**

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f84ec2a3-cf72-9d3e-c1b1-ff685678dcf3
* Version Independent ID: febc9930-68c7-f668-49a7-bf34962418cb
* Content: [Client-side JavaScript using Web API in model-driven apps - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/webapi/get-started-web-api-client-side-javascript)
* Content Source: [powerapps-docs/developer/data-platform/webapi/get-started-web-api-client-side-javascript.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/webapi/get-started-web-api-client-side-javascript.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @divkamath
* Microsoft Alias: **dikamath**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @ken-afh. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@ken-afh 
Thanks for your feedback.

Just want to make sure that I'm understanding the feedback correctly.
Looking at the page:
![image](https://github.com/MicrosoftDocs/powerapps-docs/assets/6353736/18e0205f-9449-4241-a85f-9e8a38f3ca44)

The left side is the **table of contents**.

What you are seeing on the right side is something new.
This is a dynamically generated list of **Additional Resources**.
Until last week, this appeared at the bottom of the topic, so it is much more visible now.

Sounds like you are overwhelmed by the number of options available.

This area of content is primarily about how to use the Dataverse Web API, without regard for a specific client. If you want to learn about the Dataverse Web API, you should start at the top ([Use the Microsoft Dataverse Web API](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/webapi/overview)) and work down. It starts general and becomes more specific. Near the bottom, there are several items that don't necessarily follow any linear path, they are kind of "*BTW, you should also know*" details.

The purpose of this [Client-side JavaScript using Web API in model-driven apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/webapi/get-started-web-api-client-side-javascript) article is to call out that model-driven apps have their own helper [Xrm.WebApi](https://learn.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/reference/xrm-webapi) that provides methods to interact with data using Web API.

The dynamically generated content in this case is mostly taking you to some client-side JavaScript samples that don't use  [Xrm.WebApi](https://learn.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/reference/xrm-webapi), so that probably isn't what you want.

It would be helpful to know what you are trying to do.

- Are you trying to learn all about Dataverse Web API?
- Are you only interested in how to use Web API from Model-driven apps?
- Something else?

**Comment by ken-afh** [comment]
Hey, Jim,

Thanks for investigating! First, to clarify, I have no issue with the content of the article. My issue is with the way the documentation site is structured. Wherever I start, I wind up with the same dilemma – where should I go next? This is particularly frustrating when reading on mobile, where the left-hand table of contents column simply doesn’t exist. I get to the bottom of an article & there’s “See Also,” “Feedback,” and “Additional resources” – no way to get to the next article in the series. A simple “Next” link at the bottom of the article would go a long way toward clarifying a preferred path for consuming the documentation.

To answer your questions:

Sounds like you are overwhelmed by the number of options available.

[KLC] Yes. There are too many options and not a clear preferred path!

This area of content is primarily about how to use the Dataverse Web API without regard for a specific client. If you want to learn about the Dataverse Web API, you should start at the top (Use the Microsoft Dataverse Web API<https://learn.microsoft.com/en-us/power-apps/developer/data-platform/webapi/overview>) and work down.

[KLC] Yes – but I’m missing a simple “Next” button at the bottom to move to the next section. Instead, I get “See Also” or “Additional resources”

It starts general and becomes more specific.

Near the bottom, there are several items that don't necessarily follow any linear path, they are kind of "BTW, you should also know" details.

[KLC] I think this is where I find myself the most confused. Sometimes, there’s “See Also” and sometimes “Additional resources” (I’m not sure what the breakpoint is to render Additional resources in a third column, it’s wider than I have my browser window.) Again, I’m missing a simple “Next” link that would allow me to easily continue with a linear reading path.

The purpose of this Client-side JavaScript using Web API in model-driven apps<https://learn.microsoft.com/en-us/power-apps/developer/data-platform/webapi/get-started-web-api-client-side-javascript> article is to call out that model-driven apps have their own helper Xrm.WebApi<https://learn.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/reference/xrm-webapi> that provides methods to interact with data using Web API.

[KLC] My feedback is not for just this one article. It’s for the entire documentation compendium. Wherever I start, I wind up with the same dilemma – where should I go next? This is particularly frustrating when reading on mobile where the left-hand navigation column simply doesn’t exist. I get to the bottom of an article & there’s “See Also”, “Feedback”, and “Additional resources” – no way to get to the next article in the series.

The dynamically generated content in this case is mostly taking you to some client-side JavaScript samples that don't use Xrm.WebApi<https://learn.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/reference/xrm-webapi>, so that probably isn't what you want.

It would be helpful to know what you are trying to do.

  *   Are you trying to learn all about Dataverse Web API?
  *   Are you only interested in how to use Web API from Model-driven apps?
  *   Something else?
[KLC] My eventual goal is to understand the core Dataverse structure and usage, eventually getting to the point of creating model-driven apps. Before I can start creating apps of any kind, I need to understand (at a basic level) what the Dataverse is and how to use it. Knowing how to talk to it does me no good if I don’t know what to say.

Thanks,
KLC

**Comment by JimDaly** [comment]
Thanks again Ken.
Feedback like this is very valuable.

I hear what you are saying about wanting more guidance about what to do next. Unfortunately, this is product documentation rather than a course. It is going to be pretty feature focused rather than task focused, and Dataverse has a lot of features.

The learning courseware is more focused on guiding people through a set of paths with more structure on commonly performed tasks. I would recommend looking here if you haven't already [Learning catalog for Power Apps](https://learn.microsoft.com/en-us/power-apps/learning-catalog/learning-catalog), especially if you are just getting started.

Product documentation is a bit more like Wikipedia. We organize the content more around features and go much deeper. Content is optimized for search engines since most people come to our content from searches. We don't necessarily expect people to read the whole thing, but let them 'write their own adventure' so to speak. So, the design provides lots of links for people to choose from. Perhaps too many.

I am glad to accept your feedback and agree we can do better to establish clearer paths in the product documentation like the courseware does.

One example of this is the content about [Web API types and operations](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/webapi/web-api-types-operations). There is a series of 8 articles that walk you through some pretty dry content related to reading XML service documents. But it is important, so we try to make it easier to consume by keeping the articles short(er) and establishing that there is more to learn at the end of each one.

My take-away is that you want more content like that. Please let me know if that isn't a good example.

**Comment by ken-afh** [comment]
Hi, Jim,

Thank you for taking the time to have this dialog. I greatly appreciate it!

Yes, the example you provided (Web API types and operations) provides a much better (to me) user experience. I do understand what you’re saying about the product documentation being focused on reference rather than serial consumption. Perhaps, rather than providing breadcrumbs to lead the way through the documentation set, have the product documentation include a pathway to the educational material? I did find the content via a search. Maybe giving me a gentle nudge saying “Hey, you! If you’re looking for educational material on this topic, look over here.”

Thanks again for your time! You’ve given me confidence that my feedback will receive due consideration & may lead to improvements!

KLC

**Comment by JimDaly** [comment]
@ken-afh 

Thank you Ken.
Appreciate your feedback.
Closing this.
