### ISSUE TITLE
Next set of updates required

### ISSUE THREAD

**Issue by kyleatversion1** [MicrosoftDocs/powerapps-docs#4441]
[Enter feedback here]

Can the next set of articles for this be scheduled please?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: af6c10f2-9207-25f6-1a32-a50c82698c3b
* Version Independent ID: 5a29feb2-950c-f914-cb86-e38a70033b45
* Content: [Developers: Best practices and guidance for model-driven apps - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/model-driven-apps/best-practices/)
* Content Source: [powerapps-docs/developer/model-driven-apps/best-practices/index.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/model-driven-apps/best-practices/index.md)
* Service: **powerapps**
* Sub-service: **mda-developer**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @kyleatversion1. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@kyleatversion1 

Thanks for your feedback.

This introductory article sets expectations for more content in this area, but there is nothing currently planned to be added. Agree this is misleading. This was prepared so that different teams would have a place to include their best practice recommendations.

Client scripting is the only place where developers write code. Since this is within the developer area of the docs, I don't think that there is likely to be any more best practices here in terms of the following areas mentioned in this article:

- Model-driven app design
- Form design
- Web resources

I will create a workitem to re-write this article so it doesn't incorrectly set the expectation that there is more content coming in this area.

If you have some ideas about best practice guidance that could be covered in this space, I would be glad to hear your thoughts.
