### ISSUE TITLE
Clarification on moving data and deactivation

### ISSUE THREAD

**Issue by surfarri** [MicrosoftDocs/powerapps-docs#4483]
Can you explain in detail what this means: _Merging will move any data from the Subordinate record to the Target and then deactivate the Subordinate record_

1) It will move "any" data, meaning any blank fields on the Target?  How does it know what to move (from the Subordinate) and what to leave (on the Target)?
2) It just moves to "Inactive"?  Can the merge API control what the Status Reason in the same POST?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3210eb69-a264-5bcd-74d1-d2cefb9aac4d
* Version Independent ID: 76696c85-0363-6b45-4fb6-e95d03c458c3
* Content: [Merge table rows using the Web API (Microsoft Dataverse) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/webapi/merge-entity-using-web-api)
* Content Source: [powerapps-docs/developer/data-platform/webapi/merge-entity-using-web-api.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/webapi/merge-entity-using-web-api.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @divkamath
* Microsoft Alias: **dikamath**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @surfarri. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@surfarri 

1. My understanding is that any useful data from the `Subordinate` record will be moved to the `Target`. Since the target is the record to remain active, I don't expect that this will overwrite any columns in the target that have data. So only columns that are 'blank' should be set on the `Target` record.

2. I don't see any capability to specify a specific `statuscode` value. If you have added custom `statuscode` options, I expect that the default `statuscode` option for the inactive `statecode` will be chosen. For an account record, you can see the default status is 2 (Inactive). See [Account  StateCode Options](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/reference/entities/account#statecode-choicesoptions) But you could try to set this in a plug-in registered for the `Merge` operation.

**Comment by JimDaly** [comment]
Updated article to clarify.
