### ISSUE TITLE
Similar cmdlets [PowerShell]

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/powerapps-docs#47]
Each environment is shared by both powerapps and flow and the Get-PowerAppsEnvironment and Get-FlowEnvironment return the same objects, why are there 2 cmlets? I would think that one cmdlet would be adquate

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a682d40-fb0d-4938-b1ac-cee291c2bbff
* Version Independent ID: c7fdffb8-c6b7-f02b-a5e0-6787218978c6
* Content: [PowerShell support (preview) - PowerApps](https://docs.microsoft.com/en-us/powerapps/administrator/powerapps-powershell)
* Content Source: [powerapps-docs/administrator/powerapps-powershell.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/administrator/powerapps-powershell.md)
* Service: **powerapps**
* GitHub Login: @jamesol-msft
* Microsoft Alias: **jamesol**

**Comment by jamesol-msft** [comment]
Because Flow is offered as a stand-alone product from PowerApps, and the Get-PowerAppsEnvironment cmdlet will not work if the user does not have a PowerApps license.

Now, you may ask "why not publish separate cmdlets for Flow vs PowerApps?" and is a very good question and one we considered.   However, given the amount of overlap between the new platform capabilities (and the fact that PowerApps always included Flow), we decided to start with just one library for now.
