### ISSUE TITLE
Lack of a way to detect Form type of model-driven app in PCF Context

### ISSUE THREAD

**Issue by keijimscom** [MicrosoftDocs/powerapps-docs#4748]
[Enter feedback here]
There is lack of a way to detect Form type of model-driven app in PCF Context.
Needs the feature like the getFormType  in Client API: [getFormType](https://learn.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/reference/formcontext-ui/getformtype)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5f219919-646d-18e5-2766-365f34aea315
* Version Independent ID: de311f39-0493-955f-d3fb-7b38071b5ab9
* Content: [Context (Power Apps component framework API reference) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/component-framework/reference/context)
* Content Source: [powerapps-docs/developer/component-framework/reference/context.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/component-framework/reference/context.md)
* Service: **powerapps**
* Sub-service: **pcf**
* GitHub Login: @noazarur-microsoft
* Microsoft Alias: **noazarur**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @keijimscom. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
Added @HemantGaur for visibility, but this appears to be a feature request.  We can't fix this with documentation, so it isn't an actionable issue until that feature is added.

Since the getFormType method returns information like this:

<html>
<body>


Value | Form type
-- | --
0 | Undefined
1 | Create
2 | Update
3 | Read Only
4 | Disabled
6 | Bulk Edit


</body>
</html>

I can see how this would be useful for the PCF developer to have this information in the context.
I'm not aware of another way to detect this. 

Recommend posting this feature request on the [Power Apps Ideas site](https://ideas.powerapps.com/d365community/forum/f1458c72-ae29-ed11-9db2-000d3a8c451e).

Closing this
