### ISSUE TITLE
Mistake/Bug in the userSettings.roles documentation

### ISSUE THREAD

**Issue by acaprodware** [MicrosoftDocs/powerapps-docs#5046]
Xrm.Utility.getGlobalContext().userSettings.roles returns only the security roles assigned directly to the current user and not the roles inherited by teams where the current user is a member as stated in this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 999537e5-d7fd-6e16-207a-b7c7c31fdc9e
* Version Independent ID: 48ac9b62-a8b5-3bab-11b5-c0bbc5fde88c
* Content: [getGlobalContext.userSettings (Client API reference) in model-driven apps - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/reference/xrm-utility/getglobalcontext/usersettings)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Utility/getGlobalContext/userSettings.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Utility/getGlobalContext/userSettings.md)
* Service: **powerapps**
* Sub-service: **mda-developer**
* GitHub Login: @adrianorth
* Microsoft Alias: **aorth**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @acaprodware. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@acaprodware 
Thanks for your feedback.

The docs say this: [userSettings.roles](https://learn.microsoft.com/power-apps/developer/model-driven-apps/clientapi/reference/xrm-utility/getglobalcontext/usersettings#roles)

> Returns a collection of lookup objects containing the GUID and display name of each of the security role assigned to the user and any security roles assigned to the team that the user is associated with. This method is supported only on Unified Interface.

I used this code to check from the Edge developer tools in a model-driven app:

```
function writeOutput(role,index){
  console.log("id: "+ role.id +" name: " + role.name);
}

Xrm.Utility.getGlobalContext().userSettings.roles.forEach(writeOutput);
```
It returned these 5 results:

```
id: 54bc2ab3-f5ba-e811-a962-000d3a1cbed4 name: Basic User
id: 7a1fd7a1-cca4-e911-a81e-000d3a36fe11 name: Account App
id: cad52a75-568c-e611-80d4-00155d42a122 name: Sales Enterprise app access
id: 3dac4d9e-568c-e611-80d4-00155d42a122 name: Customer service app access
id: 16e3dbe4-131b-e111-ba7e-78e7d1620f5e name: System Administrator
```

Then I ran this query using [Web API via Postman](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/webapi/setup-postman-environment) to get the roles directly related to my systemuser account:

```
GET {{webapiurl}}systemusers(<my userid>)/systemuserroles_association?$select=name
```
It returned these 3 results:

```
{
    "@odata.context": "https://myorg.api.crm.dynamics.com/api/data/v9.2/$metadata#roles(name)",
    "value": [
        {
            "name": "Sales Enterprise app access",
            "roleid": "cad52a75-568c-e611-80d4-00155d42a122"
        },
        {
            "name": "Customer service app access",
            "roleid": "3dac4d9e-568c-e611-80d4-00155d42a122"
        },
        {
            "name": "System Administrator",
            "roleid": "16e3dbe4-131b-e111-ba7e-78e7d1620f5e"
        }
    ]
}
```

These roles are not directly associated to my user account:

> id:54bc2ab3-f5ba-e811-a962-000d3a1cbed4 name: Basic User
> id:7a1fd7a1-cca4-e911-a81e-000d3a36fe11 name: Account App

But they are associated to other teams I'm associated with. I can verify this using this Web API query:

```
GET {{webapiurl}}systemusers(<my userid>)/teammembership_association?$select=name
```

I get all the teams I'm part of. Then for each team, I use this query:

```
GET {{webapiurl}}teams(<team id>)/teamroles_association?$select=name
```

I find the two missing roles associated to those teams.

I have to conclude that the documentation is accurate. 
I recommend you try this yourself and see whether you get similar results.

If you aren't getting similar results, I recommend contacting technical support.

Closing this since there doesn't appear to be anything actionable for the docs.
