### ISSUE TITLE
Error: disableAsyncTimeout on OnLoad in not a function 

### ISSUE THREAD

**Issue by Astaneta** [MicrosoftDocs/powerapps-docs#5052]
Hello,
I’m trying to use the method executioncontext.getEventArgs().disableAsyncTimeout() on the onLoad event. I found this method on the [Form-Onload](https://learn.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/reference/events/form-onload) page, but when I call the onLoad method, I receive an error message saying that disableAsyncTimeout is not a method (while getEventArgs is correctly working). 
In fact, on this page [geteventargs](https://learn.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/reference/executioncontext/geteventargs) that method exists only as child of onSave method. 
Is it possibile to disable the timeout on onLoad or it is an error of the documentation?

My current dataverse version is 9.2.23112.00216

**Comment by JimDaly** [comment]
@Astaneta -
Thanks for your feedback and apologies for the delay in responding.
Our doc feedback system works best when people use the **Feedback** > **This page** button at the bottom of the article.
This notifies the contributors and we can respond faster.

You didn't mention this, but I can't assume. Did you turn on the setting mentioned here [Enable Async OnLoad using app setting](https://learn.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/reference/events/form-onload#enable-async-onload-using-app-setting), just above the description of the `disableAsyncTimeout` even argument? This seems a possilbe cause.

I also found this blog post [Disable Async Timeout for Save Events in Model-Driven Forms – Show Dialogs in OnSave](https://dianabirkelbach.wordpress.com/2023/03/23/disable-async-timeout-for-save-events-in-model-driven-forms-show-dialogs-in-onsave/) which indicates that it does work, but perhaps didn't for some time. A forum post on a similar issue: [model-driven app Client API : disableAsyncTimeout issue](https://powerusers.microsoft.com/t5/Power-Apps-Pro-Dev-ISV/model-driven-app-Client-API-disableAsyncTimeout-issue/td-p/1574911)

@tahoon-ms 
This is the current description of [Async OnLoad timeouts](https://learn.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/reference/events/form-onload#async-onload-timeouts)

> **Async OnLoad timeouts**
> When using an async handler, a form load will wait for the promise to be fulfilled, but only up to 10 seconds. This is to ensure that the form loads within a reasonable amount of time.
> 
> There may be scenarios where you want to pause OnLoad for a longer period of time. An example is opening a dialog in the async OnLoad handler and waiting for the user's input before saving. To make sure the async operation will wait, you can invoke the event argument **disableAsyncTimeout** as follows `executioncontext.getEventArgs().disableAsyncTimeout()`. When **disableAsyncTimeout** is set, the timeout for that handler will not be applied. It will continue to wait for that handler's promise to be fulfilled.
> 
> This should be used with caution as it might affect the performance of the form load.

Is there anything we might change in the content of this page? Perhaps a link to the community blog post?

From an information architecture perspective, we should have a separate page for this argument.
 - Create new `disableAsyncTimeout.md` page and add it to the table of contents below [setSharedVariable](https://learn.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/reference/executioncontext/setsharedvariable)
 - Change this row in `save-event-arguments.md`: `|[disableAsyncTimeout](events/form-onsave.md#async-onsave-timeouts)|Disables the default async handler timeout.|` so that it points to the new page.
 - Update `form-onload.md` so that it refers to the new page.
 - Update [Execution context (Client API reference)](https://learn.microsoft.com/power-apps/developer/model-driven-apps/clientapi/reference/execution-context) table so it is listed there

**Comment by tahoon-ms** [comment]
The documentation is in error. `disableAsyncTimeout()` is not available for OnLoad events.

These 2 paragraphs should be removed:

```
There may be scenarios where you want to pause OnLoad for a longer period of time. An example is opening a dialog in the async OnLoad handler and waiting for the user's input before saving. To make sure the async operation will wait, you can invoke the event argument disableAsyncTimeout as follows executioncontext.getEventArgs().disableAsyncTimeout(). When disableAsyncTimeout is set, the timeout for that handler will not be applied. It will continue to wait for that handler's promise to be fulfilled.

This should be used with caution as it might affect the performance of the form load.
```

**Comment by JimDaly** [comment]
Thanks @tahoon-ms  & @Astaneta 

With your input we have updated the content.
