### ISSUE TITLE
File Column Data Storage details

### ISSUE THREAD

**Issue by rranjit83** [MicrosoftDocs/powerapps-docs#5104]
Provide details on the what is stored in the relational tables vs the file storage. This page must explicitly call this out .
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8026a170-f2e5-9d5f-3c7b-0fcfaca0d71c
* Version Independent ID: 7b8e643b-ad4a-2032-ef27-413ed7e8f97a
* Content: [File columns (Microsoft Dataverse) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/file-attributes?tabs=sdk)
* Content Source: [powerapps-docs/developer/data-platform/file-attributes.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/file-attributes.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @NHelgren
* Microsoft Alias: **nhelgren**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @rranjit83. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@rranjit83 
Thanks for your feedback.

The scope of this article is for developers to use the APIs to create file columns. I'm not clear about how the implementation details about which parts are stored in relational tables vs file storage helps them do that better. 

- Can you elaborate on how this information will make people more successful?
- Who needs this information and what will they do with it?

There is more content for developers about _using file columns_ here: [Use file column data](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/file-column-data?tabs=sdk). It explains some of the other columns in the table that support the file column, and the [relationship to the FileAttachment table](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/file-column-data?tabs=sdk#relationship-to-fileattachment-table) so that you can [retrieve additional information about the file](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/file-column-data?tabs=sdk#retrieve-additional-information-about-files-for-a-record).

There is general content about file columns for all audiences here: [Types of columns: File columns](https://learn.microsoft.com/en-us/power-apps/maker/data-platform/types-of-fields#file-columns).
