### ISSUE TITLE
Alternate Keys with Multi-table lookups in WebAPI requests?

### ISSUE THREAD

**Issue by DanielBruckhaus** [MicrosoftDocs/powerapps-docs#5123]
The documenation is missing guidance on how to use an Alternate Key that includes a Multi-table lookup (or "Polymorphic Lookup").

Alternate Keys that include a multi-table lookup automatically contain the associated "...type" column to identify the referenced entity's type.

Using the SOAP/.Net API, such a key can be used like this:
```
var key = new KeyAttributeCollection()
{
    ["test_regardingobjectid"] = new EntityReference("account", new Guid("c1cc0063-bfd3-ed11-a7c7-000d3aabc3d6")), 
    ["test_regardingobjectidtype"] = 1
};
```

However, I could not find a way to use such a key with the WebAPI.
The documentation states that for lookup attributes, the name of the single-valued navigation property (ReferencingEntityNavigationPropertyName) has to be used.
This name is unique per individual relationship, so the referenced type is always uniquely identitfied, even when using multi-table lookups.
However, any attempts of using an alternate key with the multi-table lookup via the WebAPI results in this error message:
_The key in the request URI is not valid for resource 'Microsoft.Dynamics.CRM.[...]'. Ensure that the names and number of key properties match the declared or alternate key properties for the resource [...]_

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cd844db9-ff8f-0573-1596-bb31d6d4609a
* Version Independent ID: cd844db9-ff8f-0573-1596-bb31d6d4609a
* Content: [Use an alternate key to reference a record - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/use-alternate-key-reference-record?tabs=webapi)
* Content Source: [powerapps-docs/developer/data-platform/use-alternate-key-reference-record.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/use-alternate-key-reference-record.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @divkamath
* Microsoft Alias: **dikamath**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @DanielBruckhaus. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@DanielBruckhaus 

Thanks for your feedback. I need to check with the dev team to see if this is a supported scenario. I need more information from you.

Generally, we support using our schema definition (metadata) APIs to do anything you can do in the Power Apps portal. Creating a [polymorphic (multi-table) lookup](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/webapi/multitable-lookup) is an exception.

The Power Apps portal _does_ allow you to create a _customer lookup_, which is a type of polymorphic lookup that includes account and contact records only.

To test your scenario, I created this customer lookup because it is easy to do in the UI. Then I tried to make it an alternate key for my table in the Power Apps UI [as described here](https://learn.microsoft.com/power-apps/maker/data-platform/define-alternate-keys-portal). But that customer lookup column wasn't presented as an option.

However, we have documented [how to create an alternate key with code without using the UI](https://learn.microsoft.com/power-apps/developer/data-platform/define-alternate-keys-entity#create-alternate-keys).

My questions for you are: 

- Is your scenario using a Customer lookup, or a 'custom' polymorphic relationship? 

   - You can create a customer lookup using [CreateCustomerRelationships](https://learn.microsoft.com/dotnet/api/microsoft.xrm.sdk.messages.createcustomerrelationshipsrequest?view=dataverse-sdk-latest), but a polymorphic lookup requires [CreatePolymorphicLookupAttribute](https://learn.microsoft.com/dotnet/api/microsoft.crm.sdk.messages.createpolymorphiclookupattributerequest). Knowing this could be important to establish what is supported.
   
 - Did you create the alternate key using the UI, or with code? 
 
    - Is the polymorphic lookup you created visible in the UI to create an alternate key?
 
If the end-to-end scenario can be replicated using the UI, then it should be supported. If not, we need to find out whether this scenario was tested and is supported.

**Comment by DanielBruckhaus** [comment]
@JimDaly 
thanks for your feedback!
Regarding your questions:

- _Is your scenario using a Customer lookup, or a 'custom' polymorphic relationship?_
It's a custom polymorphic relationship, created via XRMToolbox Polymorphic Lookup Manager

- _Did you create the alternate key using the UI, or with code?_
Alternate Key created via UI, where the Polymorphic Lookup is selectable:
![image](https://github.com/MicrosoftDocs/powerapps-docs/assets/10832182/376a9cec-b5d1-408d-ae98-818bd1395de0)

I had also noticed that Customer-Lookups are not selecteable in the UI as part of an alternate key, however, I had assumed this was because of their special AttributeType ("Customer" instead of "Lookup").

**Comment by JimDaly** [comment]
I think this is a bug or undocumented limitation.
Here is what I did:

1. Created three tables:

   - `sample_RelatedRecord`
   - `sample_TargetA`
   - `sample_TargetB`

1. Created a multi-table (polymorphic) lookup on `sample_RelatedRecord` named `sample_RegardingId` so that the [LookupAttributeMetadata.Targets](https://learn.microsoft.com/dotnet/api/microsoft.xrm.sdk.metadata.lookupattributemetadata.targets?view=dataverse-sdk-latest) value is:  `sample_targeta,sample_targetb`.

1.  Using Power Apps, created an alternate key on `sample_RelatedRecord` with **LogicalName** = `sample_polymorphiclookup` and **KeyAttributes** = `sample_regardingid,sample_regardingidtype`

    At this point, I can see all the data for these items in Power Apps.

1.  Downloaded the $metadata service document using the script here: [Download the Dataverse Web API CSDL $metadata document](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/webapi/use-ps-and-vscode-web-api#download-the-dataverse-web-api-csdl-metadata-document)

**Expected**:

When I view the $metadata service document, I should see the definition of the alternate key created for the `sample_RelatedRecord` table as described here: [Entity Types > Alternate Keys](https://learn.microsoft.com/power-apps/developer/data-platform/webapi/web-api-entitytypes#alternate-keys)

**Actual**:

The alternate key `Annotation` isn't present in the `EntityType` definition for the table. It is present for other alternate keys in the environment.

**Conclusion**:

If the alternate key definition isn't reflected in the OData $metadata service document, the Web API doesn't know it exists. It can't be used.

You should contact technical support to report this issue so it can be escalated. You can refer to this issue.

I'll contact the teams to see if this is a bug to be fixed or if we should document that this isn't supported.

**Comment by DanielBruckhaus** [comment]
@JimDaly 
thanks again for the feedback and analysis.
I've opened a ticket with technical support as suggested: Ticket#2401240050000305

**Comment by JimDaly** [comment]
Thanks @DanielBruckhaus 
There isn't anything currently actionable for the docs now.
Let's see what the product team decides. 

Closing this.
