### ISSUE TITLE
Update documentation for low code developers

### ISSUE THREAD

**Issue by iddycol** [MicrosoftDocs/powerapps-docs#5226]
[Enter feedback here]

This page describe how to create and invoke a custom API. However it does not explain if it is possible to call the created API using PowerFX (either from a model driven app command button or a canvas app). It would useful to add that, either with a link to the documentation or a note in the FAQ section if it is not possible to do this.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dbd53494-e9ff-33b0-d857-bcd235233aa5
* Version Independent ID: a362d3d7-3d5c-9222-39e6-dd426f96c4a4
* Content: [Create and use custom APIs (Microsoft Dataverse) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/custom-api)
* Content Source: [powerapps-docs/developer/data-platform/custom-api.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/custom-api.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @divkamath
* Microsoft Alias: **dikamath**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @iddycol. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@iddycol 

Thanks for your feedback.

Custom APIs allow a developer to create new Dataverse messages that are exposed as Web API functions or actions.

The content doesn't talk about Power FX because AFAIK, there is no capability to invoke any of the Dataverse Web API [functions](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/webapi/reference/functions?view=dataverse-latest) or [actions](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/webapi/reference/actions?view=dataverse-latest) other than [SendAppNotification Action](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/webapi/reference/sendappnotification?view=dataverse-latest) using [XSendAppNotification](https://learn.microsoft.com/en-us/power-platform/power-fx/reference/function-send-app-notification). Our documentation describes the things a feature does. Documenting all the things a feature doesn't do is not realistic.

I understand that you are expecting this capability and I hope that Power FX will enable it. But until that time, there isn't anything to speak to here. If a capability for Power FX to leverage these Dataverse capabilities is valuable to you, I recommend posting this on the [Power Apps Ideas page](https://ideas.powerapps.com/d365community/forum/f1458c72-ae29-ed11-9db2-000d3a8c451e)

If this capability becomes available, this page will be should to speak to it
