### ISSUE TITLE
duplicate "x-ms-service-request-id" header in response

### ISSUE THREAD

**Issue by gghaleb** [MicrosoftDocs/powerapps-docs#5235]
Is it normal to get a response with two "x-ms-service-request-id" headers when i send the {{webapiurl}}WhoAmI  dataverse request from Postman ?

**Comment by JimDaly** [comment]
@gghaleb 

Thanks for your feedback.

There are a lot of headers returned in the response. We document them as needed. As far as I know, there is no external use case for the `x-ms-service-request-id` response header. We don't talk about it because we don't want people to take a dependency on it.

The only place I see it mentioned in passing is here [Telemetry events for model-driven apps > Where is the page load data available?](https://learn.microsoft.com/en-us/power-platform/admin/telemetry-events-model-driven-apps#where-is-the-page-load-data-available) where it says:

> For Microsoft Dataverse events, the **ID** field or **operation_ParentId** in Application Insights is the **x-ms-service-request-id**. The **operationId** maps to the **activityId** on the back end for troubleshooting purposes and support requests.

But I think this paragraph isn't needed, it is just some extra detail.

Is this causing a problem? Or are you just curious?

**Comment by JimDaly** [comment]
OK.  [Looks like duplicate response headers are acceptable](https://stackoverflow.com/questions/4371328/are-duplicate-http-response-headers-acceptable). Closing this.
