### ISSUE TITLE
LookUpObjects Reference not correct

### ISSUE THREAD

**Issue by CrytoxXD** [MicrosoftDocs/powerapps-docs#5237]
The link to the lookupOptions points to the xrm-utility page. The documentation there contains options which are not present in in the power apps component framework api (for example the option "filters").

That is confusing. 
I would propose that either the link points to the correct site or the properties from the xrm-utily page are made available in the pcf api.

Personally I'd prefer the second option, because it would add a possibility properly customize which data is displayed in the lookup.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8adb7aec-f488-0653-4b0e-2793d9b75509
* Version Independent ID: aa79b169-3a80-1a06-dba3-d173d8e22aa0
* Content: [lookupObjects (Power Apps component framework API reference) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/component-framework/reference/utility/lookupobjects)
* Content Source: [powerapps-docs/developer/component-framework/reference/utility/lookupobjects.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/component-framework/reference/utility/lookupobjects.md)
* Service: **powerapps**
* Sub-service: **pcf**
* GitHub Login: @HemantGaur
* Microsoft Alias: **hemantg**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @CrytoxXD. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
OK, Summarizing this this way:

> The [PCF context.utils.lookupObjects page](https://learn.microsoft.com/power-apps/developer/component-framework/reference/utility/lookupobjects) page contains a link to the [Client API Xrm.Utility.lookupObjects](https://learn.microsoft.com/power-apps/developer/model-driven-apps/clientapi/reference/xrm-utility/lookupobjects) page. This client api page includes descriptions of [lookupOptions properties](https://learn.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/reference/xrm-utility/lookupobjects#lookupoptions-properties) such as _filters_ that are not included in the PCF context.utils.lookupObjects.

Is that correct?

@CrytoxXD How do you know that the Xrm.Utility.lookupObjects LookupOptions _contains options which are not present in in the power apps component framework api (for example the option "filters")._? Did you try to use them and get an error?

I think we need the product team to verify and isolate which lookupOptions are valid in the PCF context and document them in the [PCF context.utils.lookupObjects page](https://learn.microsoft.com/power-apps/developer/component-framework/reference/utility/lookupobjects) page. I can help them with that.

@rarattay Can you help verify and isolate which [Client API lookupOptions](https://learn.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/reference/xrm-utility/lookupobjects#lookupoptions-properties) applies to PCF or not?

**Comment by CrytoxXD** [comment]
Hi @JimDaly,
Yes that is correct.

1. Upon examining the typings of the objects in VSCode, I noticed they options aren't present.
2. To work around the error, I attempted to use "ts-ignore" above the line and specified a filter anyway. However, it didn't seem to have any effect. I didn't receive an error message, but it also didn't behave as expected.

Any insight into this matter is greatly appreciated.

**Comment by rarattay** [comment]
Currently the only supported LookupOptions in the PCF API typings are: allowMultiSelect, defaultEntityType, defaultViewId, entityTypes, viewIds, and searchText. It is possible that the other LookupOptions properties were added after PCF's support for it, and we can look into adding support for more properties in the future.

In the meantime, we can update the docs to be clearer on which specific properties are supported. 

@CrytoxXD You could try overriding the typings with a global.d.ts​ file that includes the properties on LookupOptions that you want to use.

**Comment by CrytoxXD** [comment]
Hi @rarattay,

Hmm, yes, I would really appreciate it if you could update the documentation to provide clearer explanations regarding the properties. I'm hesitant to override the typings as it could potentially expose the PCF to unexpected errors or compromise its updateability.

Could you provide us with an estimate or a roadmap outlining when the properties will be supported? Or is that not determined yet?

**Comment by JimDaly** [comment]
This issue is addressed with changes made to the [PCF context.utils.lookupObjects page](https://learn.microsoft.com/power-apps/developer/component-framework/reference/utility/lookupobjects). It no longer refers to the Client API page and the Remarks section contains a table with the options valid for PCF scenarios

The lookupOptions available for components is different from those for the [Client API Xrm.Utility.lookupObjects lookupOptions properties](../../../model-driven-apps/clientapi/reference/Xrm-Utility/lookupObjects.md#lookupoptions-properties) available for model-driven app client side scripts.

### lookupOptions properties

For components, lookupOptions parameter has the following properties:

|Property Name |Type |Required |Description |
|---|---|---|---|
|`allowMultiSelect`|Boolean|No|Indicates whether the lookup allows more than one item to be selected.|
|`defaultEntityType`|String|No|The default table type to use.|
|`defaultViewId`|String|No|The default view to use.|
|`entityTypes`|Array|Yes|The table types to display.|
|`searchText`|String|No|Indicates the default search term for the lookup control. This is supported only on [Unified Interface](/power-platform/admin/about-unified-interface).|
|`viewIds`|Array|No|The views to be available in the view picker. Only system views are supported.|

The `disableMru` and `filters` properties available for model-driven app client scripts are not available for components.
