### ISSUE TITLE
How to connect Power App with dataflow?

### ISSUE THREAD

**Issue by legendgod** [MicrosoftDocs/powerapps-docs#5241]
The page is talking about how to create dataflow. However, I cannot find any instruction to connect App to Dataflow.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 69ef5ecf-6d78-d852-f9ec-bf452864f0f5
* Version Independent ID: 9a080f0e-f168-ee88-2b32-22e55e95ae4c
* Content: [Create and use dataflows in Power Apps - Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/data-platform/create-and-use-dataflows?source=recommendations)
* Content Source: [powerapps-docs/maker/data-platform/create-and-use-dataflows.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/create-and-use-dataflows.md)
* Service: **powerapps**
* Sub-service: **dataverse-maker**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@legendgod  - You don't connect Power Apps to a dataflow per se. You can access the table records that are created and/or updated in Dataverse from the dataflow by using Power Apps, such as creating a canvas app or model-driven app to include the tables. So once you have the dataflow in place that you want. Create an app that includes the Dataverse tables you want.
For example, a model-driven app (use the tables populated from the dataflow instead of account and contact): [Create an app with an account table](https://learn.microsoft.com/en-us/power-apps/maker/model-driven-apps/create-a-model-driven-app)

Closing issue.
