### ISSUE TITLE
typo in code `entity["sample_description"] = preImage["sample_description"] += message;`

### ISSUE THREAD

**Issue by skfd** [MicrosoftDocs/powerapps-docs#5264]
this line does not look correct:
`entity["sample_description"] = preImage["sample_description"] += message;`

Also sample has a a little bit of pyramid of doom nesting. Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8dd4cb2f-c1e8-b741-98b2-229f5952b5da
* Version Independent ID: 8dd4cb2f-c1e8-b741-98b2-229f5952b5da
* Content: [Write plug-ins for CreateMultiple and UpdateMultiple - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/write-plugin-multiple-operation?WT.mc_id=DX-MVP-5004571&tabs=single)
* Content Source: [powerapps-docs/developer/data-platform/write-plugin-multiple-operation.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/write-plugin-multiple-operation.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @divkamath
* Microsoft Alias: **dikamath**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @skfd. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@skfd 

Thanks for your feedback.

This code comes from the sample on GitHub that you can run. See [Sample: CreateMultiple and UpdateMultiple plug-ins](https://learn.microsoft.com/power-apps/developer/data-platform/org-service/samples/createmultiple-updatemultiple-plugin).

You can run the sample and determine whether the code isn't correct. Please let us know if you find something that doesn't work.

Finally, yes the function has some nested logic.  I am trying to keep things simple and in one place rather than create a separate method. Pulling the logic out into another method is a common pattern, but the intention for this example is to demonstrate the flow. I think that would be diminished if the relatively simple logic of this example was put into a separate method.
