### ISSUE TITLE
Deprecated Entities listed in Common Data Service Web API

### ISSUE THREAD

**Issue by gregdegruy** [MicrosoftDocs/powerapps-docs#577]
Is this a [deprecation issue](https://docs.microsoft.com/en-us/dynamics365/get-started/whats-new/customer-engagement/important-changes-coming)?

Since the change of Microsoft deprecating the entity properties processid, process stage name and few more info directly from a main entity ( in my case [opportunity entityType](https://docs.microsoft.com/en-us/dynamics365/customer-engagement/web-api/opportunity?view=dynamics-ce-odata-9) ) to new businesses process flow entity and its records. These deprecated properties are still listed as supported in the [opportunity entityType](https://docs.microsoft.com/en-us/dynamics365/customer-engagement/web-api/opportunity?view=dynamics-ce-odata-9) and other entities throughout the docs. 

This incorrect information in the REST API is impacting speed of development and overall understanding of the API from the community at large.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 227fd50c-3385-52c1-a57d-08dca61d36c4
* Version Independent ID: 3d616dde-59fa-4ab0-14e0-0ddbf972fe64
* Content: [Use the Common Data Service Web API (Common Data Service) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/overview?view=dynamics-ce-odata-9)
* Content Source: [powerapps-docs/developer/common-data-service/webapi/overview.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/webapi/overview.md)
* Service: **powerapps**
* GitHub Login: @brandonsimons
* Microsoft Alias: **susikka**

**Comment by JimDaly** [comment]
From the topic you linked to:

> “Deprecated” means we intend to remove the feature or capability from a future major release of Dynamics 365. The feature or capability will continue to work and is fully supported until it is officially removed. This deprecation notification can span a few years. After removal, the feature or capability will no longer work. We are notifying you now so you have sufficient time to plan and update your code before the feature or capability is removed.

The reference documentation about the Web API simply lists the entities and attributes as they exist. It is not incorrect, but you could argue that it is incomplete because it doesn't reflect that specific properties have been deprecated. If the service documents that provide the data for these generated topics included the information about whether the properties are deprecated or not, this information could be included in the docs.

What you have is a feature request. You can submit your ideas at the [PowerApps Ideas](https://powerusers.microsoft.com/t5/PowerApps-Ideas/idb-p/PowerAppsIdeas) site.
