### ISSUE TITLE
Examples please

### ISSUE THREAD

**Issue by jjsowers** [MicrosoftDocs/powerapps-docs#597]
If you are going to call something an "overview", then you really need to give some specific examples of the types of problems you would solve with each of the types of apps.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd466cfc-002f-eba5-da1a-a82ddad5fea5
* Version Independent ID: 5313c975-6848-3d03-9a18-a5ed0cb07149
* Content: [Overview of creating apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/index#feedback)
* Content Source: [powerapps-docs/maker/index.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/index.md)
* Service: **powerapps**
* GitHub Login: @AFTOwen
* Microsoft Alias: **anneta**

**Comment by KumarVivek** [comment]
@jjsowers This topic specifically provides an overview of each app type you can create in PowerApps, and then provides deep link to specific app area for detailed information. We have tried to keep the information succinct so that it's easily scannable.

What specific information you are looking for?

**Comment by KumarVivek** [comment]
Closing this as I did not get a reponse.
