### ISSUE TITLE
How to use Flow to hide a Channel In Teams

### ISSUE THREAD

**Issue by Benzin42** [MicrosoftDocs/powerapps-docs#628]
It was easy to find how to create a channel in Teams (in this case for a new item in a SharePoint list).

When the item has been completed (specific field completed), I would like to hide the Teams Channel, since it is no longer needed (but shouldn't be deleted).

Does anyone know how?

thanks

**Comment by tapanm-MSFT** [comment]
Hello, thank you for reaching out. Since this issue has been open for long, closing it for now. For discussions and suggestions to requirements like above, please feel free to reach out to the [Power Automate community forum](https://powerusers.microsoft.com/t5/Microsoft-Power-Automate/ct-p/MPACommunity). You can also report an issue through [support](https://learn.microsoft.com/power-platform/admin/get-help-support).
