### ISSUE TITLE
Data Section Inconsistencies

### ISSUE THREAD

**Issue by jasonaalmeida** [MicrosoftDocs/powerapps-docs#658]
The data section of this page includes Optionsets in addition to Entities, Fields and Relationships. This seems inconsistent as optionsets are a type of field so would be a subset of field.
The related link  (https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/define-data-model-driven-app) seems more consistent as it only includes the main 3 components.

I would suggest removing optionsets from this overview and moving it to the type of fields section (https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/types-of-fields)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa788547-0b4a-7c36-8035-95a0c0386927
* Version Independent ID: bd9e046d-a255-c965-6356-84508141ff61
* Content: [Understand model-driven app components in PowerApps - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/model-driven-app-components)
* Content Source: [powerapps-docs/maker/model-driven-apps/model-driven-app-components.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/model-driven-apps/model-driven-app-components.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@jasonaalmeida - Thank you for your feedback. Unlike in solution explorer you'll notice that option sets are created and edited in a separate area under the **Data** section on the PowerApps maker portal. 
This  is indicated as such in the table under the **Designer** column. Because of the separate placement  in the UI we feel it warrants separate listing in the **Data** section of the topic. 
However, to make the table appear less disjointed I've moved relationships up a row and fields down. 
Closing issue.
