### ISSUE TITLE
What are the units for fontsize? Is it px? They do not display in the fontsize property

### ISSUE THREAD

**Issue by shane-moore** [MicrosoftDocs/powerapps-docs#661]

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. [Font size](https://docs.microsoft.com/powerapps/maker/canvas-apps/controls/properties-text) is in font size points. You can use different values to review the font size as per the requirement. If this question is for any other article, please reach out via feedback from the specific article page.

**Comment by vnys** [comment]
@shane-moore The font-size seem to be in Pica points, which is what you would use in print. To translate it into pixels, you would have to divide it by 72 and multiply it with 96. The reason is that one typographic point is 1/72 of an inch, and the screen resolution in Windows is 96 dots per inch. So 12pt is rendered on screen as 16px. I was a bit surprised when I found out that Power Apps doesn't use pixels, reminds me of what web development was like back in the 90s when we used `<font size="3">Some text</font>` to define font-size, and it was rendered as 12px on the mac and 16px on Windows. Fun times 😉
