### ISSUE TITLE
Urgently need an update regarding those restricted entities

### ISSUE THREAD

**Issue by popujol** [MicrosoftDocs/powerapps-docs#689]
Urgently need an update regarding those restricted entities.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ecf0cd5-9a4c-780a-7cc9-c189d399efa5
* Version Independent ID: 32aeab29-70b5-97b3-1a6b-96c6bfcecc3c
* Content: [Restricted entities requiring Dynamics 365 licenses - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/data-platform-restricted-entities)
* Content Source: [powerapps-docs/maker/common-data-service/data-platform-restricted-entities.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/data-platform-restricted-entities.md)
* Service: **powerapps**
* GitHub Login: @lancedMicrosoft
* Microsoft Alias: **lanced**

**Comment by popujol** [comment]
The list of NOT RESTRICTED ENTITIES would be better even

**Comment by iangpgh** [comment]
@popujol Article is recently updated with the list of restricted entities. 

[Restricted entities requiring Dynamics 365 licenses](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/data-platform-restricted-entities)

**Comment by iangpgh** [comment]
@popujol Correction: the list of restricted entities was not updated in this article. We are working on updating these soon.

**Comment by tapanm-MSFT** [comment]
Hello, thank you for reaching out. Since this issue has been open for long, closing it for now. The documentation has had several updates since this issue was open. If you have any other ask or a pending question, please feel free to report a new documentation issue. For discussions regarding product, feel free to utilize the [Power Apps community forum](https://powerusers.microsoft.com/t5/Power-Apps-Community/ct-p/PowerApps1)
