### ISSUE TITLE
The line -2147015898	Number of concurrent requests exceeded the limit of X has no value

### ISSUE THREAD

**Issue by cadilu** [MicrosoftDocs/powerapps-docs#699]
The line -2147015898	Number of concurrent requests exceeded the limit of X has no value (Instead of a value, there´s an "X"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fd657fb-b2cb-a85a-7243-41d7cc30dc87
* Version Independent ID: 4ed6833a-668b-ff05-97da-286fb6d68394
* Content: [API Limits (Common Data Service) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/api-limits#feedback)
* Content Source: [powerapps-docs/developer/common-data-service/api-limits.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/api-limits.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **bsimons**

**Comment by JimDaly** [comment]
This is because the value may change. We continue to tune the values to reach the right balance.

The values also depend on the product sku. Trial instances have much lower limits.

But most importantly, we don’t want people fixated on specific numbers so that they try to hard code around these changing numbers. The key thing we hope people will take away from the documentation is that they should write code in such a way to manage transient errors and treat the protective throttling errors like other kinds of transient errors.

**Comment by IanLimn** [comment]
Without knowing the number, how then do I answer my boss when she asks me “what’s the maximum number of concurrent users that we can support without entering error handling scenarios?”. Which is exactly what I’m being asked. I can calculate api calls for specific transaction loads and have a model that yields api call volumes for different transaction mixes for multiple types of concurrent users - but without knowing where the end point is, what’s my max users? “Sorry, we’ll just have to go live and find out. I can’t guarantee you any number, because the vendor wants us to treat protective throttling errors like other kinds of transient errors”.

**Comment by JimDaly** [comment]
Fair enough.
Well, it isn't exactly the number of concurrent users, it is the number of concurrent connections. Multi-threaded applications which seek to maximize the throughput of a large data migration are the main focus here. The base number starts at about 50. That is - one user has 50 browser sessions open in the simplest view, but in reality even the browser can run a certain number of concurrent connections in some circumstances. It is possible, but not common.

**Comment by JimDaly** [comment]
I need to clarify that the number of concurrent connections doesn't mean number of concurrent users.

**Comment by mohsinonxrm** [comment]
@cadilu , @IanLimn , as per my testing from (Aug ~ Sep 2019), the limit was 40 max. concurrent requests per user. This applies on both, client and server side requests. Like @JimDaly said in his original comment that this limit can change in the future, so just implement your logic to use bulk requests (ExecuteMultipleRequest (SOAP) or $batch (REST/WebAPI)) and use retry logic.

Obviously, this will add complexity to things as you'll need to take special care of requests that are not GET/Retrieve, meaning, idempotent PATCH/POST/Create/Update/Upsert/Delete requests.

**Comment by JimDaly** [comment]
I have updated this topic to add specific numbers, but also cautioning about how they are used since they are evaluated per web server.  Currently the max concurrent connection value per user is 52.

But I don't recommend depending on batch operations as @mohsinonxrm mentioned, Those operations take longer and end up contributing to the combined execution time limit.

If you have a lot of relatively light, quick operations to perform, use multiple threads which represent more concurrent connections, up to the limit of 52. But if your operations are heavier because they are combined as batch operations, you may start to bump into the total execution time limits.

The recommended strategy is to listen to the Retry-After values returned and let the server tell you how quickly it can accept new requests. If you are using the [Microsoft.Xrm.Tooling.Connector.CrmServiceClient](https://docs.microsoft.com/en-us/dotnet/api/microsoft.xrm.tooling.connector.crmserviceclient) it should take care of this for you.

I hope this helps.
