### ISSUE TITLE
Most minimalistic... once more.

### ISSUE THREAD

**Issue by schittli** [MicrosoftDocs/powerapps-docs#71]
it's a shame that M$ no longer offer the related section. You're really not able to maintain a simple list of related things?
Yes, it's a shame.

It's great to have google: the answer the question.
But if Google is more interested to have productive and therefore happy users - why should we use M$ products?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ccab736b-a56a-46eb-72df-675e16b16203
* Version Independent ID: 568bb9b0-a455-2336-a416-29c266a9e660
* Content: [DateValue, TimeValue, and DateTimeValue functions - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-datevalue-timevalue)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-datevalue-timevalue.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-datevalue-timevalue.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by AFTOwen** [comment]
Thanks for your feedback, @schittli! Like other topics of this type, this topic has links to related content inline. For example, it links to the procedural topic for working with dates and times, as well as the reference topics for the Date, Time, Value, Language, Text, and DateDiff functions throughout the topic. Perhaps these links are difficult to see, or you would rather see them in separate sentences or a single list at the end of the topic instead of where they relate to the discussion.

We’re continually refining our approach and priorities, and your comment will inform our discussion.
