### ISSUE TITLE
Deployment Steps

### ISSUE THREAD

**Issue by interfacemirror** [MicrosoftDocs/powerapps-docs#723]
Can we have documentation around deployment steps? I have downloaded these samples but I just get errors and cannot use them

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b78efa0d-09e0-ebac-cce2-19362bdfb602
* Version Independent ID: 000cbd45-8d9a-bb1e-8d9a-a685fe9907b2
* Content: [Web API component - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/sample-controls/webapi-control)
* Content Source: [powerapps-docs/developer/component-framework/sample-controls/webapi-control.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/component-framework/sample-controls/webapi-control.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@interfacemirror Thanks for the feedback. Once you have downloaded the samples, you need to create a solution file, so that you can import into your instance. Follow the steps mentioned [here](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/implementing-controls-using-typescript#packaging-your-code-components). If you're still facing the issues, please raise your issue in the [community forum](https://powerusers.microsoft.com/t5/PowerApps-Component-Framework/bd-p/pa_component_framework), our developers will help you resolving the issue

**Comment by Nkrb** [comment]
Closing the issue.
