### ISSUE TITLE
Need Additional Callout/Clarification

### ISSUE THREAD

**Issue by daryllabar** [MicrosoftDocs/powerapps-docs#741]
This stems from a bug I introduced with my misunderstanding for how the patch function works.

I believe this line:
    Patch returns the merged record and doesn't modify its arguments or records in any data sources.
in this section:
    https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-patch#merge-records-outside-of-a-data-source
should be called out as a warning, since it's completely opposite to how the Patch function works with collections.

I also believe an example should be added for this section:
    https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-patch#merge-records-outside-of-a-data-source-1
that updates a variable in the context as well, just to additionally call out that the first item in the patch, is not updated.

Special thanks to Carlos Figueria for calling out my misunderstanding here: https://powerusers.microsoft.com/t5/Building-PowerApps-Formerly/How-Do-Variables-References-Work-In-Canvas-Apps/m-p/389338#M113480

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b39cb78-75da-5e8c-f105-1f0b9ea1b830
* Version Independent ID: 28bfec67-a78a-4a0d-cfc6-e95a560f7092
* Content: [Patch function - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-patch#merge-records-outside-of-a-data-source-1)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-patch.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-patch.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by daryllabar** [comment]
Actually, I guess I still didn't understand what is going on until I did some additional testing.
Items are never actually updated with the Patch function.  Just new items are created and replace the item in the collection for Datasource calls, and the "merged" item is returned from an item patch.

**Comment by daryllabar** [comment]
Here is a fun test that so far every single person I've asked has got wrong:

![image](https://user-images.githubusercontent.com/9728423/67525540-ecc39c00-f680-11e9-9379-8cb54181275c.png)

What will the value of Collection be and what will the value of newItem be?  I know that is crazy in depth, but if creators can understand and explain the answer, then they will have a very firm grasp of how Patch really works, and not spend hours debugging and guessing.

**Comment by tapanm-MSFT** [comment]
@daryllabar please find responses in chronological order. I would also suggest to please reach out to our support teams via a support service request that can be created through https://admin.powerplatform.microsoft.com/support for additional help with your samples. 

1 - regarding separate callout of warning:

This is part of 3 different methods to work with Patch. Modify/create record inside data source, modify/create a set of records inside data source, and last being this one which is modify/create record outside data source. 

2 - regarding context variable:

https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-patch#modify-or-create-a-record-in-a-data-source does refer ‘context variable’ for base record when modifying record. However, it might be useful to have sample like this:

UpdateContext({ newItem: { name: Text(CountRows(Myvariable)+1), qty: 0 }});

Collect(Myvariable,newItem);
Patch(Myvariable, newItem, { qty:1 });
Patch(Myvariable, newItem, { qty:2 });

3 - Modification of record in addition to create/replace:

Following sample updates 1st record in above collection with patch and updates from qty of 1 to 200, as an example that it can do modify as documented:

Patch(Myvariable, {name:1,qty:1}, { qty:200 });

4 - Sample test and result:

Both Patch() add new items. First Patch creates new item with name 1, qty 0 and modifies qty to 1 as supplied. Second Patch adds new item but only adds qty as 2 with no name since Patch doesn’t supply newItem’s name variable value. 

Take following example:

UpdateContext({ newItem: { name: 5, qty: 10 }});
Clear(Myvariable);
ClearCollect(Myvariable,newItem);
Patch(Myvariable, newItem, { name: CountRows(Myvariable)+1, qty:5 });
Patch(Myvariable, {name: CountRows(Myvariable)+1}, { name: CountRows(Myvariable)+10, qty:50 });

The output is always name as 11 and qty as 50. 

Another example uses collection and adds first record through Patch as 1 & 5. Next update context updates record to 2/10 and patch after that adds 1 more row of 2/10. Next one updates this 2/10 to 3/10 since newItem matches existing record of 2/10. And last patch adds new 4/11 since there’s no 2/10 anymore. 

Collect(Myvariable,{name:0,qty:0});
Clear(Myvariable);
Patch(Myvariable, {name: CountRows(Myvariable)}, { name: CountRows(Myvariable)+1, qty:5 });
UpdateContext({ newItem: { name: 2, qty: 10 }});
Patch(Myvariable, newItem, newItem);
Patch(Myvariable, newItem, { name: 3, qty: 10 });
Patch(Myvariable, newItem, { name: 4, qty: 11 });

As mentioned above, please feel free to raise a support service request for additional help on additional testing.
