### ISSUE TITLE
Use in non-MS applications

### ISSUE THREAD

**Issue by MisinformedDNA** [MicrosoftDocs/powerapps-docs#79]
I'm creating a new API and like the idea of using CDM but there is no instruction on how to apply the schemas to C#/ASP.NET or OpenAPI or anything else. Is there more information that can be provided?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe02d091-db7a-6cc8-32ef-10682bb9bf3b
* Version Independent ID: 4f46052e-07b2-ac66-49e2-8775d2f73a26
* Content: [Development using the Common Data Model - PowerApps](https://docs.microsoft.com/en-us/powerapps/common-data-model/use-common-data-model)
* Content Source: [powerapps-docs/common-data-model/use-common-data-model.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/common-data-model/use-common-data-model.md)
* Service: **powerapps**
* GitHub Login: @RobertBruckner
* Microsoft Alias: **robruc**

**Comment by johnholliday** [comment]
One approach is to copy the JSON endpoint URLs and use them to fetch the schema for the entities you wish to use.  Assuming the endpoints don't change dramatically, your app can stay in sync with the current set of entity definitions.

As an example, to retrieve the current schema for the "Contact" entity, simply enter the following into your browser or invoke it from your app:

https://raw.githubusercontent.com/Microsoft/CDM/master/schemaDocuments/core/applicationCommon/Contact.cdm.json

To get the list of available entities within a branch, request the "_allImports" object:

https://raw.githubusercontent.com/Microsoft/CDM/master/schemaDocuments/core/applicationCommon/foundationCommon/_allImports.cdm.json

This can be a bit tricky because the "uri" field must be handled appropriately.  Uri values that begin with "/" refer to the "schemaDocuments" path segment, otherwise they refer to the "current" segment (in this case, "applicationCommon/foundationCommon").

Hope this helps.

**Comment by theresapalmer** [comment]
Hi Dan - per our email thread let's follow up offline on your scenario and options to accomplish this given our current and future work. Looking forward to discussing!
