### ISSUE TITLE
$bacth implications on API limits

### ISSUE THREAD

**Issue by gregdegruy** [MicrosoftDocs/powerapps-docs#796]
"We limit the number of API requests made by each user, per organization instance, within a five minute sliding window. Additionally, we limit the number of concurrent requests that may come in at one time. When one of these limits is exceeded, an exception will be thrown by the platform."

For example for a PowerApps per user plan is the limit 5,000 individual `$bacth` calls and does a `$bacth` requests just count as 1 towards this limit? How many calls can be a part of this `$bacth` for it to still count as 1?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fd657fb-b2cb-a85a-7243-41d7cc30dc87
* Version Independent ID: 4ed6833a-668b-ff05-97da-286fb6d68394
* Content: [API Limits (Common Data Service) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/api-limits#feedback)
* Content Source: [powerapps-docs/developer/common-data-service/api-limits.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/api-limits.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **bsimons**

**Comment by JimDaly** [comment]
Batch operations are considered a single call.

Keep in mind that this topic is about _Service Protection_ limits, so the _Entitlement_ limits you mention (_the PowerApps per user plan_) are irrelevant unless you are just trying to reduce the total number of requests to stay below your entitlement.

I've added a new topic: [Common Data Service API limits overview](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/api-limits-overview) to try to help differentiate these limits from a Common Data Service standpoint.

In a sense, they are both service protection limits because they both serve to protect shared resources. A broad analogy could be that the Entitlement limits are like the number of miles you can drive in a rented care. The Service Protection limits are about how fast you can drive.

Wrapping things in batch operations might help you avoid Entitlement limits, but they don't provide any benefit in terms of service protection limits. These calls are larger because they bundle multiple calls together. They take more time and therefore contribute to the combined execution time when you are using multiple threads (connections).

**Comment by JimDaly** [comment]
@gregdegruy 
Before I close this out, I want to call out that wrapping CRUD operations within a $batch is not an effective strategy to bypass Entitlement limits. The Entitlement limits are enforced at a lower level.
