### ISSUE TITLE
Cannot set the Webresource title

### ISSUE THREAD

**Issue by aboodh95** [MicrosoftDocs/powerapps-docs#851]
Hi,

Once i opened a web-resource using the navigateTo, i was not able to set the title of it, and it's showing the URL of it as a title

![image](https://user-images.githubusercontent.com/12459798/70421899-2fe89b80-1a84-11ea-97b4-971f70137d68.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c917fb9-84c8-2676-9c6a-f33f03ba5da7
* Version Independent ID: 057dd7ac-8383-1650-ceb5-cbea3995180c
* Content: [navigateTo (Client API reference) in model-driven apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/xrm-navigation/navigateto#feedback)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Navigation/navigateTo.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Navigation/navigateTo.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by Jdawg20** [comment]
As of right now there is not a parameter in the function that can set that label.  I would assume since this is bleeding edge it will be coming in the near future.  For now if you get the h1 element with the data-id of "dialogTitleText" you can then set the value of the header.  This is a hack of the DOM which isn't supported because Microsoft could change the data-id at anytime and doesn't have to tell anyone so one day it could work and the next it doesn't.  But it could be a temporary fix until the feature is added in the future.

**Comment by martynlesbirel-axon** [comment]
When you create the web resource you reference in the pageInfo object the Display Name value of that web resource becomes the title of the modal window.

**Comment by Nkrb** [comment]
@aboodh95 
Thanks for your feedback. For product-related feedback, visit https://ideas.powerapps.com. Closing this issue.
